import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const route = fs.readFileSync("app/api/v1/crm/leads/route.ts", "utf8");
const page = fs.readFileSync("app/(crm)/leads/page.tsx", "utf8");
const report = fs.readFileSync("components/reports/WeeklyDeveloperPerformance.tsx", "utf8");
const reportsPage = fs.readFileSync("app/(crm)/reports/page.tsx", "utf8");

test("filas de qualidade consultam a base sem modificar leads", () => {
  assert.match(route, /allowedQualityFilters/);
  assert.match(route, /query = query\.is\("project_id", null\)/);
  assert.match(route, /query = query\.is\("campaign_id", null\)/);
  assert.match(route, /source\.is\.null,source\.eq\./);
  assert.match(route, /quality,/);
  assert.match(page, /params\.set\("quality", quality\)/);
  assert.match(page, /missing_source/);
  assert.match(page, /Nenhum dado é alterado automaticamente/);
});

test("relatório encaminha cada pendência para uma ação real", () => {
  assert.match(report, /data-report-quality-action/);
  assert.match(report, /const pendingQualityActions/);
  assert.match(report, /data-report-quality-pending/);
  assert.match(report, /data-report-quality-clear/);
  assert.match(report, /Nenhuma pendência de vínculo nesta coorte/);
  assert.match(report, /quality: "missing_project"/);
  assert.match(report, /quality: "missing_campaign"/);
  assert.match(report, /missingSource/);
  assert.match(report, /leads têm projeto,\s*incorporadora, campanha e origem registrados/);
  assert.match(report, /quality: "missing_source"/);
  assert.match(report, /attention: "unassigned"/);
  assert.match(report, /coverageLabel: "com origem"/);
  assert.match(report, /coverageLabel: "distribuídas"/);
  assert.match(report, /\/developments\/developers/);
  assert.match(report, /data-report-project-action/);
  assert.match(report, /<th>Sem corretor<\/th>/);
  assert.match(report, /Math\.max\(0, row\.leads - row\.assigned\)/);
  assert.match(report, /const interactionsByProject/);
  assert.match(report, /const silentAssignedProjects/);
  assert.match(report, /<th>Interações<\/th>/);
  assert.match(report, /interactionsByProject\.get\(row\.developmentId/);
  assert.match(report, /Há leads neste projeto sem interação registrada no período/);
  assert.match(report, /data-report-silent-projects/);
  assert.match(report, /data-report-silent-project-action/);
  assert.match(report, /Projetos já distribuídos, mas sem interação no período/);
  assert.match(report, /data-report-project-broker-action/);
  assert.match(report, /const unassignedProjectBrokers/);
  assert.match(report, /data-report-unassigned-projects/);
  assert.match(report, /data-report-unassigned-project-action/);
  assert.match(report, /Ver carteira pendente/);
  assert.match(report, /Revisar \{row\.leads\} leads/);
  assert.match(report, /const leadsInMeasuredPeriodHref/);
  assert.match(report, /project: row\.developmentId/);
  assert.match(report, /params\.set\("created_after", report\.period\.start\)/);
  assert.match(report, /params\.set\("created_before", report\.period\.end\)/);
  assert.match(page, /requestedProject/);
  assert.match(page, /requestedBroker/);
  assert.match(page, /const requestedStatus = url\.searchParams\.get\("status"\)\?\.trim\(\)/);
  assert.match(page, /function isKnownLeadStatus/);
  assert.match(page, /if \(isKnownLeadStatus\(requestedStatus\)\) setStatus\(requestedStatus\)/);
  assert.match(page, /\["status", "quality", "attention", "project", "campaign", "broker", "source", "created_after", "created_before"\]/);
  assert.match(page, /const hasReportDrilldown/);
  assert.match(page, /It must not\n\s*\/\/ inherit a previous workspace filter/);
  assert.match(page, /data-leads-report-context/);
  assert.match(page, /clearProjectFilter/);
  assert.match(page, /clearBrokerFilter/);
  assert.match(page, /data-leads-attention-filter/);
  assert.match(page, /clearAttentionFilter/);
  assert.match(page, /search\.trim\(\)/);
  assert.match(page, /Report drilldowns use URL parameters/);
  assert.match(page, /"created_after"/);
  assert.match(page, /"created_before"/);
  assert.match(route, /const createdBefore = createdBeforeFilter\(params\.get\("created_before"\)\)/);
  assert.match(route, /query = query\.lt\("created_at", createdBefore\)/);
  assert.match(route, /INVALID_CREATED_RANGE/);
});

test("relatório de campanhas abre a carteira no recorte exato", () => {
  assert.match(report, /data-report-campaign-action/);
  assert.match(report, /data-report-campaign-broker-action/);
  assert.match(report, /data-report-campaign-bottleneck-action/);
  assert.match(report, /data-report-broker-priority-action/);
  assert.match(report, /data-report-campaign-journey-action/);
  assert.match(report, /data-report-campaign-next-decision/);
  assert.match(report, /const priorityCampaigns = observedCampaignJourneys/);
  assert.match(report, /data-report-priority-campaigns/);
  assert.match(report, /data-report-priority-campaign=/);
  assert.match(report, /data-report-priority-campaign-action=/);
  assert.match(report, /Onde a liderança deve agir agora/);
  assert.match(report, /const leadRosterFilters: Record<string, string> \| null =/);
  assert.match(report, /attention: "unassigned"/);
  assert.match(report, /status: "novo"/);
  assert.match(report, /status: bottleneckStatus\(largestQueue\.label\)!/);
  assert.match(report, /const leadRosterLabel =/);
  assert.match(report, /Abrir fila sem corretor →/);
  assert.match(report, /Abrir leads sem contato →/);
  assert.match(report, /Abrir etapa crítica →/);
  assert.match(report, /const needsFirstContact = Boolean\(row\.brokerId && row\.leads > row\.contacted\);/);
  assert.match(report, /quality: "missing_campaign"/);
  assert.match(report, /broker: row\.brokerId/);
  assert.match(report, /\.\.\.\(needsFirstContact \? \{ status: "novo" \} : \{\}\)/);
  assert.match(report, /\.\.\.\(broker\.unattended > 0 \? \{ status: "novo" \} : \{\}\)/);
  assert.match(report, /Abrir leads sem contato →/);
  assert.match(report, /const nextDecision =/);
  assert.match(report, /Priorizar primeiro contato/);
  assert.match(report, /Tratar fila: \$\{largestQueue\.label\}/);
  assert.match(report, /bottleneckRecommendation\(largestQueue\.label\)/);
  assert.match(report, /"Próxima decisão"/);
  assert.match(report, /"Orientação operacional"/);
  assert.match(report, /\.\.\.observedCampaignJourneys\.map\(\(row\) => \[/);
  assert.match(report, /campaign: campaign\.campaignId/);
  assert.match(report, /campaign: row\.campaignId/);
  assert.match(page, /requestedCampaign/);
  assert.match(page, /requestedSource/);
  assert.match(page, /params\.set\("campaign_ids", campaign\)/);
  assert.match(page, /data-leads-campaign-filter/);
  assert.match(page, /Carteira da campanha/);
  assert.match(page, /clearCampaignFilter/);
  assert.match(page, /data-leads-source-filter/);
  assert.match(page, /Origem selecionada/);
  assert.match(page, /clearSourceFilter/);
  assert.match(page, /const campaignNameMap/);
  assert.match(page, /campaignNameMap\.get\(campaign\)/);
});

test("relatório sinaliza quando a leitura de campanha não possui amostra suficiente", () => {
  assert.match(report, /const minimumDescriptiveSample = 30/);
  assert.match(report, /Amostra descritiva ≥ \$\{minimumDescriptiveSample\}/);
  assert.match(report, /Amostra insuficiente · \$\{campaign\.leads\}\/\$\{minimumDescriptiveSample\}/);
  assert.match(
    report,
    /não mede lift, ganho incremental nem efeito causal/,
  );
});

test("relatório evidencia leads de campanha sem atendimento registrado", () => {
  assert.match(report, /unattendedLeads: Math\.max\(0, campaign\.leads - campaign\.contacted\)/);
  assert.match(report, /data-report-campaign-unattended/);
  assert.match(report, /sem atendimento registrado/);
  assert.match(report, /Atendimento registrado para toda a coorte/);
  assert.match(report, /"Sem atendimento registrado"/);
  assert.match(report, /"Cobertura de atendimento"/);
  assert.match(report, /const campaignExecutionById/);
  assert.match(report, /activeBrokers: new Set<string>\(\)/);
  assert.match(report, /assignedBrokers:/);
  assert.match(report, /data-report-campaign-idle-brokers/);
  assert.match(report, /data-report-campaign-unassigned/);
  assert.match(report, /data-report-campaign-developer-attribution/);
  assert.match(report, /data-report-campaign-configuration-action/);
  assert.match(report, /data-report-campaign-execution/);
  assert.match(report, /attentionOrder:/);
  assert.match(report, /data-report-campaign-priority-order/);
  assert.match(report, /não é uma nota de desempenho/);
  assert.match(report, /Sem distribuição/);
  assert.match(report, /Distribuição pendente:/);
  assert.match(report, /const campaignLargestQueue/);
  assert.match(report, /Maior fila comercial/);
  assert.match(report, /Maior fila:/);
  assert.match(report, /Priorizar primeiro contato/);
  assert.match(report, /Definir distribuição/);
  assert.match(report, /Tratar fila:/);
  assert.match(report, /Incorporadora inferida pelo CRM/);
  assert.match(report, /Incorporadora pendente/);
  assert.match(report, /Revisar cadastro da campanha/);
  assert.match(report, /"Corretores atribuídos"/);
  assert.match(report, /"Corretores com interação"/);
  assert.match(report, /"Corretores sem interação"/);
  assert.match(report, /"Interações registradas"/);
  assert.match(report, /Execução registrada:/);
});

test("carteira mantém o período do relatório visível e removível", () => {
  assert.match(page, /function clearReportPeriod\(\)/);
  assert.match(page, /url\.searchParams\.delete\("created_after"\)/);
  assert.match(page, /url\.searchParams\.delete\("created_before"\)/);
  assert.match(page, /data-leads-report-period/);
  assert.match(page, /Ver todo o período/);
  assert.match(page, /const reportPeriodLabel = createdAfter/);
  assert.match(page, /até \$\{formatDate\(createdBefore\)\}/);
});

test("indicadores do relatório respeitam o recorte operacional selecionado", () => {
  assert.match(report, /const scopedInteractions/);
  assert.match(report, /const hasOperationalScope/);
  assert.match(report, /selection\.leads/);
  assert.match(report, /selection\.contacted/);
  assert.match(report, /selection\.qualified/);
  assert.match(report, /selection\.wins/);
  assert.match(report, /const bottleneckRecommendation/);
  assert.match(report, /const bottleneckStatus/);
  assert.match(report, /const bottleneckActionHref/);
  assert.match(report, /data-report-bottleneck-action/);
  assert.match(report, /const developerOperationalPriorities/);
  assert.match(report, /const brokerOperationalPriorities/);
  assert.match(report, /data-report-broker-priority-watchlist/);
  assert.match(report, /Carteiras que pedem revisão humana/);
  assert.match(report, /const projectServiceWatchlist/);
  assert.match(report, /data-report-project-service-watchlist/);
  assert.match(report, /Onde revisar a velocidade de atendimento/);
  assert.match(report, /const slowAverage =/);
  assert.match(report, /const lowWithin15Rate =/);
  assert.match(report, /reviewReason:/);
  assert.match(report, /Média acima de 15 min e menos de 50% em até 15 min/);
  assert.match(report, /const unattended = Math\.max\(0, project\.leads - project\.contacted\);/);
  assert.match(report, /const unattendedHref =/);
  assert.match(report, /project: project\.developmentId,\s*status: "novo"/);
  assert.match(report, /Revisar \{unattended\} sem contato →/);
  assert.match(report, /SLA em \{project\.service\.measured\} de \{project\.leads\} lead/);
  assert.match(report, /SLA POR PROJETO \(APENAS AMOSTRA MEDIDA\)/);
  assert.match(report, /const projectFunnelWatchlist/);
  assert.match(report, /data-report-project-funnel-watchlist/);
  assert.match(report, /Fila que pode travar conversão por projeto/);
  assert.match(report, /GARGALO DO FUNIL POR PROJETO/);
  assert.match(report, /const visibleDailyDistribution/);
  assert.match(report, /data-report-daily-distribution/);
  assert.match(report, /Separação entre distribuição e atendimento/);
  assert.match(report, /DISTRIBUIÇÃO DIÁRIA POR PROJETO E CORRETOR/);
  assert.match(report, /data-report-daily-distribution-summary/);
  assert.match(report, /const brokerDailyWorkload/);
  assert.match(report, /firstContactRate:/);
  assert.match(report, /data-report-broker-daily-workload=/);
  assert.match(report, /CARGA DIÁRIA POR CORRETOR/);
  assert.match(report, /const actionLabel = needsNewLeadReview/);
  assert.match(report, /Registrar contato em \$\{broker\.withoutFirstContact\} lead/);
  assert.match(report, /\{broker\.firstContactRate\}% com primeiro contato/);
  assert.match(report, /Cobertura de primeiro contato de \$\{broker\.brokerName\}/);
  assert.match(report, /aria-valuenow=\{broker\.firstContactRate\}/);
  assert.match(report, /Carteiras com responsável atual no recorte/);
  assert.match(report, /status: bottleneckStatus\(largestQueue\.label\)/);
  assert.match(report, /data-report-developer-priority-watchlist/);
  assert.match(report, /data-report-developer-priority=/);
  assert.match(report, /data-report-developer-priority-action=/);
  assert.match(report, /Atenção por incorporadora/);
  assert.match(report, /Prioridades operacionais por incorporadora/);
  assert.match(report, /PRIORIDADES OPERACIONAIS POR INCORPORADORA/);
  assert.match(report, /Projeto de referência/);
  assert.match(report, /const \[copyStatus, setCopyStatus\]/);
  assert.match(report, /async function copyExecutiveSummary/);
  assert.match(report, /data-report-copy-executive-summary/);
  assert.match(report, /data-report-copy-status=/);
  assert.match(report, /Resumo copiado para envio/);
  assert.match(report, /Leitura baseada nos registros do CRM/);
  assert.match(report, /Qualidade da atribuição:/);
  assert.match(report, /Mídia: \$\{scopedFinancial\.spend === null/);
  assert.match(report, /Distribuir \$\{unassigned\} lead/);
  assert.match(report, /const actionLabel = !row\.brokerId/);
  assert.match(report, /Distribuir \$\{row\.leads\} lead/);
  assert.match(report, /Registrar primeiro contato →/);
  assert.match(report, /Distribuição necessária antes do atendimento/);
  assert.match(report, /Abrir carteira desta etapa/);
  assert.match(report, /const hasNoRegisteredInteraction/);
  assert.match(report, /const brokerActionLabel/);
  assert.match(report, /Abrir carteira do projeto/);
  assert.match(report, /Abrir carteira do corretor/);
  assert.match(report, /Abrir carteira da campanha/);
  assert.match(report, /converter interesse qualificado em visita agendada/);
  assert.match(report, /selection\.bottleneck\.recommendation/);
  assert.match(report, /const interactionRhythm/);
  assert.match(report, /por lead ·/);
  assert.match(report, /Primeiro contato pendente:/);
});

test("exportação e impressão identificam o recorte escolhido", () => {
  assert.match(report, /const fileSafeSegment/);
  assert.match(report, /fileSafeSegment\(selectedScope\)/);
  assert.match(report, /function printReport\(\)/);
  assert.match(report, /Atlas One — \$\{selectedScope\}/);
  assert.match(report, /Imprimir recorte/);
  assert.match(report, /QUALIDADE DA ATRIBUIÇÃO \(COORTE COMPLETA DO PERÍODO\)/);
  assert.match(report, /Leads com atribuição completa/);
  assert.match(report, /DISTRIBUIÇÃO PENDENTE POR PROJETO/);
  assert.match(report, /Nenhuma pendência no recorte/);
  assert.match(report, /ATENDIMENTO SEM REGISTRO POR PROJETO/);
  assert.match(report, /Nenhum projeto sem interação no recorte/);
  assert.match(report, /Interações registradas/);
  assert.match(report, /"Sem contato"/);
  assert.match(report, /const withoutContact = Math\.max\(0, row\.leads - row\.contacted\)/);
  assert.match(report, /Leads que ainda não chegaram à etapa de contato no período\./);
  assert.match(report, /\.\.\.filteredDailyDistribution\.map\(\(row\) => \[/);
  assert.doesNotMatch(report, /\.\.\.visibleDailyDistribution\.map\(\(row\) => \[/);
  assert.match(report, /const visibleBrokerDailyWorkload = useMemo/);
  assert.match(report, /\.\.\.brokerDailyWorkload\.map\(\(row\) => \[/);
  assert.match(report, /visibleBrokerDailyWorkload\.map\(\(broker\) => \{/);
  assert.match(report, /const allDeveloperOperationalPriorities = visibleDevelopers/);
  assert.match(report, /\.\.\.allDeveloperOperationalPriorities\.map\(\(row\) => \[/);
  assert.match(report, /const developerOperationalPriorities = allDeveloperOperationalPriorities\.slice\(0, 3\)/);
  assert.match(report, /\? \{ attention: "unassigned" \}/);
  assert.match(report, /\? \{ status: "novo" \}/);
  assert.match(report, /"Venda",\s*"Taxa de contato",\s*"Conversão"/);
  assert.match(
    report,
    /row\.stages\.contrato,\s*row\.stages\.ganho,\s*row\.contactRate/,
  );
  assert.doesNotMatch(report, /row\.stages\.ganho,\s*row\.stages\.ganho,/);
});

test("relatórios distinguem período geral de medição por incorporadora", () => {
  assert.match(reportsPage, /const periodLabel/);
  assert.match(reportsPage, /Os indicadores gerais abaixo consideram/);
  assert.match(reportsPage, /Campanhas cadastradas no período/);
  assert.match(reportsPage, /relatório\s+por incorporadora acima/);
  assert.match(report, /id="relatorio-incorporadoras"/);
  assert.match(report, /Resultado semanal registrado/);
  assert.match(report, /não atribui causalidade automática/);
  assert.doesNotMatch(report, /Resultado semanal comprovado/);
});

test("campanhas mostram apenas dados cadastrados e conduzem à gestão", () => {
  assert.match(reportsPage, /import Link from "next\/link"/);
  assert.match(reportsPage, /campaignStatusLabel/);
  assert.match(reportsPage, /campaign\.status/);
  assert.match(reportsPage, /Nenhuma campanha cadastrada neste recorte/);
  assert.match(reportsPage, /Gerenciar campanhas/);
  assert.match(reportsPage, /href="\/marketing\/campaigns"/);
  assert.match(reportsPage, /Leads informadas/);
  assert.match(reportsPage, /Carteira CRM/);
  assert.match(reportsPage, /Abrir carteira →/);
  assert.match(reportsPage, /const leadsByCampaignHref/);
  assert.match(reportsPage, /new URLSearchParams\(\{ campaign: campaignId \}\)/);
  assert.match(reportsPage, /const leadsBySourceHref/);
  assert.match(reportsPage, /const leadsMissingSourceHref/);
  assert.match(reportsPage, /quality: "missing_source"/);
  assert.match(reportsPage, /Revisar origem →/);
  assert.match(reportsPage, /params\.set\("created_after", reportStart\)/);
  assert.match(page, /createdAfter/);
  assert.match(page, /params\.set\("created_after", createdAfter\)/);
  assert.match(route, /function createdAfterFilter/);
  assert.match(route, /query = query\.gte\("created_at", createdAfter\)/);
});
