"use client";import Link from"next/link";import{useParams}from"next/navigation";import{useEffect,useState}from"react";import{supabase}from"@/lib/supabase";import{AtlasBadge,AtlasEmpty,AtlasSkeleton}from"@/components/ui/AtlasUI";import{AtlasCard,AtlasCardHeader,AtlasMetric}from"@/components/ui/AtlasCard";
type Objection={id:string;objection_type:string;objection_text:string;detected_source:string;response_text:string|null;response_source:string|null;status:string;outcome_stage:string|null;outcome_notes:string|null;created_by:string|null;resolved_by:string|null;resolved_at:string|null;created_at:string;updated_at:string};
type Payload={lead:{id:string;name:string};objections:Objection[];summary:{total:number;open:number;overcome:number};objectionTypes:readonly string[];canAct:boolean};
/* eslint-disable @typescript-eslint/no-unused-expressions -- resposta compacta mantém os dois setters explícitos */
const typeLabel:Record<string,string>={PRICE:"Preço",FINANCING:"Financiamento",LOCATION:"Localização",SIZE:"Tamanho/Metragem",TIMING:"Momento/Prazo",TRUST:"Confiança",PRODUCT:"Produto",COMPETITOR:"Concorrente",OTHER:"Outra"};
const statusTone:Record<string,"success"|"danger"|"warning"|"info">={OPEN:"warning",ANSWERED:"info",OVERCOME:"success",NOT_OVERCOME:"danger"};
const statusLabel:Record<string,string>={OPEN:"Em aberto",ANSWERED:"Respondida",OVERCOME:"Superada",NOT_OVERCOME:"Não superada"};
export default function ObjectionsPage(){const{id}=useParams<{id:string}>(),[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[form,setForm]=useState({objectionType:"PRICE",objectionText:""}),[suggesting,setSuggesting]=useState<string|null>(null),[drafts,setDrafts]=useState<Record<string,string>>({});
async function token(){return(await supabase.auth.getSession()).data.session?.access_token}
async function load(){const t=await token();if(!t){setError("Sessão expirada.");return}const r=await fetch(`/api/v1/leads/${id}/objections`,{headers:{Authorization:`Bearer ${t}`}}),p=await r.json();r.ok?setData(p.data):setError(p.error?.message||p.error||"Objeções indisponíveis.")}
useEffect(()=>{void load()},[id]);
async function add(event:React.FormEvent){event.preventDefault();if(form.objectionText.trim().length<5)return;setBusy(true);const t=await token(),r=await fetch(`/api/v1/leads/${id}/objections`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify(form)}),p=await r.json();if(!r.ok)setError(p.error?.message||p.error||"Objeção não registrada.");else{setForm({objectionType:"PRICE",objectionText:""});await load()}setBusy(false)}
async function suggest(o:Objection){setSuggesting(o.id);setError("");const t=await token(),r=await fetch("/api/ai/copilot",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({leadId:id,prompt:`O cliente desta lead levantou a seguinte objeção de vendas (tipo: ${typeLabel[o.objection_type]||o.objection_type}): "${o.objection_text}". Sugira uma resposta comercial curta, honesta e persuasiva para o corretor usar, sem prometer desconto ou condição que não foi confirmada.`}),}),p=await r.json();if(!r.ok)setError(p.error?.message||p.error||"Não foi possível gerar sugestão.");else setDrafts(current=>({...current,[o.id]:String(p.answer||"")}));setSuggesting(null)}
async function resolve(o:Objection,status:string){setBusy(true);const t=await token(),r=await fetch(`/api/v1/leads/${id}/objections`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({objectionId:o.id,status,responseText:drafts[o.id]||o.response_text||""})}),p=await r.json();if(!r.ok)setError(p.error?.message||p.error||"Não foi possível concluir.");else await load();setBusy(false)}
return <div className="space-y-6 pb-10" data-phase="atlas-lead-objections"><section className="atlas-grid-glow rounded-[30px] border border-amber-400/10 bg-gradient-to-br from-amber-500/[.1] via-orange-500/[.06] to-rose-500/[.1] p-6 sm:p-8"><Link href={`/leads/${id}`} className="text-sm font-semibold text-sky-300">← Voltar à lead</Link><div className="mt-5 flex flex-wrap gap-2"><AtlasBadge tone="warning">OBJEÇÕES DE VENDA</AtlasBadge><AtlasBadge tone="info">SUGESTÃO DE RESPOSTA POR IA</AtlasBadge><AtlasBadge tone="violet">DECISÃO SEMPRE DO CORRETOR</AtlasBadge></div><h1 className="mt-5 text-3xl font-semibold text-white sm:text-5xl">O que está travando {data?.lead.name||"esta lead"}?</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">Registre a objeção real do cliente, peça uma sugestão de resposta e acompanhe se ela foi superada — histórico útil para a próxima conversa e para o aprendizado comercial.</p></section>
{error?<div className="rounded-2xl border border-rose-400/20 bg-rose-400/10 p-4 text-rose-200">{error}</div>:null}
{data?<section className="grid gap-4 sm:grid-cols-3"><AtlasMetric label="Total registradas" value={data.summary.total} detail="Desde o início da lead" trend="HISTÓRICO" tone="blue"/><AtlasMetric label="Em aberto" value={data.summary.open} detail="Precisam de resposta" trend="ATENÇÃO" tone="amber"/><AtlasMetric label="Superadas" value={data.summary.overcome} detail="Cliente seguiu em frente" trend="CONVERSÃO" tone="green"/></section>:null}
{!data&&!error?<AtlasSkeleton className="h-72 w-full"/>:null}
{data?.canAct?<AtlasCard><AtlasCardHeader eyebrow="Nova objeção" title="Registrar o que o cliente disse" description="Quanto mais específico o texto, melhor a sugestão de resposta."/><form onSubmit={add} className="space-y-3 p-5"><select value={form.objectionType} onChange={e=>setForm({...form,objectionType:e.target.value})} className="w-full rounded-xl border border-white/10 bg-[#0a1120] p-3 text-white">{(data.objectionTypes||[]).map(t=><option key={t} value={t}>{typeLabel[t]||t}</option>)}</select><textarea required minLength={5} value={form.objectionText} onChange={e=>setForm({...form,objectionText:e.target.value})} placeholder="Ex: achou o preço acima do que esperava para o tamanho do apartamento" className="min-h-24 w-full rounded-xl border border-white/10 bg-white/[.035] p-3 text-white"/><button disabled={busy} className="atlas-button-primary w-full">{busy?"Registrando...":"Registrar objeção"}</button></form></AtlasCard>:null}
<AtlasCard><AtlasCardHeader eyebrow="Linha do tempo" title="Objeções desta lead" description="Da mais recente para a mais antiga."/><div className="space-y-4 p-5">{data?.objections.map(o=><article key={o.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] uppercase tracking-wider text-slate-500">{typeLabel[o.objection_type]||o.objection_type}</span><p className="mt-1 text-sm text-white">{o.objection_text}</p><p className="mt-1 text-xs text-slate-500">{new Date(o.created_at).toLocaleString("pt-BR")}</p></div><AtlasBadge tone={statusTone[o.status]||"info"}>{statusLabel[o.status]||o.status}</AtlasBadge></div>
{o.response_text?<p className="mt-3 rounded-xl border border-emerald-400/15 bg-emerald-400/[.05] p-3 text-sm text-emerald-100">Resposta usada: {o.response_text}</p>:null}
{data.canAct&&o.status==="OPEN"?<div className="mt-3 space-y-2"><button onClick={()=>void suggest(o)} disabled={suggesting===o.id} className="atlas-button-secondary">{suggesting===o.id?"Pensando...":"✦ Sugerir resposta"}</button>{drafts[o.id]?<div className="rounded-xl border border-sky-400/15 bg-sky-400/[.05] p-3"><p className="text-sm text-slate-200">{drafts[o.id]}</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>void resolve(o,"OVERCOME")} disabled={busy} className="atlas-button-primary">Usei e superou</button><button onClick={()=>void resolve(o,"ANSWERED")} disabled={busy} className="atlas-button-secondary">Usei, aguardando</button></div></div>:null}<button onClick={()=>void resolve(o,"NOT_OVERCOME")} disabled={busy} className="text-xs text-slate-500 underline">Marcar como não superada</button></div>:null}
</article>)}{data&&!data.objections.length?<AtlasEmpty title="Nenhuma objeção registrada" description="Quando o cliente hesitar, registre aqui para a IA ajudar com a resposta."/>:null}</div></AtlasCard></div>}
