"use client";
import { useEffect, useState } from "react";

type Payload = { summary: Record<string, number | string | boolean | null>; platforms: Array<Record<string, number | string | boolean | null>>; ranking: Array<Record<string, number | string | boolean | null>> };
const brl = (value: unknown) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }).format(Number(value || 0));

export default function CampaignIntelligencePage() {
  const [days, setDays] = useState(30); const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; fetch(`/api/v1/campaign-intelligence?days=${days}`, { cache: "no-store" }).then(async (response) => { const json = await response.json(); if (!response.ok) throw new Error(json?.error?.message || "Painel indisponível"); return json.data as Payload; }).then((value) => active && setData(value)).catch((reason) => active && setError(reason.message)); return () => { active = false; }; }, [days]);
  const summary = data?.summary || {};
  return <main data-phase="91-multichannel-campaign-intelligence" className="mx-auto max-w-7xl space-y-8 p-4 md:p-8">
    <header className="rounded-[28px] border border-blue-500/20 bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 p-7 text-white shadow-2xl"><div className="text-xs font-semibold tracking-[.24em] text-blue-300">META · GOOGLE · TIKTOK · YOUTUBE · PORTAIS</div><h1 className="mt-3 text-3xl font-semibold tracking-tight">Inteligência de campanhas</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Custos comparáveis, funil imobiliário real e decisões da diretoria com origem auditável.</p><div className="mt-5 flex items-center gap-3"><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">CRM É A VERDADE DA CONVERSÃO</span><select aria-label="Período" value={days} onChange={(event) => setDays(Number(event.target.value))} className="rounded-full border border-white/15 bg-white/5 px-3 py-1 text-xs"><option className="text-slate-900" value={7}>7 dias</option><option className="text-slate-900" value={30}>30 dias</option><option className="text-slate-900" value={90}>90 dias</option></select></div></header>
    {error ? <div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">{error}</div> : null}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Investimento", brl(summary.spend)], ["Leads CRM", summary.crmLeads || 0], ["Vendas", summary.wins || 0], ["ROAS", summary.roas == null ? "—" : `${summary.roas}x`]].map(([label, value]) => <article key={String(label)} className="rounded-3xl border bg-white p-5 shadow-sm"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><strong className="mt-2 block text-2xl text-slate-950">{value}</strong></article>)}</section>
    <section><h2 className="text-lg font-semibold">Comparativo por canal</h2><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{(data?.platforms || []).map((item) => <article key={String(item.platform)} className="rounded-3xl border bg-white p-5"><div className="text-xs font-semibold uppercase tracking-wider text-blue-700">{String(item.platform).replace("_ads", "")}</div><div className="mt-4 text-xl font-semibold">{brl(item.spend)}</div><div className="mt-2 text-sm text-slate-500">{Number(item.crmLeads || 0)} leads · {Number(item.wins || 0)} vendas</div><div className="mt-4 text-xs text-slate-400">CPL {item.cpl == null ? "—" : brl(item.cpl)} · ROAS {item.roas == null ? "—" : `${item.roas}x`}</div></article>)}</div></section>
    <section className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Ranking de performance</h2><p className="text-sm text-slate-500">RANKING COM AMOSTRA MÍNIMA: 30 leads confirmadas no CRM.</p></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase text-slate-400"><tr><th className="py-3">Campanha</th><th>Canal</th><th>Leads</th><th>Qualificadas</th><th>Visitas</th><th>Vendas</th><th>CPL</th><th>ROAS</th><th>Confiança</th></tr></thead><tbody>{(data?.ranking || []).map((item) => <tr key={`${item.platform}-${item.campaignKey}`} className="border-t"><td className="py-4 font-medium">{String(item.campaignName)}</td><td>{String(item.platform)}</td><td>{Number(item.crmLeads || 0)}</td><td>{Number(item.qualifiedLeads || 0)}</td><td>{Number(item.visits || 0)}</td><td>{Number(item.wins || 0)}</td><td>{item.cpl == null ? "—" : brl(item.cpl)}</td><td>{item.roas == null ? "—" : `${item.roas}x`}</td><td><span className={`rounded-full px-2 py-1 text-xs ${item.sampleSufficient ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{item.sampleSufficient ? String(item.confidence) : "aguardar amostra"}</span></td></tr>)}</tbody></table>{data?.ranking?.length === 0 ? <p className="py-10 text-center text-sm text-slate-500">Conectores prontos para receber os primeiros snapshots homologados.</p> : null}</div></section>
  </main>;
}
