import { canonicalPipelineStage, mergePipelineStageSettings, type PipelineStageDefinition, type PipelineStageKey } from "@/lib/atlas/pipeline-stages";

export type FunnelLead={id:string;status:string|null;created_at:string};
export type FunnelMove={id:string;lead_id:string;from_stage:string;to_stage:string;occurred_at:string;reversal_of?:string|null};
type StageInput=Partial<PipelineStageDefinition>&{stage_key?:string};
const day=86_400_000;const time=(value:string)=>{const parsed=new Date(value).getTime();return Number.isFinite(parsed)?parsed:null};const rounded=(value:number)=>Math.round(value*10)/10;const median=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);return sorted.length?rounded((sorted[Math.floor((sorted.length-1)/2)]+sorted[Math.ceil((sorted.length-1)/2)])/2):null};

export function buildFunnelVelocity(leads:FunnelLead[],moves:FunnelMove[],settings:StageInput[]=[],now=new Date(),windowDays=90){
  const stages=mergePipelineStageSettings(settings.map(item=>({key:item.key,stage_key:item.stage_key,label:item.label,probability:item.probability,position:item.position,visible:item.visible})));const stageMap=new Map(stages.map(stage=>[stage.key,stage]));const cutoff=now.getTime()-windowDays*day;
  const cohort=leads.filter(lead=>(time(lead.created_at)??0)>=cutoff);const cohortIds=new Set(cohort.map(lead=>lead.id));const cohortMoves=moves.filter(move=>cohortIds.has(move.lead_id)&&time(move.occurred_at)!==null).sort((a,b)=>(time(a.occurred_at)??0)-(time(b.occurred_at)??0));
  const reached=new Map<string,Set<PipelineStageKey>>();for(const lead of cohort)reached.set(lead.id,new Set(["novo"]));for(const move of cohortMoves){const from=canonicalPipelineStage(move.from_stage),to=canonicalPipelineStage(move.to_stage);if(from)reached.get(move.lead_id)?.add(from);if(to)reached.get(move.lead_id)?.add(to);}
  const ordered=stages.filter(stage=>stage.outcome==="open"||stage.outcome==="won");const transitions=ordered.slice(0,-1).map((stage,index)=>{const next=ordered[index+1];const entered=[...reached.values()].filter(set=>set.has(stage.key)).length;const advanced=[...reached.values()].filter(set=>set.has(stage.key)&&set.has(next.key)).length;return{fromKey:stage.key,fromLabel:stage.label,toKey:next.key,toLabel:next.label,entered,advanced,conversionRate:entered?rounded(advanced/entered*100):0,sampleSufficient:entered>=30};});
  const durations=new Map<string,number[]>();const perLead=new Map<string,FunnelMove[]>();for(const move of cohortMoves){const list=perLead.get(move.lead_id)??[];list.push(move);perLead.set(move.lead_id,list);}for(const lead of cohort){const sequence=perLead.get(lead.id)??[];let entered=time(lead.created_at);let current:PipelineStageKey="novo";for(const move of sequence){const occurred=time(move.occurred_at);if(entered!==null&&occurred!==null&&occurred>=entered){const list=durations.get(current)??[];list.push((occurred-entered)/day);durations.set(current,list);}const next=canonicalPipelineStage(move.to_stage);if(next)current=next;entered=occurred;}}
  const velocity=stages.filter(stage=>stage.outcome==="open").map(stage=>{const values=durations.get(stage.key)??[];return{key:stage.key,label:stage.label,completedTransitions:values.length,medianDays:median(values),averageDays:values.length?rounded(values.reduce((sum,value)=>sum+value,0)/values.length):null,sampleSufficient:values.length>=10};});
  const won=cohort.filter(lead=>canonicalPipelineStage(lead.status)==="ganho"||reached.get(lead.id)?.has("ganho")).length;const lost=cohort.filter(lead=>canonicalPipelineStage(lead.status)==="perdido"||reached.get(lead.id)?.has("perdido")).length;const reversals=cohortMoves.filter(move=>{const from=canonicalPipelineStage(move.from_stage),to=canonicalPipelineStage(move.to_stage);return Boolean(move.reversal_of)||(from&&to&&(stageMap.get(to)?.position??0)<(stageMap.get(from)?.position??0));}).length;
  const reliableTransitions=transitions.filter(item=>item.sampleSufficient).length;return{summary:{windowDays,cohort:cohort.length,movements:cohortMoves.length,won,lost,winRate:cohort.length?rounded(won/cohort.length*100):0,reversals},transitions,velocity,confidence:{score:cohort.length?Math.min(100,Math.round(Math.min(50,cohort.length/2)+Math.min(30,cohortMoves.length/3)+reliableTransitions/Math.max(1,transitions.length)*20)):0,minimumConversionSample:30,minimumVelocitySample:10,reliableTransitions,totalTransitions:transitions.length},governance:{cohortBased:true,hierarchicalRls:true,causalityClaimed:false,peopleRanking:false,automaticDecision:false}};
}
