export type TaskCenterRow={id:string;title:string|null;description:string|null;due_at:string|null;priority:string|null;status:string|null;lead_id:string|null;assigned_to:string|null;created_at?:string|null;lead?:{id:string;name:string|null;purpose:string|null}|null};
const DONE=new Set(["done","concluido","concluida","completed","cancelado","cancelled"]);const time=(value:string|null)=>{const parsed=value?new Date(value).getTime():Number.NaN;return Number.isFinite(parsed)?parsed:null};
export function buildTaskCenter(rows:TaskCenterRow[],profiles:Array<{id:string;full_name:string|null}>,actorId:string,now=new Date()){
  const completed=rows.filter(row=>DONE.has(String(row.status||"").toLowerCase())).length;
  const names=new Map(profiles.map(profile=>[profile.id,profile.full_name||"Profissional sem nome"]));const start=new Date(now);start.setHours(0,0,0,0);const end=start.getTime()+86_400_000;
  const tasks=rows.filter(row=>!DONE.has(String(row.status||"").toLowerCase())).map(row=>{const due=time(row.due_at),overdue=due!==null&&due<now.getTime(),today=due!==null&&due>=start.getTime()&&due<end,priority=String(row.priority||"normal").toLowerCase();const priorityScore=(overdue?300:today?180:0)+(priority==="alta"||priority==="high"||priority==="critical"?100:priority==="media"||priority==="medium"?40:0)+(due===null?20:Math.max(0,72-Math.floor((due-now.getTime())/3_600_000)));return{...row,title:row.title||"Tarefa comercial",priority,status:row.status||"pendente",overdue,today,priorityScore,assigneeName:row.assigned_to?names.get(row.assigned_to)||"Responsável não identificado":"Sem responsável",mine:row.assigned_to===actorId};}).sort((a,b)=>b.priorityScore-a.priorityScore||(time(a.due_at)??Number.MAX_SAFE_INTEGER)-(time(b.due_at)??Number.MAX_SAFE_INTEGER));
  const owners=new Map<string,{id:string;name:string;open:number;overdue:number;today:number;high:number}>();for(const task of tasks){const id=task.assigned_to||"unassigned",entry=owners.get(id)||{id,name:task.assigneeName,open:0,overdue:0,today:0,high:0};entry.open++;if(task.overdue)entry.overdue++;if(task.today)entry.today++;if(["alta","high","critical"].includes(task.priority))entry.high++;owners.set(id,entry);}
  return{summary:{open:tasks.length,completed,overdue:tasks.filter(task=>task.overdue).length,today:tasks.filter(task=>task.today).length,high:tasks.filter(task=>["alta","high","critical"].includes(task.priority)).length,withoutDueDate:tasks.filter(task=>time(task.due_at)===null).length,unassigned:tasks.filter(task=>!task.assigned_to).length,mine:tasks.filter(task=>task.mine).length},tasks,byOwner:[...owners.values()].sort((a,b)=>b.overdue-a.overdue||b.open-a.open),governance:{priorityExplainable:true,hierarchicalRls:true,arbitraryUpdate:false,automaticAssignment:false,peopleRanking:false}};
}
