"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { AtlasBadge, AtlasEmpty, AtlasSkeleton } from "@/components/ui/AtlasUI";
import { AtlasCard, AtlasCardHeader, AtlasMetric } from "@/components/ui/AtlasCard";

type Developer={id:string;legal_name:string;trade_name:string;cnpj:string|null;website:string|null;commercial_email:string|null;commercial_phone:string|null;headquarters_city:string|null;headquarters_state:string|null;default_commission_sla_days:number;status:string;projects:number};
type Payload={developers:Developer[];summary:{total:number;active:number;onboarding:number;linkedProjects:number}};
const initial={id:"",legalName:"",tradeName:"",cnpj:"",website:"",commercialEmail:"",commercialPhone:"",headquartersCity:"",headquartersState:"",defaultCommissionSlaDays:30,status:"onboarding",notes:""};

export default function DevelopersPage(){
 const[data,setData]=useState<Payload|null>(null),[form,setForm]=useState(initial),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 async function token(){const{data}=await supabase.auth.getSession();return data.session?.access_token||""}
 async function load(){setLoading(true);const response=await fetch("/api/v1/developers",{headers:{Authorization:`Bearer ${await token()}`}});const body=await response.json();if(response.ok)setData(body.data);else setMessage(body.error?.message||"Falha ao carregar incorporadoras.");setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function save(){setSaving(true);setMessage("");const response=await fetch("/api/v1/developers",{method:"POST",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json();if(response.ok){setMessage("Incorporadora salva como fonte única da verdade.");setForm(initial);await load()}else setMessage(body.error?.message||"Não foi possível salvar.");setSaving(false)}
 function edit(item:Developer){setForm({id:item.id,legalName:item.legal_name,tradeName:item.trade_name,cnpj:item.cnpj||"",website:item.website||"",commercialEmail:item.commercial_email||"",commercialPhone:item.commercial_phone||"",headquartersCity:item.headquarters_city||"",headquartersState:item.headquarters_state||"",defaultCommissionSlaDays:item.default_commission_sla_days,status:item.status,notes:""});window.scrollTo({top:0,behavior:"smooth"})}
 const fields=[['Razão social','legalName'],['Nome comercial','tradeName'],['CNPJ','cnpj'],['Site HTTPS','website'],['E-mail comercial','commercialEmail'],['Telefone comercial','commercialPhone'],['Cidade sede','headquartersCity'],['UF','headquartersState']] as const;
 return <div className="space-y-6 pb-12" data-phase="61-canonical-developers">
  <section className="atlas-grid-glow rounded-[30px] border border-blue-400/15 bg-gradient-to-br from-blue-500/[.12] via-cyan-500/[.06] to-violet-500/[.08] p-6 sm:p-8"><AtlasBadge tone="info">FASE 61 · FONTE ÚNICA</AtlasBadge><h1 className="mt-5 text-3xl font-semibold tracking-[-.04em] text-white sm:text-5xl">Incorporadoras organizadas, projetos conectados.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">Um cadastro canônico para projetos, materiais, estoque, regras de pagamento, comissão e relatórios. O nome antigo permanece apenas para compatibilidade da migração.</p><div className="mt-5 flex gap-3"><Link href="/developments" className="atlas-button-secondary">Voltar ao portfólio</Link><Link href="/developments/payment-rules" className="atlas-button-secondary">Regras de pagamento</Link></div></section>
  {message?<div className="rounded-2xl border border-sky-400/20 bg-sky-400/10 p-4 text-sm text-sky-100">{message}</div>:null}
  <section className="grid gap-4 sm:grid-cols-4"><AtlasMetric label="Incorporadoras" value={loading?"—":data?.summary.total??0} detail="Cadastro canônico" trend="ÚNICO" tone="blue"/><AtlasMetric label="Ativas" value={loading?"—":data?.summary.active??0} detail="Em operação" trend="ATIVAS" tone="green"/><AtlasMetric label="Onboarding" value={loading?"—":data?.summary.onboarding??0} detail="Dados em preparação" trend="REVISAR" tone="amber"/><AtlasMetric label="Projetos ligados" value={loading?"—":data?.summary.linkedProjects??0} detail="Vínculo por identificador" trend="ID" tone="violet"/></section>
  <AtlasCard><AtlasCardHeader eyebrow="Cadastro governado" title={form.id?"Editar incorporadora":"Nova incorporadora"} description="Diretoria e superintendência mantêm os dados. CNPJ é normalizado e único dentro da empresa."/><div className="grid gap-3 p-5 sm:grid-cols-2 sm:p-6 lg:grid-cols-4">
   {fields.map(([label,key])=><label key={key} className="text-xs text-slate-400">{label}<input value={String(form[key])} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-3 text-sm text-white"/></label>)}
   <label className="text-xs text-slate-400">SLA padrão de comissão<input type="number" min={0} max={365} value={form.defaultCommissionSlaDays} onChange={e=>setForm({...form,defaultCommissionSlaDays:Number(e.target.value)})} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-3 text-sm text-white"/></label>
   <label className="text-xs text-slate-400">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-3 text-sm text-white">{["onboarding","active","inactive","archived"].map(value=><option key={value}>{value}</option>)}</select></label>
   <label className="text-xs text-slate-400 lg:col-span-2">Observações internas<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} maxLength={2000} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-3 text-sm text-white"/></label>
   <div className="sm:col-span-2 lg:col-span-4 flex justify-end gap-2">{form.id?<button onClick={()=>setForm(initial)} className="atlas-button-secondary">Cancelar</button>:null}<button disabled={saving||form.legalName.trim().length<2||form.tradeName.trim().length<2} onClick={()=>void save()} className="atlas-button-primary disabled:opacity-50">{saving?"Salvando...":"Salvar incorporadora"}</button></div>
  </div></AtlasCard>
  <AtlasCard><AtlasCardHeader eyebrow="Fonte única" title="Incorporadoras cadastradas" description="Projetos vinculados por ID, sem depender de variações de escrita."/><div className="grid gap-4 p-5 sm:p-6 lg:grid-cols-2">
   {loading?[1,2].map(i=><AtlasSkeleton key={i} className="h-40"/>):(data?.developers??[]).map(item=><article key={item.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-5"><div className="flex items-start justify-between"><div><p className="text-xs text-slate-500">{item.legal_name}</p><h2 className="mt-1 text-lg font-semibold text-white">{item.trade_name}</h2><p className="mt-2 text-xs text-slate-400">{[item.headquarters_city,item.headquarters_state].filter(Boolean).join(" · ")||"Sede não informada"} · {item.projects} projeto(s)</p></div><AtlasBadge tone={item.status==="active"?"success":item.status==="onboarding"?"warning":"neutral"}>{item.status}</AtlasBadge></div><div className="mt-4 grid grid-cols-2 gap-2"><Link href={`/developments?developer=${encodeURIComponent(item.trade_name)}`} className="atlas-button-secondary text-center">Ver projetos</Link><Link href={`/developments/materials?developer=${encodeURIComponent(item.trade_name)}`} className="atlas-button-secondary text-center">Abrir materiais</Link></div><div className="mt-4 flex items-center justify-between border-t border-white/[.06] pt-4"><span className="text-xs text-slate-500">Comissão padrão: {item.default_commission_sla_days} dias</span><button onClick={()=>edit(item)} className="text-xs font-semibold text-sky-300">Editar cadastro</button></div></article>)}
   {!loading&&!data?.developers.length?<div className="lg:col-span-2"><AtlasEmpty title="Nenhuma incorporadora" description="Cadastre a primeira para vincular projetos e regras."/></div>:null}
  </div></AtlasCard>
 </div>
}
