"use client";
import { useEffect, useState } from "react";
import { AtlasBadge, AtlasSkeleton } from "@/components/ui/AtlasUI";
import { AtlasCard, AtlasCardHeader, AtlasMetric } from "@/components/ui/AtlasCard";
import { supabase } from "@/lib/supabase";

type Status = { connected: boolean; reason?: string; phone?: { idMasked?: string; displayNumber?: string; verifiedName?: string; qualityRating?: string; messagingLimitTier?: string; throughput?: { level?: string } | string; verificationStatus?: string; platformType?: string }; homologation?: { status: "passed" | "incomplete"; graphConfirmed: boolean; numberConfirmed: boolean; qualityConfirmed: boolean; limitConfirmed: boolean; readOnly: boolean }; templates?: Array<{ id: string; name: string; language: string; category: string }>; templateTests?: Array<{ id: string; status: string; sent_at?: string; delivered_at?: string; read_at?: string; error?: string; created_at: string }>; testRecipientMasked?: string | null; checkedAt?: string };

export default function WhatsAppIntegration() {
  const [data, setData] = useState<Status | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [templateId, setTemplateId] = useState("");
  const [sending, setSending] = useState(false);
  const [notice, setNotice] = useState("");
  async function load() { setLoading(true); setError(""); try { const token = (await supabase.auth.getSession()).data.session?.access_token || ""; const response = await fetch("/api/v1/integrations/whatsapp", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Diagnóstico indisponível."); setData(body.data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Diagnóstico indisponível."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function sendTemplateTest() { setSending(true); setError(""); setNotice(""); try { const token = (await supabase.auth.getSession()).data.session?.access_token || ""; const response = await fetch("/api/v1/integrations/whatsapp", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ templateId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Ensaio de template falhou."); setNotice(`${body.data.next} Protocolo ${body.data.externalMessageIdMasked}.`); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Ensaio de template falhou."); } finally { setSending(false); } }
  const quality = String(data?.phone?.qualityRating || "UNKNOWN").toUpperCase();
  const passed = data?.homologation?.status === "passed";
  return <div className="space-y-6 pb-10">
    <section className="atlas-grid-glow rounded-[30px] border border-emerald-400/10 bg-gradient-to-br from-emerald-500/[.11] via-cyan-500/[.06] to-blue-500/[.08] p-6 sm:p-8"><div className="flex flex-wrap gap-2"><AtlasBadge tone={data?.connected ? "success" : "danger"}>{data?.connected ? "API OFICIAL CONECTADA" : "CONFIGURAÇÃO PENDENTE"}</AtlasBadge><AtlasBadge tone={quality === "GREEN" ? "success" : quality === "YELLOW" ? "warning" : "danger"}>QUALIDADE {quality}</AtlasBadge><AtlasBadge tone={passed ? "success" : "warning"}>FASE 27 · {passed ? "COMPROVADA" : "PENDENTE"}</AtlasBadge></div><h1 className="mt-5 text-3xl font-semibold tracking-[-.04em] text-white sm:text-5xl">Saúde do <span className="atlas-gradient-text">WhatsApp Business.</span></h1><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-400">Leitura direta da Graph API para confirmar número, nome, qualidade, limite e capacidade da conta — sem alterar configurações ou revelar credenciais.</p><button disabled={loading} onClick={() => void load()} className="atlas-button-primary mt-6 disabled:opacity-40">{loading ? "Consultando Graph API..." : "Executar diagnóstico oficial"}</button></section>
    {error ? <div className="rounded-2xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-200">{error}</div> : null}
    {notice ? <div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm text-emerald-200">{notice}</div> : null}
    {loading ? <AtlasSkeleton className="h-48 w-full" /> : <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AtlasMetric label="Número" value={String(data?.phone?.displayNumber || "Não confirmado")} detail={`${String(data?.phone?.verifiedName || data?.reason || "")} ${data?.phone?.idMasked || ""}`.trim()} trend="BUSINESS" tone={data?.homologation?.numberConfirmed ? "green" : "amber"} /><AtlasMetric label="Qualidade Meta" value={quality} detail="Avaliação oficial do número" trend="QUALITY" tone={quality === "GREEN" ? "green" : "amber"} /><AtlasMetric label="Limite de mensagens" value={String(data?.phone?.messagingLimitTier || "Não informado")} detail="Tier retornado pela Meta" trend="LIMIT" tone={data?.homologation?.limitConfirmed ? "blue" : "amber"} /><AtlasMetric label="Throughput" value={typeof data?.phone?.throughput === "object" ? String(data.phone.throughput.level || "Ativo") : String(data?.phone?.throughput || "Não informado")} detail={data?.phone?.platformType ? `${data.phone.platformType} · ${data.phone.verificationStatus || ""}` : "Capacidade oficial da conta"} trend="API" tone="violet" /></section>}
    <AtlasCard><AtlasCardHeader eyebrow="Fase 27 · Evidência" title="Confirmação da Graph API" description="Cada item abaixo precisa ser confirmado pela própria Meta para o aceite funcional." /><div className="grid gap-3 p-5 sm:grid-cols-2 sm:p-6 xl:grid-cols-4">{[["Conta acessível", data?.homologation?.graphConfirmed], ["Número confirmado", data?.homologation?.numberConfirmed], ["Qualidade disponível", data?.homologation?.qualityConfirmed], ["Limite disponível", data?.homologation?.limitConfirmed]].map(([label, value]) => <div key={String(label)} className="flex items-center justify-between rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><span className="text-sm text-slate-300">{label}</span><AtlasBadge tone={value ? "success" : "warning"}>{value ? "CONFIRMADO" : "PENDENTE"}</AtlasBadge></div>)}</div>{data?.checkedAt ? <p className="px-5 pb-5 text-[10px] text-slate-500 sm:px-6 sm:pb-6">Última consulta: {new Date(data.checkedAt).toLocaleString("pt-BR")} · operação somente leitura</p> : null}</AtlasCard>
    <AtlasCard><AtlasCardHeader eyebrow="Fase 28 · Template oficial" title="Comprovar envio, entrega e leitura" description={`O envio é restrito ao número de homologação ${data?.testRecipientMasked || "não configurado"} e a templates aprovados sem variáveis. Após abrir a mensagem no aparelho, atualize o diagnóstico.`} /><div className="space-y-4 p-5 sm:p-6"><div className="grid gap-3 lg:grid-cols-[1fr_auto]"><select value={templateId} onChange={(event) => setTemplateId(event.target.value)} className="w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-white outline-none focus:border-emerald-400/40"><option value="">Selecione um template aprovado</option>{data?.templates?.map((template) => <option key={template.id} value={template.id}>{template.name} · {template.language} · {template.category}</option>)}</select><button disabled={!templateId || sending || !data?.connected || !data?.testRecipientMasked} onClick={() => void sendTemplateTest()} className="atlas-button-primary min-w-52 disabled:opacity-40">{sending ? "Enviando pela API..." : "Enviar para teste"}</button></div>{!data?.templates?.length ? <p className="text-xs text-amber-300">Cadastre e sincronize ao menos um template aprovado sem variáveis para executar esta fase.</p> : null}<div className="space-y-2">{data?.templateTests?.length ? data.templateTests.map((test) => <div key={test.id} className="grid gap-3 rounded-2xl border border-white/[.07] bg-white/[.025] p-4 sm:grid-cols-[1fr_auto_auto_auto]"><div><strong className="text-sm text-white">Teste {new Date(test.created_at).toLocaleString("pt-BR")}</strong>{test.error ? <p className="mt-1 text-xs text-rose-300">{test.error}</p> : null}</div>{[["Enviado", test.sent_at], ["Entregue", test.delivered_at], ["Lido", test.read_at]].map(([label, at]) => <div key={String(label)}><AtlasBadge tone={at ? "success" : "warning"}>{at ? "CONFIRMADO" : "AGUARDANDO"}</AtlasBadge><p className="mt-1 text-[10px] text-slate-500">{label}{at ? ` · ${new Date(at).toLocaleTimeString("pt-BR")}` : ""}</p></div>)}</div>) : <p className="text-xs text-slate-500">Nenhum ensaio de template registrado nesta organização.</p>}</div></div></AtlasCard>
    <AtlasCard><AtlasCardHeader eyebrow="Estratégia operacional" title="Proteções ativas" description="Camadas que reduzem risco e preservam a experiência — sem mascarar limites definidos pela Meta." /><div className="grid gap-3 p-5 sm:grid-cols-2 sm:p-6 xl:grid-cols-3">{["Templates previamente aprovados", "Opt-out verificado antes de cada envio", "Pacing e teto diário por campanha", "Worker com tomada atômica do evento", "Webhook de entrega, leitura e falha", "IA detecta atrito e pede decisão humana"].map((item) => <div key={item} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4 text-sm text-slate-300"><span className="mr-2 text-emerald-300">✓</span>{item}</div>)}</div></AtlasCard>
  </div>;
}
