"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
type Assessment={score:number;readiness:string;metrics:Record<string,number>;blockers:string[];recommendations:Array<{type:string;title:string;action:string}>};
type Cycle={id:string;readiness_score:number;readiness:string;status:string;blockers:string[];recommendations:Array<{title:string;action:string}>;decision_reason:string|null;created_at:string};
type Payload={live:Assessment|null;cycles:Cycle[];policy:Record<string,unknown>};
const label=(value:string)=>value.replaceAll("_"," ");
export default function AndromedaLoopPage(){const[data,setData]=useState<Payload|null>(null);const[busy,setBusy]=useState(false);const[reason,setReason]=useState<Record<string,string>>({});const[notice,setNotice]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/v1/integrations/meta/andromeda-loop",{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json?.error?.message||"Indisponível");setData(json.data)},[]);
 useEffect(()=>{load().catch((error)=>setNotice(error.message))},[load]);
 async function act(body:Record<string,unknown>){setBusy(true);setNotice("");try{const response=await fetch("/api/v1/integrations/meta/andromeda-loop",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const json=await response.json();if(!response.ok)throw new Error(json?.error?.message||"Ação recusada");setNotice(body.action==="generate"?"Ciclo de evidência registrado.":"Decisão registrada sem alterar campanhas automaticamente.");await load()}catch(error){setNotice(error instanceof Error?error.message:"Falha")}finally{setBusy(false)}}
 const live=data?.live;return <main data-phase="92-meta-andromeda-learning-loop" className="mx-auto max-w-7xl space-y-7 p-4 md:p-8">
  <header className="rounded-[30px] border border-violet-400/20 bg-[radial-gradient(circle_at_top_right,_#4338ca,_#08101f_48%)] p-7 text-white shadow-2xl"><p className="text-xs font-semibold tracking-[.22em] text-violet-300">CRM → CONVERSIONS API → ANDROMEDA</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-semibold tracking-tight">Loop de aprendizado governado</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Sinais consentidos, profundos e recentes; hipóteses para decisão humana, nunca mudança autônoma.</p></div><div className="flex gap-2"><Link href="/marketing/experiments" className="rounded-full border border-white/20 px-5 py-2.5 text-sm">Laboratório de testes</Link><button disabled={busy} onClick={()=>act({action:"generate"})} className="rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50">Registrar ciclo de 30 dias</button></div></div><div className="mt-5 flex flex-wrap gap-2 text-[11px]"><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-emerald-300">CONSENTIMENTO OBRIGATÓRIO</span><span className="rounded-full bg-amber-400/10 px-3 py-1 text-amber-200">MODO DE TESTE</span><span className="rounded-full bg-violet-400/10 px-3 py-1 text-violet-200">DECISÃO EXCLUSIVA DO DIRETOR</span></div></header>
  {notice&&<div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">{notice}</div>}
  <section className="grid gap-4 lg:grid-cols-[280px_1fr]"><article className="rounded-3xl border bg-white p-6 text-center"><p className="text-xs uppercase tracking-wider text-slate-500">Prontidão atual</p><strong className="mt-3 block text-6xl tracking-tighter text-slate-950">{live?.score??0}%</strong><span className="mt-3 inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{label(live?.readiness||"sem evidência")}</span></article><article className="rounded-3xl border bg-white p-6"><h2 className="font-semibold">Qualidade do sinal</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(live?.metrics||{}).map(([key,value])=><div key={key} className="rounded-2xl bg-slate-50 p-4"><span className="text-xs text-slate-500">{label(key)}</span><strong className="mt-1 block text-2xl">{value}%</strong></div>)}</div></article></section>
  <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-3xl border bg-white p-6"><h2 className="font-semibold">Bloqueadores de escala</h2>{live?.blockers.length?<ul className="mt-4 space-y-2 text-sm text-amber-800">{live.blockers.map(item=><li key={item} className="rounded-xl bg-amber-50 p-3">{label(item)}</li>)}</ul>:<p className="mt-4 text-sm text-emerald-700">Sinal apto somente para teste controlado; ainda depende da diretoria.</p>}</article><article className="rounded-3xl border bg-white p-6"><h2 className="font-semibold">Próximos testes sugeridos</h2><div className="mt-4 space-y-3">{(live?.recommendations||[]).map(item=><div key={item.title} className="rounded-2xl bg-violet-50 p-4"><strong className="text-sm text-violet-950">{item.title}</strong><p className="mt-1 text-xs leading-5 text-violet-700">{item.action}</p></div>)}</div></article></section>
  <section><h2 className="text-lg font-semibold">Histórico decisório</h2><p className="text-sm text-slate-500">Aprovar um ciclo autoriza análise e teste planejado; não executa público, verba ou campanha.</p><div className="mt-4 space-y-3">{(data?.cycles||[]).map(cycle=><article key={cycle.id} className="rounded-3xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-xs uppercase text-violet-700">{cycle.status}</span><h3 className="mt-1 font-semibold">Prontidão {cycle.readiness_score}% · {label(cycle.readiness)}</h3><small className="text-slate-400">{new Date(cycle.created_at).toLocaleString("pt-BR")}</small></div>{cycle.status==="draft"&&<div className="flex flex-wrap gap-2"><input aria-label="Justificativa" placeholder="Justificativa da diretoria" value={reason[cycle.id]||""} onChange={event=>setReason({...reason,[cycle.id]:event.target.value})} className="min-w-64 rounded-full border px-4 py-2 text-sm"/><button disabled={busy} onClick={()=>act({action:"decide",cycleId:cycle.id,decision:"approved",reason:reason[cycle.id]})} className="rounded-full bg-emerald-600 px-4 py-2 text-sm text-white">Aprovar teste</button><button disabled={busy} onClick={()=>act({action:"decide",cycleId:cycle.id,decision:"rejected",reason:reason[cycle.id]})} className="rounded-full bg-slate-800 px-4 py-2 text-sm text-white">Rejeitar</button></div>}</div>{cycle.decision_reason&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{cycle.decision_reason}</p>}</article>)}</div></section>
 </main>}
