"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { AtlasBadge, AtlasEmpty, AtlasSkeleton } from "@/components/ui/AtlasUI";
import { AtlasCard, AtlasCardHeader, AtlasMetric } from "@/components/ui/AtlasCard";

type Developer = { id: string; trade_name: string; status: string };
type Development = { id: string; developer_id: string | null; developer_name: string | null; name: string; project_code: string | null; city: string | null; state: string | null; product_type: string | null; sales_cycle_status: string; total_units: number | null };
type Payload = { developers: Developer[]; developments: Development[]; summary: { total: number; inSales: number; incomplete: number } };
const initial = { developerId: "", name: "", projectCode: "", addressLine: "", neighborhood: "", city: "", state: "SP", postalCode: "", latitude: "", longitude: "", marketSegment: "residencial", productType: "apartamento", typologies: "", bedroomsMin: "", bedroomsMax: "", privateAreaMin: "", privateAreaMax: "", priceMin: "", priceMax: "", totalUnits: "", status: "active", salesCycleStatus: "planning", launchDate: "", salesStartDate: "", salesEndDate: "", deliveryDate: "" };

export default function DevelopmentRegistryPage() {
  const [data, setData] = useState<Payload | null>(null); const [form, setForm] = useState(initial); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const input = "w-full rounded-xl border border-white/10 bg-white/[.035] px-3 py-2.5 text-sm text-white outline-none placeholder:text-slate-600 focus:border-sky-400/40";
  const field = (key: keyof typeof initial, label: string, type = "text") => <label className="space-y-1.5"><span className="text-xs text-slate-400">{label}</span><input className={input} type={type} value={form[key]} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} /></label>;
  async function token() { return (await supabase.auth.getSession()).data.session?.access_token; }
  async function load() { setLoading(true); const accessToken = await token(); if (!accessToken) { setMessage("Sessão expirada."); setLoading(false); return; } const response = await fetch("/api/v1/developments", { headers: { Authorization: `Bearer ${accessToken}` } }); const payload = await response.json(); if (response.ok) setData(payload); else setMessage(payload.error || "Falha ao carregar cadastro."); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function save() { setSaving(true); setMessage(""); const accessToken = await token(); const response = await fetch("/api/v1/developments", { method: "POST", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" }, body: JSON.stringify({ ...form, typologies: form.typologies.split(",").map((item) => item.trim()).filter(Boolean) }) }); const payload = await response.json(); if (response.ok) { setMessage("Empreendimento salvo e auditado."); setForm(initial); await load(); } else setMessage(payload.error || "Não foi possível salvar."); setSaving(false); }
  return <div className="space-y-6 pb-10" data-phase="62-complete-development-registry">
    <header className="rounded-[30px] border border-sky-400/10 bg-gradient-to-br from-sky-500/[.12] via-blue-500/[.06] to-violet-500/[.1] p-6 sm:p-8"><Link href="/developments" className="text-sm font-semibold text-sky-300">← Voltar ao portfólio</Link><div className="mt-5 flex gap-2"><AtlasBadge tone="info">FASE 62</AtlasBadge><AtlasBadge tone="success">CADASTRO CANÔNICO</AtlasBadge></div><h1 className="mt-4 text-3xl font-semibold text-white sm:text-5xl">Cadastro completo de empreendimentos</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-400">Uma ficha única conecta incorporadora, localização, produto, faixas comerciais e ciclo de vendas às demais inteligências do Atlas.</p></header>
    <section className="grid gap-4 sm:grid-cols-3"><AtlasMetric label="Empreendimentos" value={String(data?.summary.total ?? 0)} detail="Portfólio canônico" tone="blue"/><AtlasMetric label="Em vendas" value={String(data?.summary.inSales ?? 0)} detail="Ciclo comercial ativo" tone="green"/><AtlasMetric label="A completar" value={String(data?.summary.incomplete ?? 0)} detail="Dados essenciais pendentes" tone="amber"/></section>
    <AtlasCard><AtlasCardHeader eyebrow="Fonte operacional única" title="Nova ficha de projeto" description="Apenas diretoria e superintendência podem gravar; toda mudança fica auditada."/><div className="space-y-6 p-5 sm:p-6">
      <section><h2 className="mb-3 text-sm font-semibold text-white">Incorporadora canônica e identidade</h2><div className="grid gap-3 md:grid-cols-3"><label className="space-y-1.5"><span className="text-xs text-slate-400">Incorporadora canônica</span><select className={input} value={form.developerId} onChange={(e)=>setForm(c=>({...c,developerId:e.target.value}))}><option value="">Selecione</option>{data?.developers.map(d=><option key={d.id} value={d.id}>{d.trade_name}</option>)}</select></label>{field("name","Nome do empreendimento")}{field("projectCode","Código interno")}</div></section>
      <section><h2 className="mb-3 text-sm font-semibold text-white">Localização</h2><div className="grid gap-3 md:grid-cols-4">{field("addressLine","Endereço")} {field("neighborhood","Bairro")} {field("city","Cidade")} {field("state","UF")} {field("postalCode","CEP")} {field("latitude","Latitude","number")} {field("longitude","Longitude","number")}</div></section>
      <section><h2 className="mb-3 text-sm font-semibold text-white">Produto e tipologias</h2><div className="grid gap-3 md:grid-cols-4">{field("marketSegment","Segmento")} {field("productType","Tipo de produto")} {field("typologies","Tipologias, separadas por vírgula")} {field("totalUnits","Total de unidades","number")} {field("bedroomsMin","Dormitórios mín.","number")} {field("bedroomsMax","Dormitórios máx.","number")} {field("privateAreaMin","Área privativa mín.","number")} {field("privateAreaMax","Área privativa máx.","number")} {field("priceMin","Preço mín.","number")} {field("priceMax","Preço máx.","number")}</div></section>
      <section><h2 className="mb-3 text-sm font-semibold text-white">Ciclo comercial</h2><div className="grid gap-3 md:grid-cols-4"><label className="space-y-1.5"><span className="text-xs text-slate-400">Fase comercial</span><select className={input} value={form.salesCycleStatus} onChange={(e)=>setForm(c=>({...c,salesCycleStatus:e.target.value}))}>{[["planning","Planejamento"],["pre_launch","Pré-lançamento"],["launch","Lançamento"],["sales","Em vendas"],["sold_out","Esgotado"],["delivered","Entregue"],["suspended","Suspenso"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{field("launchDate","Lançamento","date")} {field("salesStartDate","Início das vendas","date")} {field("salesEndDate","Fim das vendas","date")} {field("deliveryDate","Entrega","date")}</div></section>
      {message?<p className="text-sm text-sky-200">{message}</p>:null}<button disabled={saving||!form.developerId||!form.name||!form.projectCode} onClick={()=>void save()} className="atlas-button-primary disabled:opacity-40">{saving?"Salvando...":"Salvar empreendimento"}</button>
    </div></AtlasCard>
    <AtlasCard><AtlasCardHeader eyebrow="Portfólio cadastrado" title="Projetos e prontidão" description="Identifique rapidamente fichas que ainda precisam ser completadas."/><div className="p-5 sm:p-6">{loading?<AtlasSkeleton className="h-40 w-full"/>:!data?.developments.length?<AtlasEmpty title="Nenhum empreendimento cadastrado" description="Preencha a primeira ficha completa acima."/>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.developments.map(item=><Link key={item.id} href={`/developments/${item.id}`} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4 hover:border-sky-400/30"><div className="flex justify-between gap-3"><div><p className="text-xs text-slate-500">{item.developer_name||"Sem incorporadora"} · {item.project_code||"Sem código"}</p><h3 className="mt-1 font-semibold text-white">{item.name}</h3></div><AtlasBadge tone={item.sales_cycle_status==="sales"?"success":"info"}>{item.sales_cycle_status}</AtlasBadge></div><p className="mt-3 text-sm text-slate-400">{[item.city,item.state].filter(Boolean).join(" · ")||"Localização pendente"} · {item.product_type||"Produto pendente"} · {item.total_units??"—"} unidades</p></Link>)}</div>}</div></AtlasCard>
  </div>;
}
