"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { AtlasBadge, AtlasEmpty, AtlasSkeleton } from "@/components/ui/AtlasUI";
import { AtlasCard, AtlasCardHeader, AtlasMetric } from "@/components/ui/AtlasCard";

type Developer = { id: string; trade_name: string; status: string };
type Development = { id: string; developer_id: string | null; developer_name: string | null; name: string; project_code: string | null; address_line: string | null; neighborhood: string | null; city: string | null; state: string | null; postal_code: string | null; latitude: number | null; longitude: number | null; market_segment: string | null; product_type: string | null; typologies: string[] | null; bedrooms_min: number | null; bedrooms_max: number | null; private_area_min: number | null; private_area_max: number | null; price_min: number | null; price_max: number | null; sales_cycle_status: string; status: string; total_units: number | null; launch_date: string | null; sales_start_date: string | null; sales_end_date: string | null; delivery_date: string | null };
type Payload = { developers: Developer[]; developments: Development[]; summary: { total: number; inSales: number; incomplete: number } };
const initial = { id: "", developerId: "", name: "", projectCode: "", addressLine: "", neighborhood: "", city: "", state: "SP", postalCode: "", latitude: "", longitude: "", marketSegment: "residencial", productType: "apartamento", typologies: "", bedroomsMin: "", bedroomsMax: "", privateAreaMin: "", privateAreaMax: "", priceMin: "", priceMax: "", totalUnits: "", status: "active", salesCycleStatus: "planning", launchDate: "", salesStartDate: "", salesEndDate: "", deliveryDate: "" };

export default function DevelopmentRegistryPage() {
  const [data, setData] = useState<Payload | null>(null); const [form, setForm] = useState(initial); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState("all");
  const input = "w-full rounded-xl border border-white/10 bg-white/[.035] px-3 py-2.5 text-sm text-white outline-none placeholder:text-slate-600 focus:border-sky-400/40";
  const field = (key: keyof typeof initial, label: string, type = "text") => <label className="space-y-1.5"><span className="text-xs text-slate-400">{label}</span><input className={input} type={type} value={form[key]} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} /></label>;
  async function token() { return (await supabase.auth.getSession()).data.session?.access_token; }
  async function load() { setLoading(true); const accessToken = await token(); if (!accessToken) { setMessage("Sessão expirada."); setLoading(false); return; } const response = await fetch("/api/v1/developments", { headers: { Authorization: `Bearer ${accessToken}` } }); const payload = await response.json(); if (response.ok) setData(payload.data); else setMessage(payload.error?.message || "Falha ao carregar cadastro."); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function save() { setSaving(true); setMessage(""); const accessToken = await token(); const response = await fetch("/api/v1/developments", { method: "POST", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" }, body: JSON.stringify({ ...form, typologies: form.typologies.split(",").map((item) => item.trim()).filter(Boolean) }) }); const payload = await response.json(); if (response.ok) { setMessage("Empreendimento salvo e auditado."); setForm(initial); await load(); } else setMessage(payload.error?.message || "Não foi possível salvar."); setSaving(false); }
  function edit(item: Development) {
    const value = (input: string | number | null) => input == null ? "" : String(input);
    setForm({ id: item.id, developerId: item.developer_id ?? "", name: item.name, projectCode: item.project_code ?? "", addressLine: item.address_line ?? "", neighborhood: item.neighborhood ?? "", city: item.city ?? "", state: item.state ?? "", postalCode: item.postal_code ?? "", latitude: value(item.latitude), longitude: value(item.longitude), marketSegment: item.market_segment ?? "", productType: item.product_type ?? "", typologies: (item.typologies ?? []).join(", "), bedroomsMin: value(item.bedrooms_min), bedroomsMax: value(item.bedrooms_max), privateAreaMin: value(item.private_area_min), privateAreaMax: value(item.private_area_max), priceMin: value(item.price_min), priceMax: value(item.price_max), totalUnits: value(item.total_units), status: item.status, salesCycleStatus: item.sales_cycle_status, launchDate: item.launch_date ?? "", salesStartDate: item.sales_start_date ?? "", salesEndDate: item.sales_end_date ?? "", deliveryDate: item.delivery_date ?? "" });
    window.scrollTo({ top: 0, behavior: "smooth" });
  }
  async function archive(item: Development) {
    if (!window.confirm(`Arquivar ${item.name}? O histórico será preservado.`)) return;
    const accessToken = await token();
    const response = await fetch(`/api/v1/developments/${item.id}`, { method: "DELETE", headers: { Authorization: `Bearer ${accessToken}` } });
    const payload = await response.json();
    setMessage(response.ok ? "Empreendimento arquivado sem apagar o histórico." : payload.error?.message || "Não foi possível arquivar.");
    if (response.ok) await load();
  }
  const visible = (data?.developments ?? []).filter((item) => {
    const matchesText = `${item.name} ${item.developer_name ?? ""} ${item.city ?? ""} ${item.project_code ?? ""}`.toLowerCase().includes(query.toLowerCase());
    return matchesText && (statusFilter === "all" || item.status === statusFilter);
  });
  return <div className="space-y-6 pb-10" data-phase="62-complete-development-registry">
    <header className="rounded-[30px] border border-sky-400/10 bg-gradient-to-br from-sky-500/[.12] via-blue-500/[.06] to-violet-500/[.1] p-6 sm:p-8"><Link href="/developments" className="text-sm font-semibold text-sky-300">← Voltar ao portfólio</Link><div className="mt-5 flex gap-2"><AtlasBadge tone="info">FASE 62</AtlasBadge><AtlasBadge tone="success">CADASTRO CANÔNICO</AtlasBadge></div><h1 className="mt-4 text-3xl font-semibold text-white sm:text-5xl">Cadastro completo de empreendimentos</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-400">Uma ficha única conecta incorporadora, localização, produto, faixas comerciais e ciclo de vendas às demais inteligências do Atlas.</p></header>
    <section className="grid gap-4 sm:grid-cols-3"><AtlasMetric label="Empreendimentos" value={String(data?.summary.total ?? 0)} detail="Portfólio canônico" tone="blue"/><AtlasMetric label="Em vendas" value={String(data?.summary.inSales ?? 0)} detail="Ciclo comercial ativo" tone="green"/><AtlasMetric label="A completar" value={String(data?.summary.incomplete ?? 0)} detail="Dados essenciais pendentes" tone="amber"/></section>
    <AtlasCard><AtlasCardHeader eyebrow="Fonte operacional única" title="Nova ficha de projeto" description="Apenas diretoria e superintendência podem gravar; toda mudança fica auditada."/><div className="space-y-6 p-5 sm:p-6">
      <section><h2 className="mb-3 text-sm font-semibold text-white">Incorporadora canônica e identidade</h2><div className="grid gap-3 md:grid-cols-3"><label className="space-y-1.5"><span className="text-xs text-slate-400">Incorporadora canônica</span><select className={input} value={form.developerId} onChange={(e)=>setForm(c=>({...c,developerId:e.target.value}))}><option value="">Selecione</option>{data?.developers.map(d=><option key={d.id} value={d.id}>{d.trade_name}</option>)}</select></label>{field("name","Nome do empreendimento")}{field("projectCode","Código interno")}</div></section>
      <section><h2 className="mb-3 text-sm font-semibold text-white">Localização</h2><div className="grid gap-3 md:grid-cols-4">{field("addressLine","Endereço")} {field("neighborhood","Bairro")} {field("city","Cidade")} {field("state","UF")} {field("postalCode","CEP")} {field("latitude","Latitude","number")} {field("longitude","Longitude","number")}</div></section>
      <section><h2 className="mb-3 text-sm font-semibold text-white">Produto e tipologias</h2><div className="grid gap-3 md:grid-cols-4">{field("marketSegment","Segmento")} {field("productType","Tipo de produto")} {field("typologies","Tipologias, separadas por vírgula")} {field("totalUnits","Total de unidades","number")} {field("bedroomsMin","Dormitórios mín.","number")} {field("bedroomsMax","Dormitórios máx.","number")} {field("privateAreaMin","Área privativa mín.","number")} {field("privateAreaMax","Área privativa máx.","number")} {field("priceMin","Preço mín.","number")} {field("priceMax","Preço máx.","number")}</div></section>
      <section><h2 className="mb-3 text-sm font-semibold text-white">Ciclo comercial</h2><div className="grid gap-3 md:grid-cols-4"><label className="space-y-1.5"><span className="text-xs text-slate-400">Fase comercial</span><select className={input} value={form.salesCycleStatus} onChange={(e)=>setForm(c=>({...c,salesCycleStatus:e.target.value}))}>{[["planning","Planejamento"],["pre_launch","Pré-lançamento"],["launch","Lançamento"],["sales","Em vendas"],["sold_out","Esgotado"],["delivered","Entregue"],["suspended","Suspenso"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{field("launchDate","Lançamento","date")} {field("salesStartDate","Início das vendas","date")} {field("salesEndDate","Fim das vendas","date")} {field("deliveryDate","Entrega","date")}</div></section>
      {message?<p className="text-sm text-sky-200">{message}</p>:null}<div className="flex gap-3"><button disabled={saving||!form.developerId||!form.name||!form.projectCode} onClick={()=>void save()} className="atlas-button-primary disabled:opacity-40">{saving?"Salvando...":form.id ? "Salvar alterações" : "Salvar empreendimento"}</button>{form.id ? <button className="atlas-button-secondary" onClick={() => setForm(initial)}>Cancelar edição</button> : null}</div>
    </div></AtlasCard>
    <AtlasCard><AtlasCardHeader eyebrow="Portfólio cadastrado" title="Projetos e prontidão" description="Busque, edite ou arquive sem apagar o histórico."/><div className="p-5 sm:p-6"><div className="mb-4 grid gap-3 sm:grid-cols-[1fr_220px]"><input className={input} placeholder="Buscar nome, incorporadora, cidade ou código" value={query} onChange={e => setQuery(e.target.value)}/><select className={input} value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="all">Todos os status</option><option value="active">Ativos</option><option value="archived">Arquivados</option></select></div>{loading?<AtlasSkeleton className="h-40 w-full"/>:!visible.length?<AtlasEmpty title="Nenhum empreendimento encontrado" description="Revise os filtros ou cadastre a primeira ficha."/>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map(item=><article key={item.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex justify-between gap-3"><div><p className="text-xs text-slate-500">{item.developer_name||"Sem incorporadora"} · {item.project_code||"Sem código"}</p><h3 className="mt-1 font-semibold text-white">{item.name}</h3></div><AtlasBadge tone={item.sales_cycle_status==="sales"?"success":"info"}>{item.sales_cycle_status}</AtlasBadge></div><p className="mt-3 text-sm text-slate-400">{[item.city,item.state].filter(Boolean).join(" · ")||"Localização pendente"} · {item.product_type||"Produto pendente"} · {item.total_units??"—"} unidades</p><div className="mt-4 flex flex-wrap gap-3 text-xs font-semibold"><Link className="text-sky-300" href={`/developments/${item.id}`}>Visualizar</Link><button className="text-violet-300" onClick={() => edit(item)}>Editar</button>{item.status !== "archived" ? <button className="text-rose-300" onClick={() => void archive(item)}>Arquivar</button> : null}</div></article>)}</div>}</div></AtlasCard>
  </div>;
}
