import{type NextRequest}from"next/server";import{apiError,apiSuccess,structuredApiLog}from"@/lib/api/core";import{enforceRateLimit,requireAccessContext}from"@/lib/api/security";import{getSupabaseAdmin}from"@/lib/supabase/admin";import{logger}from"@/lib/observability/logger";import{buildVisitChecklist,recommendedPostVisitAction,VISIT_NEXT_STEPS,VISIT_OBJECTIONS,VISIT_OUTCOMES}from"@/lib/commercial/visit-proposal-assistant";import{respostasDoFormularioNoMetadata,respostasLegadoNoMetadata,sinaisUnificados,unificarQualificacao}from"@/lib/crm/qualificacao-canonica";
/**
 * ── "0% QUALIFICADA" PARA QUEM JÁ TINHA RESPONDIDO ──────────────────────────
 *
 * O percentual saía de `lead_qualification_profiles.answered_count` e só de lá.
 * Medido em 02/08/2026: 13 das 15 leads que responderam em `/qualify` não têm
 * linha no perfil, e o assistente abria a preparação da visita dizendo
 * "0% qualificada" para gente que já tinha dito objetivo, prazo e pagamento.
 *
 * O perfil segue sendo a gaveta canônica; o que faltava era LER as outras em
 * vez de tratar a ausência de linha como ausência de resposta. As oito colunas
 * do perfil continuam sendo o denominador — `sinaisUnificados` conta os mesmos
 * oito campos, agora enxergando os que estavam na outra gaveta.
 */
async function contextFor(org:string,leadId:string){const admin=getSupabaseAdmin(),{data:lead}=await admin.from("leads").select("id,assigned_to,development_id,purpose,metadata").eq("organization_id",org).eq("id",leadId).single();if(!lead)return null;const[visitsResult,qualificationResult,materialsResult,inventoryResult,simulationsResult]=await Promise.all([admin.from("lead_visits").select("id,broker_id,scheduled_at,status,format,location,preparation_snapshot,preparation_completed_at,outcome_key,objection_keys,next_step_key,result_recorded_at").eq("organization_id",org).eq("lead_id",leadId).order("scheduled_at",{ascending:false}).limit(20),admin.from("lead_qualification_profiles").select("purpose_key,timeline_key,financing_key,budget_readiness_key,region_readiness_key,unit_profile_key,decision_role_key,contact_preference_key,answered_count").eq("organization_id",org).eq("lead_id",leadId).maybeSingle(),lead.development_id?admin.from("project_materials").select("id",{count:"exact",head:true}).eq("organization_id",org).eq("development_id",lead.development_id).eq("is_current",true).eq("review_status","verified"):Promise.resolve({count:0,error:null}),lead.development_id?admin.from("properties").select("id",{count:"exact",head:true}).eq("organization_id",org).eq("development_id",lead.development_id).in("status",["available","ativo","disponivel","disponível"]):Promise.resolve({count:0,error:null}),admin.from("commercial_simulations").select("id",{count:"exact",head:true}).eq("organization_id",org).eq("lead_id",leadId).gt("valid_until",new Date().toISOString())]);
// Falha de leitura (ex.: tabela ausente pelo schema drift) era engolida e o
// contexto voltava zerado como se fosse "sem dados". Comportamento mantido;
// agora cada falha fica visível no log com a tabela de origem.
if(visitsResult.error)logger.warn("lead.visit_assistant.read_failed",{organizationId:org,leadId,table:"lead_visits",error:visitsResult.error.message});
if(qualificationResult.error)logger.warn("lead.visit_assistant.read_failed",{organizationId:org,leadId,table:"lead_qualification_profiles",error:qualificationResult.error.message});
if(materialsResult.error)logger.warn("lead.visit_assistant.read_failed",{organizationId:org,leadId,table:"project_materials",error:materialsResult.error.message});
if(inventoryResult.error)logger.warn("lead.visit_assistant.read_failed",{organizationId:org,leadId,table:"properties",error:inventoryResult.error.message});
if(simulationsResult.error)logger.warn("lead.visit_assistant.read_failed",{organizationId:org,leadId,table:"commercial_simulations",error:simulationsResult.error.message});
const unificada=unificarQualificacao({perfil:qualificationResult.data as Record<string,unknown>|null,respostasLegado:respostasLegadoNoMetadata(lead.metadata),finalidadeDaLead:lead.purpose as string|null,respostasDoFormulario:respostasDoFormularioNoMetadata(lead.metadata)});
// `metadata` e `purpose` entram só para a unificação — o corpo devolvido ao
// navegador continua com os mesmos três campos da lead de antes.
return{lead:{id:lead.id,assigned_to:lead.assigned_to,development_id:lead.development_id},visits:visitsResult.data??[],qualificationProfile:unificada.profile,qualificationOrigens:unificada.origens,qualificationPercent:Math.round(sinaisUnificados(unificada)/8*100),hasCurrentMaterials:Number(materialsResult.count||0)>=2,hasAvailableInventory:Number(inventoryResult.count||0)>0,hasSimulation:Number(simulationsResult.count||0)>0}}
export async function GET(request:NextRequest,{params}:{params:Promise<{id:string}>}){const rate=enforceRateLimit(request,{limit:60,scope:"lead.visit-assistant.read"});if(!rate.ok)return rate.response;const access=await requireAccessContext(request);if(!access.ok)return access.response;const{id}=await params,c=await contextFor(access.access.organization.id,id);if(!c)return apiError("LEAD_NOT_FOUND","Lead fora do escopo.",access.meta,{status:404});const active=c.visits.find(v=>["scheduled","confirmed"].includes(v.status)),checklist=active?buildVisitChecklist({qualificationPercent:c.qualificationPercent,hasCurrentMaterials:c.hasCurrentMaterials,hasAvailableInventory:c.hasAvailableInventory,hasSimulation:c.hasSimulation,format:active.format}):null;return apiSuccess({...c,activeVisit:active||null,checklist,outcomes:VISIT_OUTCOMES,objections:VISIT_OBJECTIONS,nextSteps:VISIT_NEXT_STEPS,canAct:c.lead.assigned_to===access.access.profile.id,policy:{structuredResult:true,noFreeTextRequired:true,noAutomaticProposal:true,noAutomaticMessage:true,humanConfirmation:true,activeMaterialsOnly:true,availableInventoryOnly:true}},access.meta,{headers:rate.headers})}
export async function POST(request:NextRequest,{params}:{params:Promise<{id:string}>}){const rate=enforceRateLimit(request,{limit:20,scope:"lead.visit-assistant.write"});if(!rate.ok)return rate.response;const access=await requireAccessContext(request);if(!access.ok)return access.response;const{id}=await params,body=await request.json().catch(()=>null)as{action?:string;visitId?:string;outcome?:string;objections?:string[];nextStep?:string}|null,c=await contextFor(access.access.organization.id,id);if(!c||c.lead.assigned_to!==access.access.profile.id)return apiError("VISIT_OWNER_ONLY","Somente o corretor responsável pode registrar.",access.meta,{status:403});const admin=getSupabaseAdmin(),visit=c.visits.find(v=>v.id===body?.visitId);if(!visit)return apiError("VISIT_NOT_FOUND","Visita não encontrada.",access.meta,{status:404});if(body?.action==="prepare"){if(!["scheduled","confirmed"].includes(visit.status))return apiError("VISIT_NOT_ACTIVE","A preparação exige visita ativa.",access.meta,{status:409});const checklist=buildVisitChecklist({qualificationPercent:c.qualificationPercent,hasCurrentMaterials:c.hasCurrentMaterials,hasAvailableInventory:c.hasAvailableInventory,hasSimulation:c.hasSimulation,format:visit.format});const{error}=await admin.from("lead_visits").update({preparation_snapshot:checklist,preparation_completed_at:new Date().toISOString()}).eq("id",visit.id).eq("broker_id",access.access.profile.id);if(error)return apiError("VISIT_PREPARE_FAILED","Não foi possível preparar.",access.meta,{status:409});await admin.from("visit_assistance_events").insert({organization_id:access.access.organization.id,lead_id:id,visit_id:visit.id,actor_id:access.access.profile.id,event_type:"prepared"});return apiSuccess({checklist,prepared:true,externalActionExecuted:false},access.meta,{headers:rate.headers})}if(body?.action==="result"){const outcome=String(body.outcome||""),suggested=recommendedPostVisitAction(outcome),nextStep=String(body.nextStep||suggested),objections=Array.isArray(body.objections)?body.objections:[];const{data,error}=await admin.rpc("record_structured_visit_result",{p_actor_id:access.access.profile.id,p_organization_id:access.access.organization.id,p_lead_id:id,p_visit_id:visit.id,p_outcome_key:outcome,p_objection_keys:objections,p_next_step_key:nextStep});if(error)return apiError("VISIT_RESULT_REJECTED","Conclua a visita e selecione um resultado válido.",access.meta,{status:409});structuredApiLog("info","visit.structured_result",request,access.meta,{leadId:id,visitId:visit.id,outcome,nextStep});return apiSuccess({...data,recommendedNextStep:suggested},access.meta,{headers:rate.headers})}return apiError("ACTION_INVALID","Ação inválida.",access.meta,{status:400})}
