"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import { AtlasBadge, AtlasEmpty, AtlasSkeleton } from "@/components/ui/AtlasUI";
import { AtlasCard, AtlasCardHeader, AtlasMetric } from "@/components/ui/AtlasCard";

type Task={id:string;title:string;description:string|null;due_at:string|null;priority:string;status:string;lead_id:string|null;assigned_to:string|null;assigneeName:string;mine:boolean;overdue:boolean;today:boolean;priorityScore:number;lead?:{id:string;name:string|null;purpose:string|null}|null};
type Center={scope:{role:string;actorId:string};summary:{open:number;overdue:number;today:number;high:number;withoutDueDate:number;unassigned:number;mine:number};tasks:Task[];byOwner:Array<{id:string;name:string;open:number;overdue:number;today:number;high:number}>};
type View="priority"|"overdue"|"today"|"mine"|"team"|"no_due";
const dateLabel=(value:string|null)=>value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"Sem prazo";

export default function TasksPage(){
  const[data,setData]=useState<Center|null>(null),[loading,setLoading]=useState(true),[savingId,setSavingId]=useState<string|null>(null),[error,setError]=useState(""),[view,setView]=useState<View>("priority");
  const sessionToken=useCallback(async()=>{const{data:session}=await supabase.auth.getSession();return session.session?.access_token||"";},[]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/v1/tasks",{headers:{Authorization:`Bearer ${await sessionToken()}`},cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error?.message||body.error);setData(body.data||body);}catch{setError("Não foi possível carregar sua operação diária.");}finally{setLoading(false);}},[sessionToken]);
  useEffect(()=>{void load();},[load]);
  async function act(task:Task,action:"complete"|"postpone_one_day"){setSavingId(task.id);setError("");try{const response=await fetch("/api/v1/tasks",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await sessionToken()}`},body:JSON.stringify({id:task.id,action})});const body=await response.json();if(!response.ok)throw new Error(body.error?.message||body.error);await load();}catch{setError(action==="complete"?"Não foi possível concluir a tarefa.":"Não foi possível reagendar a tarefa.");}finally{setSavingId(null);}}
  const visible=useMemo(()=>data?.tasks.filter(task=>view==="overdue"?task.overdue:view==="today"?task.today:view==="mine"?task.mine:view==="team"?!task.mine:view==="no_due"?!task.due_at:true)??[],[data,view]);
  const leadership=Boolean(data&&["admin","director","superintendent","manager"].includes(data.scope.role));
  return <div className="space-y-6 pb-8" data-phase="41-task-center">
    <section><AtlasBadge tone="info">FASE 41 · CENTRAL DE TAREFAS</AtlasBadge><h1 className="mt-4 text-3xl font-semibold tracking-[-.04em] text-white sm:text-4xl">Tarefas e próximos passos</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Uma fila segura para cumprir combinados, recuperar atrasos e manter cada lead avançando.</p></section>
    {error?<div className="rounded-2xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-200">{error}</div>:null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><AtlasMetric label="Pendentes" value={loading?"—":data?.summary.open??0} detail="Ações visíveis" trend="LIVE" tone="blue"/><AtlasMetric label="Vencidas" value={loading?"—":data?.summary.overdue??0} detail="Resolver primeiro" trend="SLA" tone="rose"/><AtlasMetric label="Para hoje" value={loading?"—":data?.summary.today??0} detail="Compromissos do dia" trend="HOJE" tone="amber"/><AtlasMetric label="Alta prioridade" value={loading?"—":data?.summary.high??0} detail="Maior impacto" trend="FOCO" tone="violet"/><AtlasMetric label="Sem prazo" value={loading?"—":data?.summary.withoutDueDate??0} detail="Planejamento incompleto" trend="REVISAR" tone="amber"/><AtlasMetric label="Minha fila" value={loading?"—":data?.summary.mine??0} detail="Sob minha responsabilidade" trend="PESSOAL" tone="green"/></section>
    <div className={`grid gap-5 ${leadership?"xl:grid-cols-[1fr_320px]":""}`}>
      <AtlasCard><AtlasCardHeader eyebrow="Execução diária" title="Fila comercial priorizada" description="Atraso, prazo e prioridade formam uma ordem explicável. As ações são reconfirmadas pela API e pelo RLS." action={<button type="button" onClick={()=>void load()} className="atlas-button-secondary">Atualizar</button>}/><div className="flex gap-2 overflow-x-auto border-t border-white/[.06] p-4 sm:px-6">{([['priority','Prioridade'],['overdue','Vencidas'],['today','Hoje'],['mine','Minha fila'],['team','Equipe visível'],['no_due','Sem prazo']]as const).map(([key,label])=><button key={key} onClick={()=>setView(key)} className={`atlas-kanban-toggle shrink-0 ${view===key?"is-active":""}`}>{label}</button>)}</div><div className="grid gap-3 p-4 sm:p-6 lg:grid-cols-2">{loading?[1,2,3,4].map(item=><AtlasSkeleton key={item} className="h-48"/>):visible.length?visible.map(task=><article key={task.id} className={`rounded-2xl border p-4 ${task.overdue?"border-rose-400/18 bg-rose-400/[.04]":"border-white/[.07] bg-white/[.02]"}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-sm font-semibold text-white">{task.title}</h2><p className="mt-1 truncate text-xs text-slate-500">{task.lead?.name||"Sem lead vinculada"}{task.lead?.purpose?` · ${task.lead.purpose}`:""}</p></div><AtlasBadge tone={task.overdue?"danger":["alta","high","critical"].includes(task.priority)?"warning":"neutral"}>{task.overdue?"VENCIDA":task.priority||"NORMAL"}</AtlasBadge></div><p className="mt-4 text-xs leading-5 text-slate-400">{task.description||"Execute a ação e registre o resultado na timeline da lead."}</p><div className="mt-3 flex items-center justify-between gap-2"><p className={`text-xs font-semibold ${task.overdue?"text-rose-300":"text-sky-300"}`}>{dateLabel(task.due_at)}</p><span className="text-[10px] text-slate-500">{task.assigneeName}</span></div><div className="mt-4 flex flex-wrap gap-2">{task.lead_id?<Link href={`/leads/${task.lead_id}`} className="atlas-button-secondary">Abrir lead</Link>:null}<button type="button" disabled={savingId===task.id} onClick={()=>void act(task,"postpone_one_day")} className="atlas-button-secondary disabled:opacity-50">+1 dia</button><button type="button" disabled={savingId===task.id} onClick={()=>void act(task,"complete")} className="atlas-button-primary disabled:opacity-50">Concluir</button></div></article>):<div className="lg:col-span-2"><AtlasEmpty title="Fila em dia" description="Nenhuma tarefa aberta neste filtro."/></div>}</div></AtlasCard>
      {leadership?<AtlasCard><AtlasCardHeader eyebrow="Equipe visível" title="Carga por responsável" description="Consolidado operacional, não ranking de pessoas."/><div className="space-y-2 p-5">{data?.byOwner.map(owner=><div key={owner.id} className="rounded-xl border border-white/[.06] p-3"><div className="flex items-center justify-between gap-2"><strong className="text-xs text-white">{owner.name}</strong><span className={owner.overdue?"text-xs font-bold text-rose-200":"text-xs font-bold text-emerald-200"}>{owner.overdue} vencidas</span></div><p className="mt-1 text-[10px] text-slate-500">{owner.open} abertas · {owner.today} hoje · {owner.high} prioritárias</p></div>)}{!data?.byOwner.length?<AtlasEmpty title="Sem tarefas visíveis" description="A equipe ainda não possui ações abertas."/>:null}<p className="pt-2 text-[10px] leading-4 text-slate-600">A central não atribui tarefas automaticamente e não usa volume isolado para avaliar desempenho.</p></div></AtlasCard>:null}
    </div>
  </div>;
}
