import{type NextRequest}from"next/server";import{apiError,apiSuccess,structuredApiLog}from"@/lib/api/core";import{enforceRateLimit,requireAccessContext}from"@/lib/api/security";import{getSupabaseAdmin}from"@/lib/supabase/admin";import{options,qualificationProgress}from"@/lib/ai/conversational-qualification";import{respostasDoFormularioNoMetadata,respostasLegadoNoMetadata,unificarQualificacao}from"@/lib/crm/qualificacao-canonica";
/**
 * ── A TELA PERGUNTAVA O QUE A PESSOA JÁ TINHA RESPONDIDO ────────────────────
 *
 * Esta rota lia SÓ `lead_qualification_profiles`. Medido na base viva em
 * 02/08/2026: 487 de 490 leads abriam em "0 de 8 sinais", e 181 delas já tinham
 * `leads.purpose` gravado — a primeira pergunta que o corretor fazia era
 * exatamente a que a pessoa respondeu no anúncio.
 *
 * A gaveta canônica continua sendo o perfil (é onde a transação de
 * `record_structured_qualification` grava, e onde `leads.purpose` é o efeito
 * colateral). O que mudou é que as outras fontes agora PREENCHEM as lacunas em
 * vez de desaparecer — `lib/crm/qualificacao-canonica.ts` documenta a
 * precedência e devolve a origem de cada sinal, para a tela nunca confundir
 * "o corretor confirmou" com "veio do anúncio".
 *
 * `noAutomaticInference` continua verdadeiro: nada aqui é deduzido. Toda fonte
 * é uma resposta que a pessoa deu, traduzida 1-para-1 por uma régua testada;
 * valor sem equivalente honesto simplesmente não credita sinal.
 */
export async function GET(request:NextRequest,{params}:{params:Promise<{id:string}>}){const rate=enforceRateLimit(request,{limit:60,scope:"lead.qualification.read"});if(!rate.ok)return rate.response;const access=await requireAccessContext(request);if(!access.ok)return access.response;const{id}=await params,{data:lead}=await access.supabase.from("leads").select("id,name,assigned_to,purpose,metadata").eq("id",id).maybeSingle();if(!lead)return apiError("LEAD_NOT_FOUND","Lead fora do seu escopo.",access.meta,{status:404});const[{data,error},{data:events}]=await Promise.all([access.supabase.from("lead_qualification_profiles").select("version,purpose_key,timeline_key,financing_key,budget_readiness_key,region_readiness_key,unit_profile_key,decision_role_key,contact_preference_key,answered_count,completed_at,updated_at").eq("lead_id",id).maybeSingle(),access.supabase.from("lead_qualification_events").select("id,changed_fields,source,created_at").eq("lead_id",id).order("created_at",{ascending:false}).limit(30)]);if(error)return apiError("QUALIFICATION_UNAVAILABLE","Aplique a migration da Fase 86.",access.meta,{status:503});const unificada=unificarQualificacao({perfil:data as Record<string,unknown>|null,respostasLegado:respostasLegadoNoMetadata(lead.metadata),finalidadeDaLead:lead.purpose as string|null,respostasDoFormulario:respostasDoFormularioNoMetadata(lead.metadata)}),profile=unificada.profile;return apiSuccess({lead:{id:lead.id,name:lead.name},profile,origens:unificada.origens,divergencias:unificada.divergencias,declarado:unificada.declarado,progress:qualificationProgress(profile),events:events??[],options,canAnswer:lead.assigned_to===access.access.profile.id,policy:{structuredOnly:true,oneQuestionAtATime:true,brokerConfirmation:true,rawConversationStored:false,noAutomaticInference:true,exclusiveLead:true,exclusiveBroker:true}},access.meta,{headers:rate.headers})}
export async function POST(request:NextRequest,{params}:{params:Promise<{id:string}>}){const rate=enforceRateLimit(request,{limit:30,scope:"lead.qualification.answer"});if(!rate.ok)return rate.response;const access=await requireAccessContext(request);if(!access.ok)return access.response;const{id}=await params,body=await request.json().catch(()=>null)as{field?:string;value?:string}|null,field=String(body?.field||""),value=String(body?.value||"");if(!(field in options)||!options[field as keyof typeof options].includes(value))return apiError("QUALIFICATION_INVALID","Selecione uma resposta comercial válida.",access.meta,{status:400});const{data,error}=await getSupabaseAdmin().rpc("record_structured_qualification",{p_actor_id:access.access.profile.id,p_organization_id:access.access.organization.id,p_lead_id:id,p_field:field,p_value:value});if(error)return apiError("QUALIFICATION_REJECTED","Somente o corretor responsável pode confirmar esta resposta.",access.meta,{status:403});structuredApiLog("info","lead.structured_qualification_recorded",request,access.meta,{leadId:id,field});return apiSuccess(data,access.meta,{status:201,headers:rate.headers})}
