import { defineAtlasPageContract, type AtlasPageContract } from "./page-contract";

const allRoles = {
  director: "organization",
  superintendent: "management-tree",
  manager: "team",
  broker: "own-portfolio",
} as const;

const commercialAccess = ["admin", "director_decisor", "director", "broker"] as const;

const managementRoles = {
  director: "organization",
  superintendent: "management-tree",
  manager: "team",
  broker: "hidden",
} as const;

const administrationRoles = {
  director: "organization",
  superintendent: "hidden",
  manager: "hidden",
  broker: "hidden",
} as const;

type SupportingPageContractInput = {
  id: string;
  route: `/${string}`;
  businessOutcome: string;
  primaryAction: AtlasPageContract["primaryAction"];
  metric: AtlasPageContract["decisionMetrics"][number];
  queueTitle: string;
  queueOrdering: readonly string[];
  roleScopes?: AtlasPageContract["roleScopes"];
  allowedAccessRoles?: AtlasPageContract["allowedAccessRoles"];
  dataDomains: readonly string[];
  copilotContext: string;
  copilotCapabilities: readonly string[];
  interactiveIslands: readonly string[];
};

function defineSupportingPageContract(input: SupportingPageContractInput) {
  return defineAtlasPageContract({
    id: input.id,
    route: input.route,
    businessOutcome: input.businessOutcome,
    primaryAction: input.primaryAction,
    decisionMetrics: [input.metric],
    depths: ["glance", "workspace", "context"],
    priorityQueue: { title: input.queueTitle, ordering: input.queueOrdering },
    roleScopes: input.roleScopes ?? allRoles,
    allowedAccessRoles: input.allowedAccessRoles ?? commercialAccess,
    dataDependencies: input.dataDomains.map((domain) => ({
      domain,
      query: `${input.id}-${domain}-workspace`,
      tenantScoped: true as const,
      fallback: "partial-state" as const,
    })),
    copilot: {
      contextId: input.copilotContext,
      capabilities: input.copilotCapabilities,
      maximumAutonomy: 2,
    },
    rendering: { strategy: "server-first", interactiveIslands: input.interactiveIslands },
  });
}

export const atlasCoreV2PageRegistry = [
  defineAtlasPageContract({
    id: "command-center",
    route: "/dashboard",
    businessOutcome: "Mostrar a prioridade comercial que exige decisão ou execução agora.",
    primaryAction: { id: "open-priority", label: "Abrir prioridade", href: "/pipeline", outcome: "Avançar a oportunidade mais relevante." },
    decisionMetrics: [
      { id: "new-leads", label: "Novos leads", decisionQuestion: "A entrada está sendo atendida?" },
      { id: "overdue-actions", label: "Ações vencidas", decisionQuestion: "Onde existe risco de perda?" },
      { id: "hot-opportunities", label: "Oportunidades quentes", decisionQuestion: "Quais negócios exigem contato?" },
      { id: "pipeline-value", label: "Pipeline", decisionQuestion: "Quanto valor está em movimento?" },
      { id: "conversion", label: "Conversão", decisionQuestion: "A operação está melhorando?" },
    ],
    depths: ["glance", "workspace", "context"],
    priorityQueue: { title: "O que precisa acontecer agora", ordering: ["sla-risk", "buying-intent", "commercial-value", "last-interaction"] },
    roleScopes: allRoles,
    allowedAccessRoles: commercialAccess,
    dataDependencies: [
      { domain: "leads", query: "command-center-lead-health", tenantScoped: true, fallback: "partial-state" },
      { domain: "tasks", query: "command-center-action-health", tenantScoped: true, fallback: "partial-state" },
      { domain: "opportunities", query: "command-center-pipeline-health", tenantScoped: true, fallback: "partial-state" },
    ],
    copilot: { contextId: "command-center-decision", capabilities: ["explain-priority", "prepare-daily-briefing"], maximumAutonomy: 2 },
    rendering: { strategy: "server-first", interactiveIslands: ["period-filter", "priority-queue", "copilot-drawer"] },
  }),
  defineAtlasPageContract({
    id: "leads",
    route: "/leads",
    businessOutcome: "Encontrar e atender rapidamente o lead com maior necessidade de ação.",
    primaryAction: { id: "create-lead", label: "Novo lead", href: "/leads/new", outcome: "Registrar uma nova oportunidade sem duplicidade." },
    decisionMetrics: [
      { id: "visible-leads", label: "Leads visíveis", decisionQuestion: "Qual é o tamanho da carteira acessível?" },
      { id: "hot-leads", label: "Quentes", decisionQuestion: "Quem deve receber contato primeiro?" },
      { id: "unassigned", label: "Sem responsável", decisionQuestion: "O que ainda precisa de distribuição?" },
      { id: "without-next-action", label: "Sem próxima ação", decisionQuestion: "Quem corre risco de esquecimento?" },
    ],
    depths: ["glance", "workspace", "context"],
    priorityQueue: { title: "Minha rotina", ordering: ["overdue-next-action", "temperature", "score", "created-at"] },
    roleScopes: allRoles,
    allowedAccessRoles: commercialAccess,
    dataDependencies: [{ domain: "leads", query: "search-commercial-leads", tenantScoped: true, fallback: "empty-state" }],
    copilot: { contextId: "lead-prioritization", capabilities: ["explain-score", "suggest-next-action", "prepare-message"], maximumAutonomy: 2 },
    rendering: { strategy: "server-first", interactiveIslands: ["lead-search", "lead-filters", "bulk-selection", "lead-drawer"] },
  }),
  defineAtlasPageContract({
    id: "pipeline",
    route: "/pipeline",
    businessOutcome: "Avançar oportunidades com segurança e tornar todo bloqueio comercial visível.",
    primaryAction: { id: "open-top-opportunity", label: "Abrir melhor oportunidade", href: "/pipeline?focus=priority", outcome: "Executar a próxima ação do negócio prioritário." },
    decisionMetrics: [
      { id: "open-opportunities", label: "Em aberto", decisionQuestion: "Quantos negócios exigem trabalho?" },
      { id: "overdue-sla", label: "SLA vencido", decisionQuestion: "Quais negócios estão em risco?" },
      { id: "weighted-value", label: "Forecast", decisionQuestion: "Qual valor possui evidência de avanço?" },
      { id: "won", label: "Ganhos", decisionQuestion: "Quanto foi convertido no período?" },
    ],
    depths: ["glance", "workspace", "context"],
    priorityQueue: { title: "Fila inteligente", ordering: ["sla-risk", "stage-age", "next-action", "score"] },
    roleScopes: allRoles,
    allowedAccessRoles: commercialAccess,
    dataDependencies: [{ domain: "opportunities", query: "pipeline-board", tenantScoped: true, fallback: "empty-state" }],
    copilot: { contextId: "pipeline-coach", capabilities: ["explain-risk", "suggest-stage-action", "prepare-follow-up"], maximumAutonomy: 2 },
    rendering: { strategy: "server-first", interactiveIslands: ["kanban-board", "stage-movement", "opportunity-drawer"] },
  }),
  defineAtlasPageContract({
    id: "customers-360",
    route: "/customers",
    businessOutcome: "Reunir a história do comprador e indicar a melhor continuidade do relacionamento.",
    primaryAction: { id: "open-customer", label: "Abrir cliente prioritário", href: "/customers?focus=priority", outcome: "Continuar o relacionamento com contexto completo." },
    decisionMetrics: [
      { id: "visible-customers", label: "Clientes", decisionQuestion: "Quantos relacionamentos estão no escopo?" },
      { id: "contactable", label: "Com contato", decisionQuestion: "Quantos podem ser atendidos?" },
      { id: "qualified", label: "Qualificados", decisionQuestion: "Quem possui perfil conhecido?" },
      { id: "negotiating", label: "Em negociação", decisionQuestion: "Quem já está próximo de uma decisão?" },
    ],
    depths: ["glance", "workspace", "context"],
    priorityQueue: { title: "Relacionamentos prioritários", ordering: ["next-action", "intent", "recent-activity", "data-completeness"] },
    roleScopes: allRoles,
    allowedAccessRoles: commercialAccess,
    dataDependencies: [{ domain: "customers", query: "customer-360-list", tenantScoped: true, fallback: "empty-state" }],
    copilot: { contextId: "customer-relationship", capabilities: ["summarize-history", "identify-data-gap", "recommend-project"], maximumAutonomy: 2 },
    rendering: { strategy: "server-first", interactiveIslands: ["customer-search", "customer-list", "customer-context-panel"] },
  }),
  defineAtlasPageContract({
    id: "tasks-and-agenda",
    route: "/tasks",
    businessOutcome: "Transformar toda oportunidade em uma próxima ação clara, com prazo e responsável.",
    primaryAction: { id: "create-task", label: "Nova tarefa", href: "/tasks?create=1", outcome: "Agendar uma próxima ação rastreável." },
    decisionMetrics: [
      { id: "today", label: "Hoje", decisionQuestion: "O que deve ser executado agora?" },
      { id: "overdue", label: "Atrasadas", decisionQuestion: "O que ameaça o SLA?" },
      { id: "visits", label: "Visitas", decisionQuestion: "Quais compromissos exigem preparação?" },
      { id: "completed", label: "Concluídas", decisionQuestion: "O plano diário está avançando?" },
    ],
    depths: ["glance", "workspace", "context"],
    priorityQueue: { title: "Próximas ações", ordering: ["overdue", "due-at", "lead-priority", "created-at"] },
    roleScopes: allRoles,
    allowedAccessRoles: commercialAccess,
    dataDependencies: [{ domain: "tasks", query: "commercial-action-queue", tenantScoped: true, fallback: "empty-state" }],
    copilot: { contextId: "daily-action-plan", capabilities: ["organize-day", "prepare-visit", "suggest-follow-up"], maximumAutonomy: 2 },
    rendering: { strategy: "server-first", interactiveIslands: ["task-filters", "task-completion", "task-editor"] },
  }),
  defineAtlasPageContract({
    id: "developments",
    route: "/developments",
    businessOutcome: "Encontrar rapidamente o projeto, estoque e material adequados para cada comprador.",
    primaryAction: { id: "search-materials", label: "Buscar materiais", href: "/developments/materials", outcome: "Entregar o conteúdo comercial correto ao cliente." },
    decisionMetrics: [
      { id: "active-projects", label: "Projetos ativos", decisionQuestion: "Quantos produtos estão disponíveis?" },
      { id: "available-units", label: "Unidades", decisionQuestion: "Qual estoque pode ser ofertado?" },
      { id: "portfolio-vgv", label: "VGV", decisionQuestion: "Qual valor existe no portfólio?" },
      { id: "stale-materials", label: "Materiais vencidos", decisionQuestion: "O que precisa de atualização?" },
    ],
    depths: ["glance", "workspace", "context"],
    priorityQueue: { title: "Portfólio em ação", ordering: ["buyer-match", "inventory-availability", "material-freshness", "sales-velocity"] },
    roleScopes: allRoles,
    allowedAccessRoles: commercialAccess,
    dataDependencies: [
      { domain: "developments", query: "commercial-development-catalog", tenantScoped: true, fallback: "empty-state" },
      { domain: "materials", query: "current-project-materials", tenantScoped: true, fallback: "partial-state" },
    ],
    copilot: { contextId: "project-match", capabilities: ["recommend-project", "explain-payment-flow", "find-current-material"], maximumAutonomy: 2 },
    rendering: { strategy: "server-first", interactiveIslands: ["project-search", "portfolio-filters", "project-drawer"] },
  }),
  defineSupportingPageContract({
    id: "calendar",
    route: "/calendar",
    businessOutcome: "Organizar compromissos e proteger os horários que movem oportunidades.",
    primaryAction: { id: "create-appointment", label: "Novo compromisso", href: "/calendar?create=1", outcome: "Reservar uma ação com cliente ou equipe." },
    metric: { id: "today-appointments", label: "Hoje", decisionQuestion: "Quais compromissos exigem preparação?" },
    queueTitle: "Agenda comercial",
    queueOrdering: ["start-at", "commercial-priority", "travel-time"],
    dataDomains: ["tasks", "visits", "commercial-events"],
    copilotContext: "calendar-preparation",
    copilotCapabilities: ["organize-day", "prepare-meeting", "detect-conflict"],
    interactiveIslands: ["calendar-view", "appointment-editor", "period-selector"],
  }),
  defineSupportingPageContract({
    id: "activity",
    route: "/activity",
    businessOutcome: "Explicar o que aconteceu com cada oportunidade e preservar continuidade.",
    primaryAction: { id: "open-recent-activity", label: "Ver atividade recente", href: "/activity?period=today", outcome: "Revisar a movimentação comercial mais recente." },
    metric: { id: "recent-events", label: "Eventos recentes", decisionQuestion: "O histórico comercial está atualizado?" },
    queueTitle: "Linha do tempo",
    queueOrdering: ["occurred-at", "commercial-impact", "actor"],
    dataDomains: ["commercial-events", "lead-activities"],
    copilotContext: "activity-explanation",
    copilotCapabilities: ["summarize-timeline", "identify-missing-update"],
    interactiveIslands: ["activity-filters", "timeline-details"],
  }),
  defineSupportingPageContract({
    id: "reactivation",
    route: "/leads/import",
    businessOutcome: "Recuperar oportunidades antigas sem poluir a carteira operacional.",
    primaryAction: { id: "open-eligible-queue", label: "Abrir fila elegível", href: "/leads/import?view=eligible", outcome: "Priorizar contatos válidos e autorizados." },
    metric: { id: "eligible-leads", label: "Elegíveis", decisionQuestion: "Quantos contatos podem receber uma abordagem segura?" },
    queueTitle: "Fila de reativação",
    queueOrdering: ["eligibility", "buyer-signal", "data-quality", "last-contact"],
    dataDomains: ["reactivation-leads", "suppression-list", "lead-memory"],
    copilotContext: "reactivation-supervision",
    copilotCapabilities: ["explain-eligibility", "prepare-reactivation-message"],
    interactiveIslands: ["reactivation-filters", "eligibility-review", "bulk-selection"],
  }),
  defineSupportingPageContract({
    id: "copilot",
    route: "/ai-dashboard",
    businessOutcome: "Traduzir dados comerciais em uma próxima ação explicável e supervisionada.",
    primaryAction: { id: "prepare-daily-briefing", label: "Preparar meu dia", href: "/ai-dashboard?briefing=daily", outcome: "Receber um plano baseado no escopo do usuário." },
    metric: { id: "actionable-signals", label: "Sinais acionáveis", decisionQuestion: "Quais recomendações possuem evidência suficiente?" },
    queueTitle: "Sugestões supervisionadas",
    queueOrdering: ["evidence", "urgency", "commercial-impact", "confidence"],
    dataDomains: ["leads", "tasks", "opportunities", "ai-memory"],
    copilotContext: "commercial-copilot",
    copilotCapabilities: ["prepare-daily-briefing", "suggest-next-action", "explain-evidence"],
    interactiveIslands: ["copilot-thread", "suggestion-review", "context-selector"],
  }),
  defineSupportingPageContract({
    id: "brokers",
    route: "/brokers",
    businessOutcome: "Mostrar capacidade, carteira e gargalos da estrutura comercial visível.",
    primaryAction: { id: "open-team-performance", label: "Ver desempenho", href: "/brokers?view=performance", outcome: "Direcionar apoio ao time que mais precisa." },
    metric: { id: "visible-team", label: "Pessoas visíveis", decisionQuestion: "Quem está disponível e dentro do meu escopo?" },
    queueTitle: "Equipe que exige atenção",
    queueOrdering: ["overdue-actions", "portfolio-load", "response-time", "conversion"],
    roleScopes: managementRoles,
    dataDomains: ["profiles", "team-hierarchy", "lead-assignments"],
    copilotContext: "team-coaching",
    copilotCapabilities: ["identify-bottleneck", "prepare-coaching-brief"],
    interactiveIslands: ["team-filters", "broker-context-panel"],
  }),
  defineSupportingPageContract({
    id: "distribution",
    route: "/distribution",
    businessOutcome: "Colocar cada lead em um único responsável compatível com projeto e capacidade.",
    primaryAction: { id: "open-unassigned-queue", label: "Abrir fila sem responsável", href: "/distribution?queue=unassigned", outcome: "Distribuir oportunidades sem atendimento." },
    metric: { id: "unassigned-leads", label: "Sem responsável", decisionQuestion: "Quantos leads ainda aguardam distribuição?" },
    queueTitle: "Fila de distribuição",
    queueOrdering: ["waiting-time", "project-affinity", "broker-capacity", "availability"],
    roleScopes: managementRoles,
    dataDomains: ["leads", "profiles", "distribution-rules"],
    copilotContext: "distribution-assistance",
    copilotCapabilities: ["explain-recommendation", "detect-overload"],
    interactiveIslands: ["distribution-queue", "broker-availability", "bulk-transfer"],
  }),
  defineSupportingPageContract({
    id: "sales",
    route: "/sales",
    businessOutcome: "Tornar valor, probabilidade, prazo e risco das negociações comparáveis.",
    primaryAction: { id: "open-forecast", label: "Abrir forecast", href: "/sales?view=forecast", outcome: "Revisar negócios com impacto provável na receita." },
    metric: { id: "weighted-forecast", label: "Forecast ponderado", decisionQuestion: "Qual receita possui evidência de fechamento?" },
    queueTitle: "Negócios que exigem atenção",
    queueOrdering: ["closing-risk", "expected-close", "commercial-value", "probability"],
    roleScopes: managementRoles,
    dataDomains: ["opportunities", "sales", "commission-receivables"],
    copilotContext: "sales-forecast",
    copilotCapabilities: ["explain-forecast", "identify-closing-risk"],
    interactiveIslands: ["forecast-filters", "opportunity-table", "sales-drawer"],
  }),
  defineSupportingPageContract({
    id: "reports",
    route: "/reports",
    businessOutcome: "Explicar resultado comercial e apoiar decisões diárias, semanais e mensais.",
    primaryAction: { id: "open-recommended-action", label: "Abrir ação recomendada", href: "/decision-center", outcome: "Converter um indicador em decisão rastreável." },
    metric: { id: "conversion", label: "Conversão", decisionQuestion: "Onde o funil melhora ou perde eficiência?" },
    queueTitle: "Decisões do período",
    queueOrdering: ["business-impact", "evidence-strength", "trend", "urgency"],
    roleScopes: managementRoles,
    dataDomains: ["analytics", "opportunities", "campaign-performance"],
    copilotContext: "executive-reporting",
    copilotCapabilities: ["explain-trend", "compare-period", "recommend-decision"],
    interactiveIslands: ["period-selector", "report-filters", "decision-drilldown"],
  }),
  defineSupportingPageContract({
    id: "revenue-engine",
    route: "/revenue-engine",
    businessOutcome: "Conectar aquisição, atendimento e resultado para melhorar a qualidade do público.",
    primaryAction: { id: "review-conversions", label: "Revisar conversões", href: "/revenue-engine?view=conversions", outcome: "Identificar campanhas que geram compradores reais." },
    metric: { id: "qualified-conversions", label: "Conversões qualificadas", decisionQuestion: "Quais origens geram avanço comercial real?" },
    queueTitle: "Otimizações de receita",
    queueOrdering: ["revenue-impact", "signal-quality", "campaign-cost", "learning-value"],
    roleScopes: managementRoles,
    dataDomains: ["campaigns", "conversion-events", "opportunities"],
    copilotContext: "revenue-optimization",
    copilotCapabilities: ["explain-campaign-quality", "recommend-signal-improvement"],
    interactiveIslands: ["campaign-filters", "conversion-funnel", "optimization-review"],
  }),
  defineSupportingPageContract({
    id: "users",
    route: "/users",
    businessOutcome: "Governar acesso, papel, vínculo organizacional e continuidade do histórico.",
    primaryAction: { id: "create-user", label: "Novo usuário", href: "/users?create=1", outcome: "Adicionar uma pessoa com acesso e escopo corretos." },
    metric: { id: "active-users", label: "Usuários ativos", decisionQuestion: "Quem possui acesso vigente à organização?" },
    queueTitle: "Acessos que exigem revisão",
    queueOrdering: ["missing-membership", "inactive-account", "role-risk", "last-access"],
    roleScopes: administrationRoles,
    allowedAccessRoles: ["admin"],
    dataDomains: ["profiles", "memberships", "roles"],
    copilotContext: "access-governance",
    copilotCapabilities: ["explain-role-scope", "identify-access-risk"],
    interactiveIslands: ["user-table", "user-editor", "role-review"],
  }),
  defineSupportingPageContract({
    id: "external-sales",
    route: "/external-sales",
    businessOutcome: "Preservar aprendizado de compradores externos sem distorcer receita própria.",
    primaryAction: { id: "register-external-purchase", label: "Registrar compra externa", href: "/external-sales?create=1", outcome: "Classificar a perda comercial com contexto." },
    metric: { id: "external-purchases", label: "Compras externas", decisionQuestion: "Quais padrões explicam negócios perdidos?" },
    queueTitle: "Aprendizados externos",
    queueOrdering: ["learning-value", "commercial-reason", "buyer-profile", "registered-at"],
    roleScopes: administrationRoles,
    allowedAccessRoles: ["admin", "director_decisor"],
    dataDomains: ["leads", "external-purchases", "commercial-memory"],
    copilotContext: "external-buyer-learning",
    copilotCapabilities: ["summarize-loss-reason", "identify-buyer-pattern"],
    interactiveIslands: ["external-sale-form", "learning-table"],
  }),
  defineSupportingPageContract({
    id: "integrations",
    route: "/integrations",
    businessOutcome: "Mostrar quais conexões possuem credencial, teste real e operação comprovada.",
    primaryAction: { id: "open-integration-health", label: "Ver saúde", href: "/integrations/health", outcome: "Identificar conexões sem evidência operacional." },
    metric: { id: "operational-integrations", label: "Operacionais", decisionQuestion: "Quais integrações passaram por teste real?" },
    queueTitle: "Conexões que exigem atenção",
    queueOrdering: ["failed-test", "missing-credential", "delivery-error", "last-verified"],
    roleScopes: administrationRoles,
    allowedAccessRoles: ["admin", "director_decisor"],
    dataDomains: ["integration-catalog", "integration-health", "delivery-events"],
    copilotContext: "integration-health",
    copilotCapabilities: ["explain-status", "recommend-safe-next-step"],
    interactiveIslands: ["integration-catalog", "health-details", "test-connection"],
  }),
  defineSupportingPageContract({
    id: "settings",
    route: "/settings",
    businessOutcome: "Centralizar configurações governadas da organização, IA e operação.",
    primaryAction: { id: "review-environment", label: "Revisar ambiente", href: "/settings?view=environment", outcome: "Confirmar parâmetros críticos da operação." },
    metric: { id: "configuration-health", label: "Saúde da configuração", decisionQuestion: "Existe algum parâmetro crítico incompleto?" },
    queueTitle: "Configurações pendentes",
    queueOrdering: ["security-impact", "operational-impact", "missing-value", "last-updated"],
    roleScopes: administrationRoles,
    allowedAccessRoles: ["admin"],
    dataDomains: ["organization-settings", "ai-governance", "security-policy"],
    copilotContext: "configuration-governance",
    copilotCapabilities: ["explain-setting", "identify-configuration-risk"],
    interactiveIslands: ["settings-navigation", "configuration-editor"],
  }),
] as const satisfies readonly AtlasPageContract[];

export function getAtlasCoreV2PageContract(route: string) {
  return atlasCoreV2PageRegistry.find((contract) => contract.route === route) ?? null;
}
