import{type NextRequest}from"next/server";import{apiError,apiSuccess}from"@/lib/api/core";import{enforceRateLimit,requireAccessContext}from"@/lib/api/security";import{aiProviderReadiness,aiPricingReadiness,aiRoutingDiagnostics}from"@/lib/ai/provider-router";import{planCommercialAI,type OrchestratedTask}from"@/lib/ai/commercial-orchestrator";import{fetchAllRows}from"@/lib/supabase/fetch-all-rows";const management=(r:string|null,role:string)=>['director','superintendent'].includes(r||'')||role==='admin';
type OrchestrationRow={requested_task:string;resolved_task:string;data_class:string;risk_level:string;provider_order:string[];selected_provider:string|null;selected_model:string|null;token_budget:number;routing_reasons:string[];human_review_required:boolean;fallback_used:boolean;status:string;latency_ms:number|null;total_tokens:number|null;estimated_cost_usd:number|null;created_at:string};
export async function GET(request:NextRequest){const rate=enforceRateLimit(request,{limit:30,scope:'ai.orchestration.read'});if(!rate.ok)return rate.response;const access=await requireAccessContext(request);if(!access.ok)return access.response;if(!management(access.access.profile.commercialRole,access.access.profile.role))return apiError('FORBIDDEN','Orquestração disponível para diretoria e superintendência.',access.meta,{status:403});const readiness=aiProviderReadiness(),pricing=aiPricingReadiness(),since=new Date(Date.now()-30*86400000).toISOString(),
// .limit(1000) cortava a janela de 30 dias em silêncio: acima disso o custo e a
// taxa de fallback saíam menores que a realidade sem nenhum aviso. Ordem estável
// (created_at + id) porque paginar por range sem ordem determinística repete e
// pula linhas entre páginas.
{rows,error,truncated}=await fetchAllRows<OrchestrationRow>((from,to)=>access.supabase.from('ai_orchestration_decisions').select('requested_task,resolved_task,data_class,risk_level,provider_order,selected_provider,selected_model,token_budget,routing_reasons,human_review_required,fallback_used,status,latency_ms,total_tokens,estimated_cost_usd,created_at,id').gte('created_at',since).order('created_at',{ascending:false}).order('id',{ascending:false}).range(from,to));if(error)return apiError('AI_ORCHESTRATION_UNAVAILABLE','Aplique a migration da Fase 81.',access.meta,{status:503});
// Custo só soma linhas COM tarifa: linha sem tarifa tem custo desconhecido, não zero.
const priced=rows.filter(item=>item.estimated_cost_usd!==null&&item.estimated_cost_usd!==undefined),cost=priced.reduce((sum,item)=>sum+Number(item.estimated_cost_usd||0),0);return apiSuccess({readiness,pricing,routingDiagnostics:aiRoutingDiagnostics(),decisions:rows.slice(0,50),summary:{calls:rows.length,truncated,fallbacks:rows.filter(item=>item.fallback_used).length,personalDataCalls:rows.filter(item=>item.data_class==='personal').length,humanReview:rows.filter(item=>item.human_review_required).length,totalTokens:rows.reduce((sum,item)=>sum+Number(item.total_tokens||0),0),pricedCalls:priced.length,unpricedCalls:rows.length-priced.length,costMeasurementComplete:rows.length>0&&priced.length===rows.length&&!truncated,estimatedCostUsd:priced.length?Math.round(cost*1e6)/1e6:null},policy:{singleOrchestrator:true,personalDataTrustedProviderOnly:true,researchRequiresSources:true,costAware:true,tokenBudgeted:true,humanReviewEscalation:true,externalActionAllowed:false,deterministicFallback:true,host:'hostinger'}},access.meta,{headers:{...rate.headers,'Cache-Control':'no-store'}})}
export async function POST(request:NextRequest){const rate=enforceRateLimit(request,{limit:30,scope:'ai.orchestration.preview'});if(!rate.ok)return rate.response;const access=await requireAccessContext(request);if(!access.ok)return access.response;if(!management(access.access.profile.commercialRole,access.access.profile.role))return apiError('FORBIDDEN','Simulação reservada à gestão.',access.meta,{status:403});const body=await request.json().catch(()=>null)as{task?:string;containsPersonalData?:boolean;feature?:string}|null,task=String(body?.task||'');if(!['fast','commercial','reasoning','research'].includes(task))return apiError('TASK_INVALID','Escolha uma tarefa válida.',access.meta,{status:400});const plan=planCommercialAI({task:task as OrchestratedTask,containsPersonalData:Boolean(body?.containsPersonalData),feature:String(body?.feature||'orchestration-preview').slice(0,100),available:aiProviderReadiness()});return apiSuccess({plan,simulationOnly:true,providerCalled:false,promptStored:false},access.meta,{headers:rate.headers})}
