begin;
alter table public.project_intelligence_profiles add column if not exists evidence_summary jsonb not null default '{}'::jsonb,add column if not exists readiness_calculated_at timestamptz,add column if not exists publication_note text;
create table if not exists public.project_intelligence_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,development_id uuid not null references public.developments(id) on delete cascade,actor_id uuid not null references public.profiles(id),event_type text not null check(event_type in('refreshed','approved','publication_revoked')),readiness_percent integer not null check(readiness_percent between 0 and 100),note text not null check(char_length(note) between 5 and 500),evidence_summary jsonb not null,created_at timestamptz not null default now());
alter table public.project_intelligence_events enable row level security;drop policy if exists project_intelligence_events_scope on public.project_intelligence_events;create policy project_intelligence_events_scope on public.project_intelligence_events for select to authenticated using(organization_id=(select public.current_organization_id()));revoke all on public.project_intelligence_events from anon;revoke insert,update,delete on public.project_intelligence_events from authenticated;grant select on public.project_intelligence_events to authenticated;
create or replace function public.refresh_project_intelligence_dossier(p_actor_id uuid,p_organization_id uuid,p_development_id uuid,p_note text default 'Prontidão recalculada com fontes canônicas')returns jsonb language plpgsql security definer set search_path='' as $$
declare d public.developments;profile public.project_intelligence_profiles;location_ready boolean;verified_features integer;typologies integer;verified_materials integer;source_count integer;score integer:=0;missing jsonb:='[]'::jsonb;evidence jsonb;
begin select * into d from public.developments where id=p_development_id and organization_id=p_organization_id;if d.id is null then raise exception 'dossier_development_invalid';end if;insert into public.project_intelligence_profiles(organization_id,development_id)values(p_organization_id,p_development_id)on conflict do nothing;select * into profile from public.project_intelligence_profiles where organization_id=p_organization_id and development_id=p_development_id for update;
location_ready:=coalesce(d.city,'')<>'' and coalesce(d.state,'')<>'' and coalesce(d.neighborhood,'')<>'';if location_ready then score:=score+20;else missing:=missing||jsonb_build_array('localização completa');end if;
select count(*) into typologies from public.development_typologies where organization_id=p_organization_id and development_id=p_development_id and status='active';if typologies>0 then score:=score+15;else missing:=missing||jsonb_build_array('tipologias estruturadas');end if;
select count(*) into verified_features from public.development_features where organization_id=p_organization_id and development_id=p_development_id and status='active' and verified=true and source_reference is not null;if verified_features>=3 then score:=score+20;else missing:=missing||jsonb_build_array('3 diferenciais com fonte');end if;
select count(distinct material_type) into verified_materials from public.project_materials where organization_id=p_organization_id and development_id=p_development_id and is_current=true and material_type in('book','price_table','sales_mirror') and review_status='verified' and(coalesce(valid_from,current_date)<=current_date and coalesce(valid_until,current_date)>=current_date);if verified_materials=3 then score:=score+30;else missing:=missing||jsonb_build_array('book, tabela e espelho vigentes e validados');end if;
source_count:=jsonb_array_length(coalesce(profile.source_register,'[]'::jsonb));if source_count>=2 then score:=score+15;else missing:=missing||jsonb_build_array('2 fontes regionais identificadas');end if;
evidence:=jsonb_build_object('locationComplete',location_ready,'activeTypologies',typologies,'verifiedFeatures',verified_features,'verifiedEssentialMaterials',verified_materials,'regionalSources',source_count,'personalDataUsed',false,'generatedClaims',false);
update public.project_intelligence_profiles set readiness_percent=score,missing_information=missing,evidence_summary=evidence,readiness_calculated_at=now(),onboarding_status=case when score=100 then'review_pending'else'study_pending'end,ai_context=coalesce(ai_context,'{}'::jsonb)||jsonb_build_object('safe_to_generate',false,'knowledge_status',case when score=100 then'human_review_required'else'incomplete_evidence'end,'allowed_facts_only',true),updated_at=now()where id=profile.id;
insert into public.project_intelligence_events(organization_id,development_id,actor_id,event_type,readiness_percent,note,evidence_summary)values(p_organization_id,p_development_id,p_actor_id,'refreshed',score,left(trim(p_note),500),evidence);return jsonb_build_object('developmentId',p_development_id,'readinessPercent',score,'missingInformation',missing,'evidence',evidence,'safeToGenerate',false,'humanApprovalRequired',true);end $$;
create or replace function public.approve_project_intelligence_dossier(p_actor_id uuid,p_organization_id uuid,p_development_id uuid,p_note text)returns jsonb language plpgsql security definer set search_path='' as $$
declare actor_role text;profile public.project_intelligence_profiles;
begin select coalesce(commercial_role,case role when'admin'then'director'else role end)into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent')then raise exception 'dossier_approval_actor_forbidden';end if;if char_length(trim(coalesce(p_note,'')))<10 then raise exception 'dossier_approval_note_required';end if;select * into profile from public.project_intelligence_profiles where organization_id=p_organization_id and development_id=p_development_id for update;if profile.id is null or profile.readiness_percent<100 then raise exception 'dossier_not_ready';end if;update public.project_intelligence_profiles set onboarding_status='published',approved_at=now(),approved_by=p_actor_id,publication_note=trim(p_note),ai_context=coalesce(ai_context,'{}'::jsonb)||jsonb_build_object('safe_to_generate',true,'knowledge_status','approved_facts_only','allowed_facts_only',true),updated_at=now()where id=profile.id;insert into public.project_intelligence_events(organization_id,development_id,actor_id,event_type,readiness_percent,note,evidence_summary)values(p_organization_id,p_development_id,p_actor_id,'approved',profile.readiness_percent,trim(p_note),profile.evidence_summary);return jsonb_build_object('developmentId',p_development_id,'status','published','safeToGenerate',true,'approvedFactsOnly',true,'auditable',true);end $$;
revoke all on function public.refresh_project_intelligence_dossier(uuid,uuid,uuid,text),function public.approve_project_intelligence_dossier(uuid,uuid,uuid,text)from public,anon,authenticated;grant execute on function public.refresh_project_intelligence_dossier(uuid,uuid,uuid,text),function public.approve_project_intelligence_dossier(uuid,uuid,uuid,text)to service_role;
commit;
