begin;
alter table public.properties add column if not exists typology_id uuid references public.development_typologies(id) on delete restrict,add column if not exists canonical_unit_key text,add column if not exists tower text,add column if not exists orientation text,add column if not exists list_price numeric(16,2),add column if not exists inventory_source text not null default 'manual',add column if not exists inventory_version integer not null default 1,add column if not exists availability_updated_at timestamptz not null default now(),add column if not exists last_synced_at timestamptz;
create unique index if not exists properties_org_canonical_unit_unique on public.properties(organization_id,development_id,canonical_unit_key) where canonical_unit_key is not null;create index if not exists properties_typology_availability_idx on public.properties(organization_id,development_id,typology_id,status);
create table if not exists public.inventory_unit_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,development_id uuid not null references public.developments(id) on delete cascade,property_id uuid not null references public.properties(id) on delete cascade,actor_id uuid not null references public.profiles(id),event_type text not null check(event_type in('created','status_changed','price_changed','profile_updated','synced')),previous_status text,new_status text,previous_price numeric(16,2),new_price numeric(16,2),inventory_version integer not null,reason text not null check(char_length(reason) between 5 and 500),created_at timestamptz not null default now());
create index if not exists inventory_unit_events_history_idx on public.inventory_unit_events(organization_id,property_id,created_at desc);alter table public.inventory_unit_events enable row level security;drop policy if exists inventory_unit_events_scope on public.inventory_unit_events;create policy inventory_unit_events_scope on public.inventory_unit_events for select to authenticated using(organization_id=(select public.current_organization_id()));revoke all on public.inventory_unit_events from anon;revoke insert,update,delete on public.inventory_unit_events from authenticated;grant select on public.inventory_unit_events to authenticated;
create or replace function public.upsert_canonical_inventory_unit(p_actor_id uuid,p_organization_id uuid,p_development_id uuid,p_property_id uuid,p_typology_id uuid,p_unit_number text,p_tower text,p_floor integer,p_orientation text,p_price numeric,p_list_price numeric,p_status text,p_source text,p_reason text,p_expected_updated_at timestamptz default null)returns jsonb language plpgsql security definer set search_path='' as $$
declare actor_role text;target public.properties;previous public.properties;canonical_key text;normalized_status text;event_name text;active_hold boolean;
begin select coalesce(commercial_role,case role when 'admin' then 'director' else role end)into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent','manager')then raise exception 'inventory_actor_forbidden';end if;if not exists(select 1 from public.developments where id=p_development_id and organization_id=p_organization_id)then raise exception 'inventory_development_invalid';end if;if p_typology_id is not null and not exists(select 1 from public.development_typologies where id=p_typology_id and development_id=p_development_id and organization_id=p_organization_id)then raise exception 'inventory_typology_invalid';end if;if char_length(trim(coalesce(p_unit_number,'')))<1 or char_length(trim(coalesce(p_reason,'')))<5 or coalesce(p_price,-1)<0 or p_list_price is not null and p_list_price<0 then raise exception 'inventory_values_invalid';end if;normalized_status:=lower(trim(coalesce(p_status,'available')));if normalized_status not in('available','reserved','sold','blocked')then raise exception 'inventory_status_invalid';end if;canonical_key:=lower(concat_ws(':',nullif(trim(p_tower),''),trim(p_unit_number)));
 if p_property_id is null then insert into public.properties(organization_id,development_id,typology_id,canonical_unit_key,title,unit_number,tower,floor,orientation,typology,price,list_price,area,bedrooms,bathrooms,parking_spaces,status,inventory_source,inventory_version,availability_updated_at,last_synced_at)select p_organization_id,p_development_id,t.id,canonical_key,concat(t.name,' · unidade ',trim(p_unit_number)),trim(p_unit_number),nullif(trim(p_tower),''),p_floor,nullif(trim(p_orientation),''),t.name,p_price,p_list_price,t.private_area,t.bedrooms,t.bathrooms,t.parking_spaces,normalized_status,coalesce(nullif(trim(p_source),''),'manual'),1,now(),case when p_source='integration' then now() else null end from public.development_typologies t where t.id=p_typology_id and t.organization_id=p_organization_id returning * into target;if target.id is null then raise exception 'inventory_typology_required';end if;event_name:='created';
 else select * into previous from public.properties where id=p_property_id and development_id=p_development_id and organization_id=p_organization_id for update;if previous.id is null then raise exception 'inventory_unit_not_found';end if;if p_expected_updated_at is not null and previous.updated_at<>p_expected_updated_at then raise exception 'inventory_concurrent_update';end if;select exists(select 1 from public.atlas_inventory_reservations where property_id=previous.id and organization_id=p_organization_id and status in('held','confirmed')and hold_expires_at>now())into active_hold;if active_hold and(normalized_status<>coalesce(previous.status,'reserved')or p_price<>previous.price)then raise exception 'inventory_active_reservation';end if;
 update public.properties p set typology_id=coalesce(p_typology_id,p.typology_id),canonical_unit_key=canonical_key,unit_number=trim(p_unit_number),tower=nullif(trim(p_tower),''),floor=p_floor,orientation=nullif(trim(p_orientation),''),price=p_price,list_price=p_list_price,status=normalized_status,inventory_source=coalesce(nullif(trim(p_source),''),p.inventory_source),inventory_version=p.inventory_version+1,availability_updated_at=case when p.status is distinct from normalized_status then now()else p.availability_updated_at end,last_synced_at=case when p_source='integration'then now()else p.last_synced_at end,updated_at=now()where p.id=previous.id returning * into target;event_name:=case when previous.status is distinct from target.status then 'status_changed'when previous.price is distinct from target.price then 'price_changed'else 'profile_updated'end;end if;
 insert into public.inventory_unit_events(organization_id,development_id,property_id,actor_id,event_type,previous_status,new_status,previous_price,new_price,inventory_version,reason)values(p_organization_id,p_development_id,target.id,p_actor_id,event_name,previous.status,target.status,previous.price,target.price,target.inventory_version,trim(p_reason));return jsonb_build_object('property',to_jsonb(target),'canonicalMirror',true,'event',event_name,'optimisticConcurrency',true,'reservationGuard',true,'auditable',true);
end $$;
revoke all on function public.upsert_canonical_inventory_unit(uuid,uuid,uuid,uuid,uuid,text,text,integer,text,numeric,numeric,text,text,text,timestamptz)from public,anon,authenticated;grant execute on function public.upsert_canonical_inventory_unit(uuid,uuid,uuid,uuid,uuid,text,text,integer,text,numeric,numeric,text,text,text,timestamptz)to service_role;
commit;
