begin;
create table if not exists public.developers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,legal_name text not null,trade_name text not null,slug text not null,cnpj text,website text,commercial_email text,commercial_phone text,headquarters_city text,headquarters_state text,default_commission_sla_days integer not null default 30 check(default_commission_sla_days between 0 and 365),status text not null default 'active' check(status in('active','inactive','onboarding','archived')),notes text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,slug));
create unique index if not exists developers_org_cnpj_unique on public.developers(organization_id,cnpj) where cnpj is not null;create index if not exists developers_org_status_idx on public.developers(organization_id,status,trade_name);
create table if not exists public.developer_profile_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,developer_id uuid not null references public.developers(id) on delete cascade,actor_id uuid not null references public.profiles(id),event_type text not null check(event_type in('created','updated','status_changed','legacy_linked')),changed_fields text[] not null default '{}',created_at timestamptz not null default now());
alter table public.developers enable row level security;alter table public.developer_profile_events enable row level security;drop policy if exists developers_scope on public.developers;create policy developers_scope on public.developers for select to authenticated using(organization_id=(select public.current_organization_id()));drop policy if exists developer_profile_events_scope on public.developer_profile_events;create policy developer_profile_events_scope on public.developer_profile_events for select to authenticated using(organization_id=(select public.current_organization_id()));revoke all on public.developers,public.developer_profile_events from anon;revoke insert,update,delete on public.developers,public.developer_profile_events from authenticated;grant select on public.developers,public.developer_profile_events to authenticated;
alter table public.developments add column if not exists developer_id uuid references public.developers(id) on delete restrict;create index if not exists developments_org_developer_idx on public.developments(organization_id,developer_id,status);
insert into public.developers(organization_id,legal_name,trade_name,slug,status,created_by)select d.organization_id,trim(d.developer_name),trim(d.developer_name),lower(regexp_replace(trim(d.developer_name),'[^a-zA-Z0-9]+','-','g')),'active',(select p.id from public.profiles p where p.organization_id=d.organization_id and p.active=true order by case when coalesce(p.commercial_role,p.role) in('director','admin') then 0 else 1 end,p.created_at limit 1) from public.developments d where nullif(trim(d.developer_name),'') is not null and exists(select 1 from public.profiles p where p.organization_id=d.organization_id and p.active=true) group by d.organization_id,trim(d.developer_name) on conflict(organization_id,slug)do nothing;
update public.developments d set developer_id=dev.id from public.developers dev where d.developer_id is null and dev.organization_id=d.organization_id and lower(trim(dev.trade_name))=lower(trim(d.developer_name));

create or replace function public.upsert_developer_profile(p_actor_id uuid,p_organization_id uuid,p_developer_id uuid,p_legal_name text,p_trade_name text,p_cnpj text,p_website text,p_commercial_email text,p_commercial_phone text,p_headquarters_city text,p_headquarters_state text,p_default_commission_sla_days integer,p_status text,p_notes text)returns jsonb language plpgsql security definer set search_path='' as $$
declare actor_role text;target public.developers;normalized_slug text;normalized_cnpj text;event text;fields text[];
begin select coalesce(commercial_role,case role when 'admin' then 'director' else role end) into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent') then raise exception 'developer_actor_forbidden';end if;if char_length(trim(coalesce(p_legal_name,'')))<2 or char_length(trim(coalesce(p_trade_name,'')))<2 or p_default_commission_sla_days<0 or p_default_commission_sla_days>365 or p_status not in('active','inactive','onboarding','archived') then raise exception 'developer_values_invalid';end if;
 normalized_slug:=lower(regexp_replace(trim(p_trade_name),'[^a-zA-Z0-9]+','-','g'));normalized_cnpj:=nullif(regexp_replace(coalesce(p_cnpj,''),'\D','','g'),'');if normalized_cnpj is not null and char_length(normalized_cnpj)<>14 then raise exception 'developer_cnpj_invalid';end if;if nullif(trim(coalesce(p_website,'')),'') is not null and trim(p_website)!~'^https://[^ ]+$' then raise exception 'developer_website_invalid';end if;
 if p_developer_id is null then insert into public.developers(organization_id,legal_name,trade_name,slug,cnpj,website,commercial_email,commercial_phone,headquarters_city,headquarters_state,default_commission_sla_days,status,notes,created_by)values(p_organization_id,trim(p_legal_name),trim(p_trade_name),normalized_slug,normalized_cnpj,nullif(trim(p_website),''),nullif(lower(trim(p_commercial_email)),''),nullif(trim(p_commercial_phone),''),nullif(trim(p_headquarters_city),''),nullif(upper(trim(p_headquarters_state)),''),p_default_commission_sla_days,p_status,nullif(trim(p_notes),''),p_actor_id)returning * into target;event:='created';fields:=array['all'];else update public.developers set legal_name=trim(p_legal_name),trade_name=trim(p_trade_name),slug=normalized_slug,cnpj=normalized_cnpj,website=nullif(trim(p_website),''),commercial_email=nullif(lower(trim(p_commercial_email)),''),commercial_phone=nullif(trim(p_commercial_phone),''),headquarters_city=nullif(trim(p_headquarters_city),''),headquarters_state=nullif(upper(trim(p_headquarters_state)),''),default_commission_sla_days=p_default_commission_sla_days,status=p_status,notes=nullif(trim(p_notes),''),updated_at=now() where id=p_developer_id and organization_id=p_organization_id returning * into target;if target.id is null then raise exception 'developer_not_found';end if;event:='updated';fields:=array['profile'];end if;
 insert into public.developer_profile_events(organization_id,developer_id,actor_id,event_type,changed_fields)values(p_organization_id,target.id,p_actor_id,event,fields);return jsonb_build_object('developer',to_jsonb(target)-'notes','sourceOfTruth',true,'legacyNameCompatibility',true,'auditable',true);end $$;
revoke all on function public.upsert_developer_profile(uuid,uuid,uuid,text,text,text,text,text,text,text,text,integer,text,text) from public,anon,authenticated;grant execute on function public.upsert_developer_profile(uuid,uuid,uuid,text,text,text,text,text,text,text,text,integer,text,text) to service_role;
commit;
