begin;
create table if not exists public.conversion_calibration_models(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,version integer not null,source_model_version text not null,dataset_version_id uuid references public.conversion_dataset_versions(id) on delete restrict,
 method text not null default 'reliability_bins' check(method in('reliability_bins')),bins jsonb not null,example_count integer not null,positive_count integer not null,negative_count integer not null,
 brier_score numeric(8,6),expected_calibration_error numeric(8,6),eligible boolean not null default false,status text not null default 'draft' check(status in('draft','active','archived','rejected')),
 created_by uuid not null references public.profiles(id),approved_by uuid references public.profiles(id),approval_reason text,approved_at timestamptz,created_at timestamptz not null default now(),unique(organization_id,version)
);
create unique index if not exists conversion_calibration_one_active on public.conversion_calibration_models(organization_id)where status='active';
alter table public.conversion_calibration_models enable row level security;drop policy if exists conversion_calibration_models_scope on public.conversion_calibration_models;create policy conversion_calibration_models_scope on public.conversion_calibration_models for select to authenticated using(organization_id=(select public.current_organization_id()));revoke all on public.conversion_calibration_models from anon;revoke insert,update,delete on public.conversion_calibration_models from authenticated;grant select on public.conversion_calibration_models to authenticated;grant all on public.conversion_calibration_models to service_role;

create or replace function public.build_conversion_calibration_candidate(p_actor_id uuid,p_organization_id uuid,p_dataset_version_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$declare actor_role text;dataset_row public.conversion_dataset_versions%rowtype;model_version integer;model_id uuid;bins_data jsonb:='[]'::jsonb;examples integer:=0;positives integer:=0;negatives integer:=0;brier numeric;ece numeric:=0;is_eligible boolean;
begin select coalesce(commercial_role,case role when'admin'then'director'else role end)into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent')then raise exception 'calibration_actor_forbidden';end if;select*into dataset_row from public.conversion_dataset_versions where id=p_dataset_version_id and organization_id=p_organization_id;if not found then raise exception 'calibration_dataset_not_found';end if;
 with examples_cte as(select s.predicted_probability::numeric predicted,o.label_value::numeric label from public.conversion_feature_snapshots s join lateral(select x.label_value from public.conversion_outcome_labels x where x.organization_id=s.organization_id and x.lead_id=s.lead_id and x.outcome_at>s.feature_cutoff_at and x.outcome_at<=s.feature_cutoff_at+make_interval(days=>s.horizon_days)order by x.outcome_at limit 1)o on true where s.organization_id=p_organization_id and s.feature_cutoff_at<=dataset_row.cutoff_at),stats as(select least(9,floor(predicted/10)::integer)bucket,count(*)n,avg(predicted)avg_predicted,avg(label)*100 observed_rate from examples_cte group by 1),totals as(select count(*)n,count(*)filter(where label=1)pos,count(*)filter(where label=0)neg,avg(power(predicted/100-label,2))brier from examples_cte)
 select coalesce(jsonb_agg(jsonb_build_object('bucket',bucket,'lower',bucket*10,'upper',case when bucket=9 then 100 else(bucket+1)*10 end,'count',stats.n,'averagePredicted',round(avg_predicted,2),'observedRate',round(observed_rate,2),'reliable',stats.n>=20)order by bucket),'[]'::jsonb),totals.n,totals.pos,totals.neg,totals.brier,coalesce(sum(stats.n::numeric/greatest(totals.n,1)*abs(stats.avg_predicted-stats.observed_rate))/100,0)into bins_data,examples,positives,negatives,brier,ece from stats cross join totals group by totals.n,totals.pos,totals.neg,totals.brier;
 is_eligible:=examples>=100 and positives>=20 and negatives>=20;perform pg_advisory_xact_lock(hashtextextended('conversion-calibration:'||p_organization_id::text,0));select coalesce(max(version),0)+1 into model_version from public.conversion_calibration_models where organization_id=p_organization_id;
 insert into public.conversion_calibration_models(organization_id,version,source_model_version,dataset_version_id,bins,example_count,positive_count,negative_count,brier_score,expected_calibration_error,eligible,created_by)values(p_organization_id,model_version,'atlas-baseline-v1',p_dataset_version_id,bins_data,examples,positives,negatives,round(brier,6),round(ece,6),is_eligible,p_actor_id)returning id into model_id;
 return jsonb_build_object('modelId',model_id,'version',model_version,'examples',examples,'positive',positives,'negative',negatives,'brierScore',round(brier,6),'expectedCalibrationError',round(ece,6),'eligible',is_eligible,'automaticPromotion',false);
end $$;
create or replace function public.activate_conversion_calibration(p_actor_id uuid,p_organization_id uuid,p_model_id uuid,p_reason text)
returns jsonb language plpgsql security definer set search_path='' as $$declare actor_role text;target public.conversion_calibration_models%rowtype;begin select coalesce(commercial_role,case role when'admin'then'director'else role end)into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role<>'director'then raise exception 'calibration_director_required';end if;if char_length(trim(coalesce(p_reason,'')))<10 then raise exception 'calibration_reason_required';end if;perform pg_advisory_xact_lock(hashtextextended('conversion-calibration:'||p_organization_id::text,0));select*into target from public.conversion_calibration_models where id=p_model_id and organization_id=p_organization_id for update;if not found or not target.eligible or target.status not in('draft','active')then raise exception 'calibration_not_eligible';end if;update public.conversion_calibration_models set status='archived'where organization_id=p_organization_id and status='active'and id<>p_model_id;update public.conversion_calibration_models set status='active',approved_by=p_actor_id,approval_reason=trim(p_reason),approved_at=now()where id=p_model_id;return jsonb_build_object('modelId',p_model_id,'version',target.version,'active',true,'humanApproved',true,'reasonRecorded',true);end $$;
create or replace function public.apply_active_conversion_calibration(p_organization_id uuid,p_raw_probability numeric)returns numeric language sql stable security definer set search_path='' as $$select coalesce((select(case when(b.value->>'reliable')::boolean then(b.value->>'observedRate')::numeric else greatest(1,least(95,p_raw_probability))end)from public.conversion_calibration_models m cross join lateral jsonb_array_elements(m.bins)b(value)where m.organization_id=p_organization_id and m.status='active'and p_raw_probability>=(b.value->>'lower')::numeric and p_raw_probability<= (b.value->>'upper')::numeric order by(b.value->>'bucket')::integer limit 1),greatest(1,least(95,p_raw_probability)))$$;
revoke all on function public.build_conversion_calibration_candidate(uuid,uuid,uuid),public.activate_conversion_calibration(uuid,uuid,uuid,text),public.apply_active_conversion_calibration(uuid,numeric)from public,anon,authenticated;grant execute on function public.build_conversion_calibration_candidate(uuid,uuid,uuid),public.activate_conversion_calibration(uuid,uuid,uuid,text),public.apply_active_conversion_calibration(uuid,numeric)to service_role;
commit;
