begin;
create table if not exists public.ai_orchestration_decisions(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid references public.profiles(id) on delete set null,feature text not null,requested_task text not null check(requested_task in('fast','commercial','reasoning','research')),resolved_task text not null check(resolved_task in('fast','commercial','reasoning','research')),
 data_class text not null check(data_class in('public','internal','personal')),risk_level text not null check(risk_level in('low','medium','high')),provider_order text[] not null,selected_provider text,selected_model text,token_budget integer not null check(token_budget between 100 and 10000),
 routing_reasons text[] not null,human_review_required boolean not null,fallback_used boolean not null default false,status text not null check(status in('planned','completed','fallback','failed')),latency_ms integer,total_tokens integer,estimated_cost_usd numeric(14,8),created_at timestamptz not null default now(),completed_at timestamptz
);
create index if not exists ai_orchestration_decisions_org_time_idx on public.ai_orchestration_decisions(organization_id,created_at desc);create index if not exists ai_orchestration_decisions_provider_idx on public.ai_orchestration_decisions(organization_id,selected_provider,created_at desc);
alter table public.ai_orchestration_decisions enable row level security;drop policy if exists ai_orchestration_decisions_scope on public.ai_orchestration_decisions;create policy ai_orchestration_decisions_scope on public.ai_orchestration_decisions for select to authenticated using(organization_id=(select public.current_organization_id()));revoke all on public.ai_orchestration_decisions from anon;revoke insert,update,delete on public.ai_orchestration_decisions from authenticated;grant select on public.ai_orchestration_decisions to authenticated;grant all on public.ai_orchestration_decisions to service_role;
commit;
