begin;
alter table public.project_materials add column if not exists review_status text not null default 'pending' check(review_status in('pending','verified','rejected')),add column if not exists verified_by uuid references public.profiles(id),add column if not exists verified_at timestamptz,add column if not exists review_note text;
create index if not exists project_materials_review_idx on public.project_materials(organization_id,development_id,is_current,review_status,valid_until);
create table if not exists public.project_material_review_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,development_id uuid not null references public.developments(id) on delete cascade,material_id uuid not null references public.project_materials(id) on delete cascade,actor_id uuid not null references public.profiles(id),previous_status text,new_status text not null check(new_status in('pending','verified','rejected')),note text not null check(char_length(note) between 5 and 500),created_at timestamptz not null default now());
alter table public.project_material_review_events enable row level security;drop policy if exists project_material_review_events_scope on public.project_material_review_events;create policy project_material_review_events_scope on public.project_material_review_events for select to authenticated using(organization_id=(select public.current_organization_id()));revoke all on public.project_material_review_events from anon;revoke insert,update,delete on public.project_material_review_events from authenticated;grant select on public.project_material_review_events to authenticated;
create or replace function public.review_project_material(p_actor_id uuid,p_organization_id uuid,p_material_id uuid,p_status text,p_note text)returns jsonb language plpgsql security definer set search_path='' as $$
declare actor_role text;target public.project_materials;previous text;
begin select coalesce(commercial_role,case role when'admin'then'director'else role end)into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent','manager')then raise exception 'material_review_actor_forbidden';end if;if p_status not in('verified','rejected')or char_length(trim(coalesce(p_note,'')))<5 then raise exception 'material_review_invalid';end if;select * into target from public.project_materials where id=p_material_id and organization_id=p_organization_id and is_current=true for update;if target.id is null then raise exception 'material_review_not_current';end if;previous:=target.review_status;update public.project_materials set review_status=p_status,verified_by=case when p_status='verified'then p_actor_id else null end,verified_at=case when p_status='verified'then now()else null end,review_note=trim(p_note),updated_at=now()where id=target.id;insert into public.project_material_review_events(organization_id,development_id,material_id,actor_id,previous_status,new_status,note)values(p_organization_id,target.development_id,target.id,p_actor_id,previous,p_status,trim(p_note));return jsonb_build_object('materialId',target.id,'previousStatus',previous,'reviewStatus',p_status,'currentVersionOnly',true,'auditable',true);end $$;
revoke all on function public.review_project_material(uuid,uuid,uuid,text,text)from public,anon,authenticated;grant execute on function public.review_project_material(uuid,uuid,uuid,text,text)to service_role;
commit;
