begin;
create table if not exists public.inventory_import_batches(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,development_id uuid not null references public.developments(id) on delete cascade,file_name text not null,file_sha256 text not null,row_count integer not null default 0,create_count integer not null default 0,update_count integer not null default 0,unchanged_count integer not null default 0,conflict_count integer not null default 0,error_count integer not null default 0,status text not null default 'preview' check(status in('preview','applying','applied','rejected','failed')),column_mapping jsonb not null default '{}',created_by uuid not null references public.profiles(id),reviewed_by uuid references public.profiles(id),review_reason text,created_at timestamptz not null default now(),reviewed_at timestamptz,applied_at timestamptz,unique(organization_id,development_id,file_sha256));
create table if not exists public.inventory_import_rows(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.inventory_import_batches(id) on delete cascade,organization_id uuid not null references public.organizations(id) on delete cascade,development_id uuid not null references public.developments(id) on delete cascade,row_number integer not null,action text not null check(action in('create','update','unchanged','conflict','error')),canonical_unit_key text,typology_id uuid references public.development_typologies(id),current_property_id uuid references public.properties(id),expected_updated_at timestamptz,normalized_data jsonb not null default '{}',differences text[] not null default '{}',issues text[] not null default '{}',created_at timestamptz not null default now(),unique(batch_id,row_number));
create index if not exists inventory_import_batches_review_idx on public.inventory_import_batches(organization_id,development_id,status,created_at desc);create index if not exists inventory_import_rows_action_idx on public.inventory_import_rows(batch_id,action,row_number);
alter table public.inventory_import_batches enable row level security;alter table public.inventory_import_rows enable row level security;drop policy if exists inventory_import_batches_scope on public.inventory_import_batches;create policy inventory_import_batches_scope on public.inventory_import_batches for select to authenticated using(organization_id=(select public.current_organization_id()));drop policy if exists inventory_import_rows_scope on public.inventory_import_rows;create policy inventory_import_rows_scope on public.inventory_import_rows for select to authenticated using(organization_id=(select public.current_organization_id()));revoke all on public.inventory_import_batches,public.inventory_import_rows from anon;revoke insert,update,delete on public.inventory_import_batches,public.inventory_import_rows from authenticated;grant select on public.inventory_import_batches,public.inventory_import_rows to authenticated;
create or replace function public.apply_inventory_import_batch(p_actor_id uuid,p_organization_id uuid,p_batch_id uuid,p_reason text)returns jsonb language plpgsql security definer set search_path='' as $$
declare actor_role text;batch public.inventory_import_batches;item public.inventory_import_rows;applied integer:=0;result jsonb;
begin select coalesce(commercial_role,case role when 'admin'then'director'else role end)into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent')then raise exception 'inventory_import_actor_forbidden';end if;if char_length(trim(coalesce(p_reason,'')))<10 then raise exception 'inventory_import_reason_required';end if;select * into batch from public.inventory_import_batches where id=p_batch_id and organization_id=p_organization_id for update;if batch.id is null or batch.status<>'preview'then raise exception 'inventory_import_batch_unavailable';end if;if batch.error_count>0 or batch.conflict_count>0 then raise exception 'inventory_import_unresolved_rows';end if;update public.inventory_import_batches set status='applying',reviewed_by=p_actor_id,review_reason=trim(p_reason),reviewed_at=now()where id=batch.id;
 for item in select * from public.inventory_import_rows where batch_id=batch.id and action in('create','update')order by row_number loop select public.upsert_canonical_inventory_unit(p_actor_id,p_organization_id,batch.development_id,item.current_property_id,item.typology_id,item.normalized_data->>'unitNumber',item.normalized_data->>'tower',nullif(item.normalized_data->>'floor','')::integer,item.normalized_data->>'orientation',nullif(item.normalized_data->>'price','')::numeric,nullif(item.normalized_data->>'listPrice','')::numeric,item.normalized_data->>'status','integration',concat('Importação ',batch.file_name,' — ',trim(p_reason)),item.expected_updated_at)into result;applied:=applied+1;end loop;
 update public.inventory_import_batches set status='applied',applied_at=now()where id=batch.id;return jsonb_build_object('batchId',batch.id,'status','applied','appliedRows',applied,'unchangedRows',batch.unchanged_count,'humanApproved',true,'atomic',true,'auditable',true);
exception when others then if batch.id is not null then update public.inventory_import_batches set status='failed',reviewed_by=p_actor_id,review_reason=concat(trim(p_reason),' | ',sqlerrm),reviewed_at=now()where id=batch.id;end if;raise;end $$;
revoke all on function public.apply_inventory_import_batch(uuid,uuid,uuid,text)from public,anon,authenticated;grant execute on function public.apply_inventory_import_batch(uuid,uuid,uuid,text)to service_role;
commit;
