-- Fase 94: catálogo versionado e aprendizagem de criativos imobiliários.
create table if not exists public.creative_intelligence_versions(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,creative_asset_id uuid not null references public.creative_assets(id) on delete cascade,version_number integer not null check(version_number>0),
 development_id uuid not null references public.developments(id) on delete restrict,developer_id uuid references public.developers(id) on delete restrict,
 funnel_stage text not null check(funnel_stage in('discovery','consideration','qualification','visit','proposal','conversion','reactivation')),persona_moment text not null check(persona_moment in('first_home','upgrade','investor','relocation','downsizing','unspecified')),
 message_angle text not null check(message_angle in('location','lifestyle','investment','affordability','scarcity','architecture','amenities','trust')),primary_promise text not null,objection_addressed text not null,
 format text not null check(format in('static','carousel','short_video','long_video','stories','reels','display','portal_listing')),hook text not null,call_to_action text not null,
 source_material_ids uuid[] not null default '{}',content_hash text not null check(content_hash~'^[a-f0-9]{64}$'),review_status text not null default 'draft' check(review_status in('draft','approved','rejected','archived')),
 created_by uuid not null references public.profiles(id),reviewed_by uuid references public.profiles(id),review_reason text,reviewed_at timestamptz,created_at timestamptz not null default now(),unique(organization_id,creative_asset_id,version_number),unique(organization_id,content_hash),
 check(char_length(trim(primary_promise)) between 10 and 500 and char_length(trim(objection_addressed)) between 5 and 500 and char_length(trim(hook)) between 5 and 300)
);
create table if not exists public.creative_performance_daily_facts(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,creative_version_id uuid not null references public.creative_intelligence_versions(id) on delete cascade,platform text not null check(platform in('meta','google_ads','youtube','tiktok_ads','portal')),reference_date date not null,currency text not null default 'BRL' check(currency='BRL'),
 spend numeric(14,2) not null default 0 check(spend>=0),impressions bigint not null default 0 check(impressions>=0),reach bigint not null default 0 check(reach>=0),clicks bigint not null default 0 check(clicks>=0),video_starts bigint not null default 0 check(video_starts>=0),video_completions bigint not null default 0 check(video_completions>=0),crm_leads bigint not null default 0 check(crm_leads>=0),qualified_leads bigint not null default 0 check(qualified_leads>=0),visits bigint not null default 0 check(visits>=0),proposals bigint not null default 0 check(proposals>=0),wins bigint not null default 0 check(wins>=0),
 source_hash text not null check(source_hash~'^[a-f0-9]{64}$'),recorded_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(organization_id,creative_version_id,platform,reference_date,source_hash),
 check(reach<=impressions and video_completions<=video_starts and qualified_leads<=crm_leads and visits<=crm_leads and proposals<=crm_leads and wins<=crm_leads and reference_date<=current_date and reference_date>=current_date-730)
);
create index if not exists creative_versions_org_idx on public.creative_intelligence_versions(organization_id,development_id,review_status,created_at desc);create index if not exists creative_facts_reporting_idx on public.creative_performance_daily_facts(organization_id,reference_date desc,platform);
alter table public.creative_intelligence_versions enable row level security;alter table public.creative_performance_daily_facts enable row level security;
drop policy if exists creative_intelligence_leadership_read on public.creative_intelligence_versions;create policy creative_intelligence_leadership_read on public.creative_intelligence_versions for select to authenticated using(organization_id=(select public.current_organization_id())and exists(select 1 from public.profiles p where p.id=auth.uid()and coalesce(p.commercial_role,case when p.role='admin'then'director'else p.role end)in('director','superintendent')));
drop policy if exists creative_facts_leadership_read on public.creative_performance_daily_facts;create policy creative_facts_leadership_read on public.creative_performance_daily_facts for select to authenticated using(organization_id=(select public.current_organization_id())and exists(select 1 from public.profiles p where p.id=auth.uid()and coalesce(p.commercial_role,case when p.role='admin'then'director'else p.role end)in('director','superintendent')));
revoke all on public.creative_intelligence_versions,public.creative_performance_daily_facts from anon,authenticated;grant select on public.creative_intelligence_versions,public.creative_performance_daily_facts to authenticated;
create or replace function public.review_creative_intelligence_version(p_actor_id uuid,p_organization_id uuid,p_version_id uuid,p_decision text,p_reason text)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v_status text;begin if not exists(select 1 from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true and coalesce(commercial_role,case when role='admin'then'director'else role end)='director')then raise exception 'creative_director_required';end if;if p_decision not in('approved','rejected')or char_length(trim(coalesce(p_reason,'')))<20 then raise exception 'creative_review_invalid';end if;update public.creative_intelligence_versions set review_status=p_decision,reviewed_by=p_actor_id,review_reason=trim(p_reason),reviewed_at=now() where id=p_version_id and organization_id=p_organization_id and review_status='draft' returning review_status into v_status;if v_status is null then raise exception 'creative_not_reviewable';end if;return jsonb_build_object('versionId',p_version_id,'status',v_status,'published',false,'externalChangeExecuted',false);end$$;
revoke all on function public.review_creative_intelligence_version(uuid,uuid,uuid,text,text)from public,anon,authenticated;grant execute on function public.review_creative_intelligence_version(uuid,uuid,uuid,text,text)to service_role;
