begin;
create table if not exists public.development_typologies(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,development_id uuid not null references public.developments(id) on delete cascade,code text not null,name text not null,bedrooms smallint check(bedrooms>=0),bathrooms smallint check(bathrooms>=0),suites smallint check(suites>=0),parking_spaces smallint check(parking_spaces>=0),private_area numeric(12,2) not null check(private_area>0),price_from numeric(16,2) check(price_from>=0),price_to numeric(16,2) check(price_to>=0),units_total integer check(units_total>=0),units_available integer check(units_available>=0),status text not null default 'active' check(status in('draft','active','inactive','sold_out')),created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,development_id,code));
create table if not exists public.development_features(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,development_id uuid not null references public.developments(id) on delete cascade,category text not null check(category in('location','mobility','leisure','security','technology','sustainability','services','architecture','unit','commercial')),name text not null,description text,commercial_priority smallint not null default 3 check(commercial_priority between 1 and 5),verified boolean not null default false,source_reference text,status text not null default 'active' check(status in('draft','active','inactive')),created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,development_id,category,name));
create table if not exists public.development_catalog_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,development_id uuid not null references public.developments(id) on delete cascade,actor_id uuid not null references public.profiles(id),entity_type text not null check(entity_type in('typology','feature')),entity_id uuid not null,event_type text not null check(event_type in('created','updated')),created_at timestamptz not null default now());
create index if not exists development_typologies_match_idx on public.development_typologies(organization_id,development_id,status,bedrooms,private_area,price_from);
create index if not exists development_features_ai_idx on public.development_features(organization_id,development_id,status,verified,commercial_priority desc);
alter table public.development_typologies enable row level security;alter table public.development_features enable row level security;alter table public.development_catalog_events enable row level security;
drop policy if exists development_typologies_scope on public.development_typologies;create policy development_typologies_scope on public.development_typologies for select to authenticated using(organization_id=(select public.current_organization_id()));
drop policy if exists development_features_scope on public.development_features;create policy development_features_scope on public.development_features for select to authenticated using(organization_id=(select public.current_organization_id()));
drop policy if exists development_catalog_events_scope on public.development_catalog_events;create policy development_catalog_events_scope on public.development_catalog_events for select to authenticated using(organization_id=(select public.current_organization_id()));
revoke all on public.development_typologies,public.development_features,public.development_catalog_events from anon;revoke insert,update,delete on public.development_typologies,public.development_features,public.development_catalog_events from authenticated;grant select on public.development_typologies,public.development_features,public.development_catalog_events to authenticated;

create or replace function public.upsert_development_catalog_item(p_actor_id uuid,p_organization_id uuid,p_development_id uuid,p_entity_type text,p_entity_id uuid,p_payload jsonb)returns jsonb language plpgsql security definer set search_path='' as $$
declare actor_role text;target_id uuid;event_name text;v_code text;v_name text;v_category text;v_min numeric;v_max numeric;
begin
 select coalesce(commercial_role,case role when 'admin' then 'director' else role end) into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent') then raise exception 'catalog_actor_forbidden';end if;
 if not exists(select 1 from public.developments where id=p_development_id and organization_id=p_organization_id)then raise exception 'catalog_development_invalid';end if;
 if p_entity_type='typology' then
  v_code:=upper(trim(coalesce(p_payload->>'code','')));v_name:=trim(coalesce(p_payload->>'name',''));v_min:=nullif(p_payload->>'priceFrom','')::numeric;v_max:=nullif(p_payload->>'priceTo','')::numeric;
  if char_length(v_code)<1 or char_length(v_name)<2 or coalesce(nullif(p_payload->>'privateArea','')::numeric,0)<=0 then raise exception 'catalog_typology_required';end if;
  if v_min is not null and v_max is not null and v_min>v_max then raise exception 'catalog_typology_price_range_invalid';end if;
  if coalesce(nullif(p_payload->>'unitsAvailable','')::integer,0)>coalesce(nullif(p_payload->>'unitsTotal','')::integer,0) then raise exception 'catalog_typology_units_invalid';end if;
  if p_entity_id is null then insert into public.development_typologies(organization_id,development_id,code,name,bedrooms,bathrooms,suites,parking_spaces,private_area,price_from,price_to,units_total,units_available,status,created_by)values(p_organization_id,p_development_id,v_code,v_name,nullif(p_payload->>'bedrooms','')::smallint,nullif(p_payload->>'bathrooms','')::smallint,nullif(p_payload->>'suites','')::smallint,nullif(p_payload->>'parkingSpaces','')::smallint,(p_payload->>'privateArea')::numeric,v_min,v_max,nullif(p_payload->>'unitsTotal','')::integer,nullif(p_payload->>'unitsAvailable','')::integer,coalesce(nullif(p_payload->>'status',''),'active'),p_actor_id)returning id into target_id;event_name:='created';
  else update public.development_typologies set code=v_code,name=v_name,bedrooms=nullif(p_payload->>'bedrooms','')::smallint,bathrooms=nullif(p_payload->>'bathrooms','')::smallint,suites=nullif(p_payload->>'suites','')::smallint,parking_spaces=nullif(p_payload->>'parkingSpaces','')::smallint,private_area=(p_payload->>'privateArea')::numeric,price_from=v_min,price_to=v_max,units_total=nullif(p_payload->>'unitsTotal','')::integer,units_available=nullif(p_payload->>'unitsAvailable','')::integer,status=coalesce(nullif(p_payload->>'status',''),'active'),updated_at=now() where id=p_entity_id and development_id=p_development_id and organization_id=p_organization_id returning id into target_id;event_name:='updated';end if;
 elsif p_entity_type='feature' then
  v_name:=trim(coalesce(p_payload->>'name',''));v_category:=coalesce(nullif(p_payload->>'category',''),'unit');if char_length(v_name)<2 or v_category not in('location','mobility','leisure','security','technology','sustainability','services','architecture','unit','commercial')then raise exception 'catalog_feature_invalid';end if;
  if coalesce((p_payload->>'verified')::boolean,false) and char_length(trim(coalesce(p_payload->>'sourceReference','')))<3 then raise exception 'catalog_feature_source_required';end if;
  if p_entity_id is null then insert into public.development_features(organization_id,development_id,category,name,description,commercial_priority,verified,source_reference,status,created_by)values(p_organization_id,p_development_id,v_category,v_name,nullif(trim(p_payload->>'description'),''),coalesce(nullif(p_payload->>'commercialPriority','')::smallint,3),coalesce((p_payload->>'verified')::boolean,false),nullif(trim(p_payload->>'sourceReference'),''),coalesce(nullif(p_payload->>'status',''),'active'),p_actor_id)returning id into target_id;event_name:='created';
  else update public.development_features set category=v_category,name=v_name,description=nullif(trim(p_payload->>'description'),''),commercial_priority=coalesce(nullif(p_payload->>'commercialPriority','')::smallint,3),verified=coalesce((p_payload->>'verified')::boolean,false),source_reference=nullif(trim(p_payload->>'sourceReference'),''),status=coalesce(nullif(p_payload->>'status',''),'active'),updated_at=now() where id=p_entity_id and development_id=p_development_id and organization_id=p_organization_id returning id into target_id;event_name:='updated';end if;
 else raise exception 'catalog_entity_type_invalid';end if;
 if target_id is null then raise exception 'catalog_item_not_found';end if;insert into public.development_catalog_events(organization_id,development_id,actor_id,entity_type,entity_id,event_type)values(p_organization_id,p_development_id,p_actor_id,p_entity_type,target_id,event_name);
 return jsonb_build_object('id',target_id,'entityType',p_entity_type,'event',event_name,'matchingReady',p_entity_type='typology','aiReady',p_entity_type='feature','auditable',true);
end $$;
revoke all on function public.upsert_development_catalog_item(uuid,uuid,uuid,text,uuid,jsonb) from public,anon,authenticated;grant execute on function public.upsert_development_catalog_item(uuid,uuid,uuid,text,uuid,jsonb) to service_role;
commit;
