begin;
create or replace function public.get_portfolio_audit_ledger(p_actor_id uuid,p_organization_id uuid,p_limit integer default 100)returns jsonb language plpgsql security definer set search_path='' as $$
declare actor_role text;events jsonb;summary jsonb;
begin
 if p_limit<1 or p_limit>500 then raise exception 'portfolio_audit_limit_invalid';end if;select coalesce(commercial_role,case role when 'admin' then 'director' else role end) into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent','manager') then raise exception 'portfolio_audit_actor_forbidden';end if;
 with recursive visible as(select id from public.profiles where id=p_actor_id and organization_id=p_organization_id union all select p.id from public.profiles p join visible v on p.reports_to=v.id where p.organization_id=p_organization_id and p.active=true),ledger as(
  select e.created_at occurred_at,'distribution' event_type,e.assigned_to broker_id,e.lead_id,e.development_id,e.actor_id,jsonb_build_object('algorithm',e.algorithm,'explanation',e.score_snapshot-'source') details from public.lead_distribution_events e where e.organization_id=p_organization_id and(actor_role='director' or e.assigned_to in(select id from visible))
  union all select i.created_at,'transfer',i.target_owner_id,i.lead_id,l.development_id,b.actor_id,jsonb_build_object('previousOwnerId',i.previous_owner_id,'batchId',b.id,'reasonRecorded',b.reason is not null) from public.lead_transfer_items i join public.lead_transfer_batches b on b.id=i.batch_id join public.leads l on l.id=i.lead_id and l.organization_id=p_organization_id where b.organization_id=p_organization_id and(actor_role='director' or i.target_owner_id in(select id from visible) or i.previous_owner_id in(select id from visible))
  union all select r.created_at,'reservation_'||r.status,r.broker_id,r.lead_id,l.development_id,r.broker_id,jsonb_build_object('reservationId',r.id,'expiresAt',r.expires_at,'acceptedAt',r.accepted_at,'releasedAt',r.released_at,'releaseReason',r.release_reason) from public.lead_assignment_reservations r join public.leads l on l.id=r.lead_id and l.organization_id=p_organization_id where r.organization_id=p_organization_id and(actor_role='director' or r.broker_id in(select id from visible))
  union all select a.created_at,'absence',a.broker_id,null::uuid,null::uuid,a.actor_id,jsonb_build_object('absenceId',a.id,'managerId',a.manager_id,'endsAt',a.ends_at,'status',a.status,'transferredCount',a.transferred_count,'reasonRecorded',true) from public.broker_absence_events a where a.organization_id=p_organization_id and(actor_role='director' or a.broker_id in(select id from visible))
  union all select c.updated_at,'capacity',c.profile_id,null::uuid,null::uuid,c.updated_by,jsonb_build_object('maxActiveLeads',c.max_active_leads,'maxProjectLeads',c.max_project_leads,'warningPercent',c.warning_percent,'reasonRecorded',true) from public.broker_capacity_limits c where c.organization_id=p_organization_id and(actor_role='director' or c.profile_id in(select id from visible))
 ),limited as(select * from ledger order by occurred_at desc limit p_limit)
 select coalesce(jsonb_agg(jsonb_build_object('occurredAt',occurred_at,'eventType',event_type,'brokerId',broker_id,'leadId',lead_id,'developmentId',development_id,'actorId',actor_id,'details',details)order by occurred_at desc),'[]'::jsonb) into events from limited;
 select jsonb_build_object('total',jsonb_array_length(events),'distributions',(select count(*) from jsonb_array_elements(events)e where e->>'eventType'='distribution'),'transfers',(select count(*) from jsonb_array_elements(events)e where e->>'eventType'='transfer'),'reservations',(select count(*) from jsonb_array_elements(events)e where e->>'eventType' like 'reservation_%'),'returns',(select count(*) from jsonb_array_elements(events)e where e->>'eventType'='reservation_expired'),'absences',(select count(*) from jsonb_array_elements(events)e where e->>'eventType'='absence'),'capacityChanges',(select count(*) from jsonb_array_elements(events)e where e->>'eventType'='capacity')) into summary;
 return jsonb_build_object('events',events,'summary',summary,'maximum',p_limit,'hierarchicalScope',true,'piiExposed',false,'immutableSources',true,'generatedAt',now());
end $$;
revoke all on function public.get_portfolio_audit_ledger(uuid,uuid,integer) from public,anon,authenticated;grant execute on function public.get_portfolio_audit_ledger(uuid,uuid,integer) to service_role;
commit;
