begin;
create table if not exists public.lead_distribution_priority_rules(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,development_id uuid not null references public.developments(id) on delete cascade,source_key text not null,priority smallint not null default 5 check(priority between 1 and 10),sla_minutes integer not null default 60 check(sla_minutes between 5 and 10080),enabled boolean not null default true,updated_by uuid not null references public.profiles(id),reason text not null check(char_length(reason) between 10 and 500),updated_at timestamptz not null default now(),unique(organization_id,development_id,source_key));
create index if not exists lead_distribution_priority_rules_scope_idx on public.lead_distribution_priority_rules(organization_id,development_id,enabled,priority desc);
alter table public.lead_distribution_priority_rules enable row level security;
drop policy if exists lead_distribution_priority_rules_scope on public.lead_distribution_priority_rules;
create policy lead_distribution_priority_rules_scope on public.lead_distribution_priority_rules for select to authenticated using(organization_id=(select public.current_organization_id()));
revoke all on public.lead_distribution_priority_rules from anon;revoke insert,update,delete on public.lead_distribution_priority_rules from authenticated;grant select on public.lead_distribution_priority_rules to authenticated;

create or replace function public.configure_distribution_priority(p_actor_id uuid,p_organization_id uuid,p_development_id uuid,p_source_key text,p_priority integer,p_sla_minutes integer,p_enabled boolean,p_reason text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare actor_role text;normalized_source text;
begin
 select coalesce(commercial_role,case role when 'admin' then 'director' else role end) into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent','manager') then raise exception 'priority_actor_forbidden';end if;
 if not exists(select 1 from public.developments where id=p_development_id and organization_id=p_organization_id) then raise exception 'priority_project_invalid';end if;
 normalized_source:=lower(trim(coalesce(p_source_key,'')));if char_length(normalized_source)<2 or char_length(normalized_source)>80 or p_priority<1 or p_priority>10 or p_sla_minutes<5 or p_sla_minutes>10080 then raise exception 'priority_values_invalid';end if;if char_length(trim(coalesce(p_reason,'')))<10 or char_length(trim(p_reason))>500 then raise exception 'priority_reason_invalid';end if;
 insert into public.lead_distribution_priority_rules(organization_id,development_id,source_key,priority,sla_minutes,enabled,updated_by,reason,updated_at)values(p_organization_id,p_development_id,normalized_source,p_priority,p_sla_minutes,p_enabled,p_actor_id,trim(p_reason),now())on conflict(organization_id,development_id,source_key)do update set priority=excluded.priority,sla_minutes=excluded.sla_minutes,enabled=excluded.enabled,updated_by=excluded.updated_by,reason=excluded.reason,updated_at=excluded.updated_at;
 return jsonb_build_object('developmentId',p_development_id,'sourceKey',normalized_source,'priority',p_priority,'slaMinutes',p_sla_minutes,'enabled',p_enabled,'personalDataUsed',false,'peopleRanking',false,'humanConfigured',true);
end $$;

create or replace function public.distribute_project_leads_v3(p_actor_id uuid,p_organization_id uuid,p_development_id uuid,p_limit integer default 1)
returns jsonb language plpgsql security definer set search_path='' as $$
declare actor_role text;counter integer;selected_lead uuid;selected_source text;selected_priority integer;selected_sla integer;selected_wait integer;selected_broker uuid;selected_load integer;selected_weight integer;selected_last timestamptz;distributed integer:=0;changed integer;assignments jsonb:='[]'::jsonb;
begin
 if p_limit<1 or p_limit>100 then raise exception 'distribution_limit_invalid';end if;select coalesce(commercial_role,case role when 'admin' then 'director' else role end) into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent','manager') then raise exception 'distribution_actor_forbidden';end if;if not exists(select 1 from public.developments where id=p_development_id and organization_id=p_organization_id) then raise exception 'distribution_project_invalid';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_organization_id::text||p_development_id::text,57));
 for counter in 1..p_limit loop
  select l.id,lower(trim(coalesce(l.source,'não informada'))),coalesce(r.priority,5),coalesce(r.sla_minutes,60),greatest(0,floor(extract(epoch from(now()-l.created_at))/60)::integer) into selected_lead,selected_source,selected_priority,selected_sla,selected_wait from public.leads l left join public.lead_distribution_priority_rules r on r.organization_id=p_organization_id and r.development_id=p_development_id and r.source_key=lower(trim(coalesce(l.source,'não informada'))) and r.enabled=true where l.organization_id=p_organization_id and l.development_id=p_development_id and l.assigned_to is null order by(greatest(0,floor(extract(epoch from(now()-l.created_at))/60))::numeric/coalesce(r.sla_minutes,60)) desc,coalesce(r.priority,5) desc,l.created_at,l.id for update of l skip locked limit 1;exit when selected_lead is null;
  with recursive descendants as(select id from public.profiles where id=p_actor_id and organization_id=p_organization_id union all select p.id from public.profiles p join descendants d on p.reports_to=d.id where p.organization_id=p_organization_id and p.active=true),candidates as(select p.id,(select count(*) from public.leads lp where lp.organization_id=p_organization_id and lp.assigned_to=p.id and lp.development_id=p_development_id and lower(coalesce(lp.status,'novo')) not in('won','ganho','vendido','lost','perdido','descartado','discarded','archived','arquivado'))::integer project_load,coalesce(m.weight,1) weight,m.last_assigned_at from public.profiles p join public.commercial_presence cp on cp.profile_id=p.id and cp.organization_id=p_organization_id and cp.availability='available' and cp.last_seen_at>=now()-interval '90 seconds' left join public.project_distribution_members m on m.development_id=p_development_id and m.profile_id=p.id left join public.broker_capacity_limits cap on cap.organization_id=p_organization_id and cap.profile_id=p.id where p.organization_id=p_organization_id and p.active=true and coalesce(p.commercial_role,p.role)='broker' and coalesce(m.enabled,true) and(actor_role='director' or p.id in(select id from descendants)) and(select count(*) from public.leads lt where lt.organization_id=p_organization_id and lt.assigned_to=p.id and lower(coalesce(lt.status,'novo')) not in('won','ganho','vendido','lost','perdido','descartado','discarded','archived','arquivado'))<coalesce(cap.max_active_leads,2147483647) and(select count(*) from public.leads lp where lp.organization_id=p_organization_id and lp.assigned_to=p.id and lp.development_id=p_development_id and lower(coalesce(lp.status,'novo')) not in('won','ganho','vendido','lost','perdido','descartado','discarded','archived','arquivado'))<coalesce(cap.max_project_leads,2147483647))
  select id,project_load,weight,last_assigned_at into selected_broker,selected_load,selected_weight,selected_last from candidates order by(project_load::numeric/weight),last_assigned_at nulls first,id limit 1;if selected_broker is null then raise exception 'distribution_no_broker_with_capacity';end if;
  update public.leads set assigned_to=selected_broker,updated_at=now() where id=selected_lead and organization_id=p_organization_id and development_id=p_development_id and assigned_to is null;get diagnostics changed=row_count;if changed<>1 then raise exception 'distribution_owner_conflict';end if;
  insert into public.project_distribution_members(organization_id,development_id,profile_id,assignments_count,last_assigned_at,updated_at)values(p_organization_id,p_development_id,selected_broker,1,now(),now())on conflict(development_id,profile_id)do update set assignments_count=public.project_distribution_members.assignments_count+1,last_assigned_at=excluded.last_assigned_at,updated_at=excluded.updated_at;
  insert into public.lead_distribution_events(organization_id,development_id,lead_id,assigned_to,actor_id,algorithm,score_snapshot)values(p_organization_id,p_development_id,selected_lead,selected_broker,p_actor_id,'sla_source_priority_v3',jsonb_build_object('algorithm','sla_source_priority_v3','source',selected_source,'sourcePriority',selected_priority,'slaMinutes',selected_sla,'waitingMinutes',selected_wait,'slaRatio',round(selected_wait::numeric/selected_sla,4),'projectLoadBefore',selected_load,'weight',selected_weight,'personalDataUsed',false,'criteria',jsonb_build_array('sla_wait','project','source','capacity','online','weighted_load')));
  assignments:=assignments||jsonb_build_array(jsonb_build_object('leadId',selected_lead,'brokerId',selected_broker,'source',selected_source,'sourcePriority',selected_priority,'slaMinutes',selected_sla,'waitingMinutes',selected_wait,'reason','Maior pressão de SLA; prioridade de origem; antiguidade. Corretor por capacidade e carga ponderada.'));distributed:=distributed+1;selected_lead:=null;selected_broker:=null;
 end loop;
 return jsonb_build_object('distributed',distributed,'developmentId',p_development_id,'algorithm','sla_source_priority_v3','assignments',assignments,'personalDataUsed',false,'peopleRanking',false,'singleOwnerPreserved',true,'capacityEnforced',true,'atomic',true);
end $$;
revoke all on function public.configure_distribution_priority(uuid,uuid,uuid,text,integer,integer,boolean,text) from public,anon,authenticated;grant execute on function public.configure_distribution_priority(uuid,uuid,uuid,text,integer,integer,boolean,text) to service_role;revoke all on function public.distribute_project_leads_v3(uuid,uuid,uuid,integer) from public,anon,authenticated;grant execute on function public.distribute_project_leads_v3(uuid,uuid,uuid,integer) to service_role;
commit;
