begin;
create table if not exists public.lead_assignment_reservations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,lead_id uuid not null references public.leads(id) on delete cascade,broker_id uuid not null references public.profiles(id),distribution_event_id uuid references public.lead_distribution_events(id),status text not null default 'pending' check(status in('pending','accepted','expired','released','superseded')),reserved_at timestamptz not null default now(),expires_at timestamptz not null,accepted_at timestamptz,released_at timestamptz,release_reason text,created_at timestamptz not null default now());
create unique index if not exists lead_assignment_one_pending_idx on public.lead_assignment_reservations(lead_id) where status='pending';create index if not exists lead_assignment_expiry_idx on public.lead_assignment_reservations(status,expires_at) where status='pending';
alter table public.lead_assignment_reservations enable row level security;drop policy if exists lead_assignment_reservations_scope on public.lead_assignment_reservations;create policy lead_assignment_reservations_scope on public.lead_assignment_reservations for select to authenticated using(organization_id=(select public.current_organization_id()) and (broker_id=(select auth.uid()) or (select private.can_view_commercial_profile(broker_id))));revoke all on public.lead_assignment_reservations from anon;revoke insert,update,delete on public.lead_assignment_reservations from authenticated;grant select on public.lead_assignment_reservations to authenticated;

create or replace function public.distribute_project_leads_v4(p_actor_id uuid,p_organization_id uuid,p_development_id uuid,p_limit integer default 1,p_acceptance_minutes integer default 5)returns jsonb language plpgsql security definer set search_path='' as $$
declare result jsonb;assignment jsonb;reservation_id uuid;reservations jsonb:='[]'::jsonb;
begin if p_acceptance_minutes<2 or p_acceptance_minutes>30 then raise exception 'reservation_period_invalid';end if;result:=public.distribute_project_leads_v3(p_actor_id,p_organization_id,p_development_id,p_limit);for assignment in select value from jsonb_array_elements(coalesce(result->'assignments','[]'::jsonb)) loop update public.lead_assignment_reservations set status='superseded',released_at=now(),release_reason='Nova atribuição substituiu a reserva.' where lead_id=(assignment->>'leadId')::uuid and status='pending';insert into public.lead_assignment_reservations(organization_id,lead_id,broker_id,expires_at)values(p_organization_id,(assignment->>'leadId')::uuid,(assignment->>'brokerId')::uuid,now()+make_interval(mins=>p_acceptance_minutes))returning id into reservation_id;reservations:=reservations||jsonb_build_array(jsonb_build_object('reservationId',reservation_id,'leadId',assignment->>'leadId','brokerId',assignment->>'brokerId','expiresInMinutes',p_acceptance_minutes));end loop;return result||jsonb_build_object('algorithm','sla_source_priority_reservation_v4','reservations',reservations,'acceptanceMinutes',p_acceptance_minutes,'acceptanceRequired',true,'safeExpiry',true);end $$;

create or replace function public.accept_lead_assignment(p_actor_id uuid,p_organization_id uuid,p_lead_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$
declare reservation record;
begin select * into reservation from public.lead_assignment_reservations where organization_id=p_organization_id and lead_id=p_lead_id and broker_id=p_actor_id and status='pending' order by created_at desc for update limit 1;if reservation.id is null then raise exception 'reservation_not_found';end if;if reservation.expires_at<=now() then raise exception 'reservation_expired';end if;if not exists(select 1 from public.leads where id=p_lead_id and organization_id=p_organization_id and assigned_to=p_actor_id) then raise exception 'reservation_owner_changed';end if;update public.lead_assignment_reservations set status='accepted',accepted_at=now() where id=reservation.id;insert into public.activities(organization_id,lead_id,user_id,title,description,type,occurred_at)values(p_organization_id,p_lead_id,p_actor_id,'Lead aceita pelo corretor','Aceite registrado dentro do prazo da distribuição.','system',now());return jsonb_build_object('reservationId',reservation.id,'leadId',p_lead_id,'accepted',true,'acceptedAt',now(),'singleOwnerPreserved',true);end $$;

create or replace function public.process_expired_lead_reservations(p_limit integer default 500)returns jsonb language plpgsql security definer set search_path='' as $$
declare item record;released integer:=0;protected integer:=0;
begin if p_limit<1 or p_limit>2000 then raise exception 'reservation_worker_limit_invalid';end if;for item in select r.* from public.lead_assignment_reservations r where r.status='pending' and r.expires_at<=now() order by r.expires_at for update skip locked limit p_limit loop if exists(select 1 from public.activities a where a.organization_id=item.organization_id and a.lead_id=item.lead_id and a.occurred_at>=item.reserved_at and a.type<>'system') then update public.lead_assignment_reservations set status='accepted',accepted_at=now(),release_reason='Atendimento iniciado antes da expiração.' where id=item.id;protected:=protected+1;elsif exists(select 1 from public.leads where id=item.lead_id and organization_id=item.organization_id and assigned_to=item.broker_id) then update public.leads set assigned_to=null,updated_at=now() where id=item.lead_id and organization_id=item.organization_id and assigned_to=item.broker_id;update public.tasks set assigned_to=null where organization_id=item.organization_id and lead_id=item.lead_id and assigned_to=item.broker_id and coalesce(status,'pendente') not in('concluida','completed','cancelado','cancelled');update public.lead_assignment_reservations set status='expired',released_at=now(),release_reason='Prazo de aceite expirado sem interação.' where id=item.id;insert into public.activities(organization_id,lead_id,user_id,title,description,type,occurred_at)values(item.organization_id,item.lead_id,item.broker_id,'Lead devolvida à fila','Prazo de aceite expirou sem interação; responsável removido com segurança.','system',now());released:=released+1;else update public.lead_assignment_reservations set status='superseded',released_at=now(),release_reason='Responsável mudou antes do processamento.' where id=item.id;protected:=protected+1;end if;end loop;return jsonb_build_object('released',released,'protected',protected,'processed',released+protected,'customerContacted',false,'singleOwnerPreserved',true);end $$;
revoke all on function public.distribute_project_leads_v4(uuid,uuid,uuid,integer,integer),public.accept_lead_assignment(uuid,uuid,uuid),public.process_expired_lead_reservations(integer) from public,anon,authenticated;grant execute on function public.distribute_project_leads_v4(uuid,uuid,uuid,integer,integer),public.accept_lead_assignment(uuid,uuid,uuid),public.process_expired_lead_reservations(integer) to service_role;
commit;
