begin;
create table if not exists public.model_release_gates(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,calibration_model_id uuid not null references public.conversion_calibration_models(id) on delete restrict,dataset_version_id uuid not null references public.conversion_dataset_versions(id) on delete restrict,drift_report_id uuid references public.prediction_drift_reports(id) on delete restrict,
 status text not null check(status in('blocked','ready','approved','rejected','rolled_back')),checks jsonb not null,segment_audit jsonb not null,prohibited_attributes_found text[] not null default '{}',
 evaluated_by uuid not null references public.profiles(id),evaluated_at timestamptz not null default now(),decided_by uuid references public.profiles(id),decision_reason text,decided_at timestamptz,rollback_at timestamptz
);
create unique index if not exists model_release_one_approved on public.model_release_gates(organization_id)where status='approved';create index if not exists model_release_gates_latest_idx on public.model_release_gates(organization_id,evaluated_at desc);
alter table public.model_release_gates enable row level security;drop policy if exists model_release_gates_scope on public.model_release_gates;create policy model_release_gates_scope on public.model_release_gates for select to authenticated using(organization_id=(select public.current_organization_id()));revoke all on public.model_release_gates from anon;revoke insert,update,delete on public.model_release_gates from authenticated;grant select on public.model_release_gates to authenticated;grant all on public.model_release_gates to service_role;

create or replace function public.evaluate_model_release_gate(p_actor_id uuid,p_organization_id uuid,p_model_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$declare actor_role text;model_row public.conversion_calibration_models%rowtype;dataset_row public.conversion_dataset_versions%rowtype;drift_row public.prediction_drift_reports%rowtype;segment_data jsonb:='[]'::jsonb;segment_count integer:=0;max_gap numeric:=0;min_gap numeric:=0;forbidden text[]:='{}';explanations integer:=0;checks_value jsonb;ready_value boolean;gate_id uuid;
begin select coalesce(commercial_role,case role when'admin'then'director'else role end)into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role not in('director','superintendent')then raise exception 'model_gate_actor_forbidden';end if;select*into model_row from public.conversion_calibration_models where id=p_model_id and organization_id=p_organization_id;if not found then raise exception 'model_gate_model_not_found';end if;select*into dataset_row from public.conversion_dataset_versions where id=model_row.dataset_version_id and organization_id=p_organization_id;select*into drift_row from public.prediction_drift_reports where organization_id=p_organization_id and active_calibration_version=model_row.version order by generated_at desc limit 1;
 with examples as(select case when coalesce((s.features->>'dataQualityPercent')::numeric,0)<50 then'data_quality_low'when coalesce((s.features->>'dataQualityPercent')::numeric,0)<80 then'data_quality_medium'else'data_quality_high'end segment,s.predicted_probability::numeric predicted,o.label_value::numeric label from public.conversion_feature_snapshots s join lateral(select x.label_value from public.conversion_outcome_labels x where x.organization_id=s.organization_id and x.lead_id=s.lead_id and x.outcome_at>s.feature_cutoff_at and x.outcome_at<=s.feature_cutoff_at+make_interval(days=>s.horizon_days)order by x.outcome_at limit 1)o on true where s.organization_id=p_organization_id and s.feature_cutoff_at<=dataset_row.cutoff_at),segments as(select segment,count(*)n,avg(predicted)predicted_rate,avg(label)*100 observed_rate,avg(power(predicted/100-label,2))brier,abs(avg(predicted)-avg(label)*100)gap from examples group by segment having count(*)>=50)
 select coalesce(jsonb_agg(jsonb_build_object('segment',segment,'count',n,'predictedRate',round(predicted_rate,2),'observedRate',round(observed_rate,2),'calibrationGap',round(gap,2),'brierScore',round(brier,4),'allowedOperationalSegment',true)order by segment),'[]'::jsonb),count(*),coalesce(max(gap),0),coalesce(min(gap),0)into segment_data,segment_count,max_gap,min_gap from segments;
 select array_agg(distinct feature_key)filter(where feature_key is not null)into forbidden from public.conversion_feature_snapshots s cross join lateral jsonb_object_keys(s.features)as feature_keys(feature_key)where s.organization_id=p_organization_id and lower(feature_key)=any(array['gender','race','ethnicity','religion','health','disability','sexual_orientation','political_opinion','cpf','cnpj','address']);forbidden:=coalesce(forbidden,'{}');select count(*)into explanations from public.lead_prediction_explanations where organization_id=p_organization_id and created_at>=now()-interval'30 days';
 checks_value:=jsonb_build_object('datasetValidated',dataset_row.status='validated','modelEligible',model_row.eligible,'modelActivated',model_row.status='active','driftMeasured',drift_row.id is not null,'driftAcceptable',coalesce(drift_row.drift_status,'missing')in('stable','watch'),'segmentSamplesSufficient',segment_count>=2,'maximumCalibrationGap',round(max_gap,2),'calibrationGapSpread',round(max_gap-min_gap,2),'segmentParityAcceptable',segment_count>=2 and max_gap<=15 and max_gap-min_gap<=10,'explanationsLast30Days',explanations,'explainabilityObserved',explanations>=50,'prohibitedAttributesAbsent',cardinality(forbidden)=0,'automaticDecisionAbsent',true);
 ready_value:=dataset_row.status='validated'and model_row.eligible and model_row.status='active'and drift_row.id is not null and drift_row.drift_status in('stable','watch')and segment_count>=2 and max_gap<=15 and max_gap-min_gap<=10 and explanations>=50 and cardinality(forbidden)=0;
 insert into public.model_release_gates(organization_id,calibration_model_id,dataset_version_id,drift_report_id,status,checks,segment_audit,prohibited_attributes_found,evaluated_by)values(p_organization_id,p_model_id,dataset_row.id,drift_row.id,case when ready_value then'ready'else'blocked'end,checks_value,segment_data,forbidden,p_actor_id)returning id into gate_id;return jsonb_build_object('gateId',gate_id,'status',case when ready_value then'ready'else'blocked'end,'checks',checks_value,'segments',segment_data,'humanApprovalRequired',true,'automaticRelease',false,'protectedAttributesUsed',false);
end $$;

create or replace function public.decide_model_release_gate(p_actor_id uuid,p_organization_id uuid,p_gate_id uuid,p_action text,p_reason text)
returns jsonb language plpgsql security definer set search_path='' as $$declare actor_role text;gate_row public.model_release_gates%rowtype;begin select coalesce(commercial_role,case role when'admin'then'director'else role end)into actor_role from public.profiles where id=p_actor_id and organization_id=p_organization_id and active=true;if actor_role<>'director'then raise exception 'model_gate_director_required';end if;if p_action not in('approve','reject','rollback')or char_length(trim(coalesce(p_reason,'')))<10 then raise exception 'model_gate_decision_invalid';end if;perform pg_advisory_xact_lock(hashtextextended('model-release:'||p_organization_id::text,0));select*into gate_row from public.model_release_gates where id=p_gate_id and organization_id=p_organization_id for update;if not found then raise exception 'model_gate_not_found';end if;if p_action='approve'and gate_row.status<>'ready'then raise exception 'model_gate_not_ready';elsif p_action='rollback'and gate_row.status<>'approved'then raise exception 'model_gate_not_approved';elsif p_action='reject'and gate_row.status not in('ready','blocked')then raise exception 'model_gate_not_decidable';end if;if p_action='approve'then update public.model_release_gates set status='rolled_back',rollback_at=now(),decision_reason='Substituído por nova liberação aprovada'where organization_id=p_organization_id and status='approved'and id<>p_gate_id;update public.model_release_gates set status='approved',decided_by=p_actor_id,decision_reason=trim(p_reason),decided_at=now()where id=p_gate_id;elsif p_action='reject'then update public.model_release_gates set status='rejected',decided_by=p_actor_id,decision_reason=trim(p_reason),decided_at=now()where id=p_gate_id;else update public.model_release_gates set status='rolled_back',decided_by=p_actor_id,decision_reason=trim(p_reason),decided_at=now(),rollback_at=now()where id=p_gate_id;update public.conversion_calibration_models set status='archived'where id=gate_row.calibration_model_id and organization_id=p_organization_id;end if;return jsonb_build_object('gateId',p_gate_id,'status',case p_action when'approve'then'approved'when'reject'then'rejected'else'rolled_back'end,'humanDecision',true,'reasonRecorded',true,'automaticRollback',false);end $$;

create or replace function public.apply_active_conversion_calibration(p_organization_id uuid,p_raw_probability numeric)returns numeric language sql stable security definer set search_path='' as $$select coalesce((select(case when(b.value->>'reliable')::boolean then(b.value->>'observedRate')::numeric else greatest(1,least(95,p_raw_probability))end)from public.conversion_calibration_models m join public.model_release_gates g on g.calibration_model_id=m.id and g.organization_id=m.organization_id and g.status='approved'cross join lateral jsonb_array_elements(m.bins)b(value)where m.organization_id=p_organization_id and m.status='active'and p_raw_probability>=(b.value->>'lower')::numeric and p_raw_probability<=(b.value->>'upper')::numeric order by(b.value->>'bucket')::integer limit 1),greatest(1,least(95,p_raw_probability)))$$;
revoke all on function public.evaluate_model_release_gate(uuid,uuid,uuid),function public.decide_model_release_gate(uuid,uuid,uuid,text,text)from public,anon,authenticated;grant execute on function public.evaluate_model_release_gate(uuid,uuid,uuid),function public.decide_model_release_gate(uuid,uuid,uuid,text,text)to service_role;
commit;
