"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import { AtlasBadge, AtlasEmpty, AtlasSkeleton } from "@/components/ui/AtlasUI";

type AgendaItem = { id:string; kind:"task"|"visit"; title:string; at:string|null; status:string; detail:string; href:string };

export default function CalendarPage(){
  const [items,setItems]=useState<AgendaItem[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{void(async()=>{const [tasks,visits]=await Promise.all([supabase.from("tasks").select("id,title,due_at,priority,status,lead_id").order("due_at"),supabase.from("lead_visits").select("id,lead_id,scheduled_at,status,format,location").order("scheduled_at")]);const merged:AgendaItem[]=[...(tasks.data??[]).map(item=>({id:item.id,kind:"task" as const,title:item.title||"Tarefa",at:item.due_at,status:item.status,detail:`Prioridade ${item.priority||"normal"}`,href:item.lead_id?`/leads/${item.lead_id}`:"/tasks"})),...(visits.data??[]).map(item=>({id:item.id,kind:"visit" as const,title:item.format==="video"?"Videochamada com cliente":"Visita com cliente",at:item.scheduled_at,status:item.status,detail:item.location||"Local a confirmar",href:`/leads/${item.lead_id}/schedule`}))].sort((a,b)=>new Date(a.at||"2999").getTime()-new Date(b.at||"2999").getTime());setItems(merged);setLoading(false);})();},[]);
  const groups=useMemo(()=>items.reduce<Record<string,AgendaItem[]>>((acc,item)=>{const key=item.at?new Date(item.at).toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"}):"Sem data";(acc[key]??=[]).push(item);return acc;},{}),[items]);
  return <div className="space-y-6 pb-10"><header><AtlasBadge tone="info">AGENDA UNIFICADA</AtlasBadge><h1 className="mt-4 text-3xl font-semibold tracking-[-.04em] text-white">Calendário operacional</h1><p className="mt-3 text-sm text-slate-400">Tarefas e visitas no mesmo fluxo, sem duplicar compromissos.</p></header>{loading?<div className="grid gap-4">{[1,2,3].map(i=><AtlasSkeleton key={i} className="h-36"/>)}</div>:Object.entries(groups).length?Object.entries(groups).map(([date,list])=><section key={date} className="rounded-3xl border border-white/[.07] bg-white/[.025] p-5"><h2 className="capitalize font-semibold text-white">{date}</h2><div className="mt-4 grid gap-3 lg:grid-cols-2">{list.map(item=><Link href={item.href} key={`${item.kind}-${item.id}`} className="flex items-center justify-between gap-4 rounded-2xl border border-white/[.07] bg-slate-950/50 p-4 transition hover:border-cyan-300/20"><div><div className="flex items-center gap-2"><AtlasBadge tone={item.kind==="visit"?"violet":"neutral"}>{item.kind==="visit"?"VISITA":"TAREFA"}</AtlasBadge><strong className="text-sm text-white">{item.title}</strong></div><p className="mt-2 text-xs text-slate-500">{item.at?new Date(item.at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}):"Sem horário"} · {item.detail}</p></div><span className="text-xs font-semibold text-cyan-200">{item.status}</span></Link>)}</div></section>):<AtlasEmpty title="Agenda livre" description="Nenhuma tarefa ou visita agendada."/>}</div>;
}
